import type {Metadata} from 'next';
import CharityResearchReport,{type CharityReportContent} from '@/components/CharityResearchReport';
import data from '@/data/san-francisco/oa-colonoscopy-cea-v1.json';
import {colonoscopyAccessModel} from '@/lib/surgical-access-model.mjs';
export const metadata:Metadata={title:'Operation Access — diagnostic colonoscopy | Market for Impact',description:'Conditional SF abnormal-FIT follow-up research: explicit cash costs, uncertain health gains and donated-resource sensitivity.'};
const money=(n:number|null)=>n===null?'No finite positive price':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2}).format(n);
const central=data.scenarios.find(s=>s.name==='central')!,r=colonoscopyAccessModel(central,data.resourceSensitivity);
const rows=data.scenarios.map(s=>({...s,calculated:colonoscopyAccessModel(s,data.resourceSensitivity)}));
const content:CharityReportContent={
 organization:'Operation Access',program:'Conditional colonoscopy access after an abnormal FIT',eyebrow:'SAN FRANCISCO · CONDITIONAL RESEARCH',published:'8 September 2026',modelVersion:data.modelId,
 nutshell:{headline:'High-risk diagnostic follow-up is promising. Donated clinical care is not costless.',
 body:<>Our provisional best estimate is <strong>{money(r.costPerTenQalys)} per better life—10 incremental QALYs</strong>. We model support for an uninsured SF adult with an abnormal stool test to complete indicated colonoscopy and subsequent care. This is a conditional estimate, not an available procedure package. <a href="/api/sf-surgical-access-models">Inspect the model and sources →</a></>,
 whyItMayWork:'Targeting abnormal results concentrates preventable health loss, while existing donated-specialist partnerships can reduce donor cash requirements.',
 whyWeAreCautious:'The local marginal completion effect and health benefit versus eventual alternative care are unknown. The favorable cash result does not survive the illustrative added-resource calculation.',
 recommendationBlocker:'No additional SF slot, accepted restricted gift or marginal funding amount is verified; downstream treatment must be available.'},
 summary:[{label:'COST PER BETTER LIFE',value:money(r.costPerTenQalys),detail:'per 10 QALYs; conditional donor-cash estimate'},{label:'POSITIVE SCENARIOS',value:'$67K–$50M',detail:'Joint judgments, not confidence bounds; null/harm possible'},{label:'CASH COST PER PATHWAY',value:'$1,500',detail:'Research allocation informed by mixed-service audited costs'},{label:'FUNDING ROOM',value:'Unknown',detail:'Funding pressure is documented, but no marginal tranche is priced'}],
 programSection:{body:'Operation Access matches uninsured patients with donated specialist care and coordinates preparation, interpretation, transport and follow-up. Its current records confirm SF service and a colorectal pathway; abnormal stool tests are a major referral reason. Its 2025 total of 1,529 completed services and 575 gastroenterology services covers a wider region. Neither is a count of SF positive-FIT colonoscopies.',
 steps:[{title:'Identify a clinically indicated follow-up',detail:'The modeled adult has an abnormal FIT, not merely a routine screening invitation; eligibility and actual local referral must be confirmed.'},{title:'Complete the coordinated pathway',detail:'Match specialist capacity and support preparation, access and follow-up. Costs allocate work on failed referrals to completed pathways.'},{title:'Ensure treatment can follow diagnosis',detail:'A diagnosis alone cannot receive the benefit of successful subsequent cancer treatment.'}],
 boundary:data.intervention.scope+' The modeled age range is 50–75; the external mortality cohort was 50–69. The share of an unrestricted gift reaching SF and current additional capacity remain unknown.'},
 model:{headline:money(r.costPerTenQalys)+' per 10 QALYs',
 body:'Audited 2025 expense minus donated clinical charges and other donated support is $2,256,966: about $1,476 per mixed completed service. We round to a judgmental $1,500 for a colonoscopy pathway, including overhead and failed-referral work. Half the activity is assumed additionally enabled, with 0.05 net QALY per enabled completion. This is a coarse judgment model, not a validated cancer-stage simulation.',
 equation:{label:'DONOR DOLLARS PER 10 QALYS',expression:'10 × $1,500 ÷ (0.5 × 0.05)',result:money(r.costPerTenQalys)},inputColumnLabel:'Central input',
 inputs:[{key:'cost',label:'Cash allocation per completed pathway',best:'$1,500',range:'$1,000–$2,500',confidence:'Audited anchor; judgmental allocation',basis:'Mixed-service average is not a colonoscopy-specific marginal quote. Annual-report cash expense differs from audit subtraction by $1.'},{key:'additionality',label:'Marginally enabled share',best:'50%',range:'10–75%; zero also possible',confidence:'Research judgment',basis:'Financing/supply expansion instead of replacement funding. Alternative clinical timing is handled in net QALYs, not discounted here again. Not estimated from reserves.'},{key:'health',label:'Net QALY per enabled completion',best:'0.05',range:'0.005–0.20; null/harm also possible',confidence:'Aggregate research judgment',basis:'Includes health consequences and procedure harms conceptually. External observational mortality is only a scale check, not a causal coefficient.'}],
 giftHeading:'Joint scenarios—not verified donation offers',
 sensitivity:rows.map(s=>({case:s.name,headline:money(s.calculated.costPerTenQalys),detail:s.calculated.netQalys+' incremental QALY per pathway equivalent'})),
 uncertaintyBoundary:'No extra navigation completion multiplier is used on the completed-pathway denominator. A randomized navigation contrast of 13 percentage points is a different intervention, not the effect of this already-navigated service. Zero funding assumes identical replacement, so clinical harms also cancel; donor opportunity costs or administrative harms remain unmodeled.',
 fundingBoundary:'The 2025 report describes losing its largest funder and layoffs; the 2026 cash budget is $1.9M. That supports a capacity concern, not a quantified marginal health effect. Restricted colorectal funds and other donors already support care. Neither a deficit nor procedure volume proves room for more funding.'},
 comparisonBridge:{headline:'The favorable donor-cash case is not a full-resource bargain',body:'Adding a judgmental $2,000 clinical resource cost and $60 donated support per additionally enabled completion raises central cost-effectiveness to $1.012M/10 QALYs, and the favorable case to about $170K. Waived clinical charges are not economic opportunity costs.',
 equation:{label:'DONOR BUDGET PLUS INDUCED RESOURCES',expression:'10 × [$1,500 + 0.5 × ($2,000 + $60)] ÷ 0.025',result:money(r.expandedResourcePrice)},inputs:[],
 sensitivity:rows.slice(0,3).map(s=>({case:s.name,headline:money(s.calculated.expandedResourcePrice),detail:'Expanded numerator '+money(s.calculated.expandedCost)+'; not a complete societal analysis'})),
 boundary:'Extra cancer treatment, surveillance, patient time and net payer savings are unquantified. At central cash/additionality, health gain must exceed 0.30 QALY per enabled completion to beat $100K/10 QALYs. The favorable case requires more than 0.133 QALY; this is a testable hypothesis, not demonstrated local yield.'},
 evidence:[{key:'Current operating evidence',design:'2025 audited finances and annual report; 2026 budget',population:'Regional services including SF, not a dedicated measured SF FIT cohort',result:'Actual clinical-access pathway and funding pressure are documented; $1,476 mixed-service cash-like average informs cost.',transfer:'Cash-like accrual cost is not cash flow, marginal price or the full cost of donated medicine.'},{key:'Positive-FIT mortality',design:'Observational Italian screening cohort',population:'Adults 50–69 with FIT above 20 micrograms Hb/g',result:'Ten-year CRC mortality was 6.8 versus 16 per 1,000 for within-program colonoscopy compliers versus noncompliers.',transfer:'Noncompliers could receive care elsewhere. Confounding, exposure timing and immortal-time concerns preclude treating the 0.0092 difference as causal OA impact.'},{key:'Navigation trial',design:'PRECISE randomized trial',population:'967 in primary analysis after abnormal stool testing',result:'Completion was 55.1% versus 42.1%, a 13-point difference against existing referral outreach.',transfer:'Useful evidence that navigation can work; not multiplied into this completed-service model.'}],
 reservations:['The central 0.05 QALY is a judgment, not a fitted effect. A rough 0.0092 mortality association × 10 discounted QALYs gives 0.092 only as a scale illustration. The 10-QALY judgment must cover both remaining health and delay until a possible death; no survival curve or discount schedule was estimated.','The favorable 0.20 net QALY requires a stronger long-delay or high-risk contrast than the central scale check, and remains unverified.','Later ordinary care, low remaining risk or unavailable cancer treatment could substantially reduce benefit.','The $20.53M in waived clinical charges is not an economic valuation of resources.','Recipient and geographic restrictions require verification before treating an unrestricted gift as this modeled pathway.'],
 excludedBenefits:['No extra navigation effect on top of a completed-pathway yield.','No separate added morbidity, survival or family credit on top of aggregate net QALYs.','No assumption all gastroenterology services are positive-FIT follow-ups or SF residents.'],
 sources:[...data.sourceDocuments.map(s=>({publisher:'Provider or public agency',title:s.id,url:s.url,published:'date' in s?s.date:'Not stated',retrieved:data.reviewDate,sourceType:'Primary program/financial source'})),{publisher:'Primary research',title:'Positive-FIT mortality cohort',url:data.externalEvidence.mortality.primaryUrl,published:'2021',retrieved:data.reviewDate,sourceType:'Observational cohort'},{publisher:'Primary research',title:'Methodological critique',url:data.externalEvidence.mortality.methodologicalCritiqueUrl,published:'2023',retrieved:data.reviewDate,sourceType:'Methodological correspondence'},{publisher:'Primary research',title:'PRECISE navigation trial',url:data.externalEvidence.navigation.primaryUrl,published:'2025',retrieved:data.reviewDate,sourceType:'Randomized trial'}],
};
export default function Page(){return <CharityResearchReport content={content}/>;}
