import type {Metadata} from 'next';
import CharityResearchReport,{type CharityReportContent} from '@/components/CharityResearchReport';
import data from '@/data/san-francisco/hearing-access-cea-v2.json';
import {hearingAccessModel} from '@/lib/hearing-access-model.mjs';
export const metadata:Metadata={title:'Hearing and Speech Center — adult hearing access | Market for Impact',description:'Conditional adult hearing-aid cost-effectiveness with finite health exposure and an unresolved recipient-status warning.'};
const money=(n:number|null)=>n===null?'No finite positive price':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2}).format(n);
const result=hearingAccessModel(data.scenarios[0]);
const input=(key:string,label:string,best:string,range:string,basis:string)=>({key,label,best,range,basis,confidence:'Low / judgmental'});
const content:CharityReportContent={
 organization:data.clinical_operator,program:'Adult hearing-aid access with Project Homeless Connect',eyebrow:'SAN FRANCISCO · CONDITIONAL RESEARCH',published:'8 September 2026',modelVersion:data.model_id,
 nutshell:{headline:'Supported hearing care can improve health. Both funding and recipient status need clarification.',
 body:<>Our provisional central estimate is <strong>{money(result.costPerTenQalys)} per better life—10 incremental QALYs</strong>. The extended favorable scenario is $74K, but requires four years of cheap sustained support and rises above $100K when a donated-device allowance is included. <a href="/api/sf-hearing-model">Inspect the model and sources →</a></>,
 whyItMayWork:'Assessed, fitted and rehabilitated hearing care can improve hearing-sensitive health utility; donating a device alone is not the intervention.',
 whyWeAreCautious:"The external evidence covers a short follow-up period. Local fitting costs, delays in accessing alternative care and continued hearing-aid use are unknown.",
 recommendationBlocker:'IRS data list the historical EIN as automatically revoked, with no reinstatement date recorded. Later reinstatement or a successor is unverified. This does not establish clinic closure; no direct gift is recommended.'},
 summary:[{label:'COST PER BETTER LIFE',value:money(result.costPerTenQalys),detail:'per 10 QALYs; conditional donor cash'},{label:'POSITIVE SCENARIOS',value:'$74K–$160M',detail:"Extended favorable scenario; not a confidence interval"},{label:'CENTRAL CASH BUDGET',value:'$1,500',detail:'Complete offered course, including failures and one-year support'},{label:'FUNDING / RECIPIENT',value:'Unverified',detail:'Historical EIN revocation; no priced marginal offer'}],
 programSection:{body:'PHC’s Core Senses page names the Center as its hearing partner and describes screening, necessary aids, batteries, support and follow-up without requiring insurance. The Center describes donated-device refurbishment. Neither page supplies a current eligible backlog, stock yield or price.',
 steps:[{title:'Start with an eligible willing adult',detail:'This denominator begins after clinical eligibility. Add broad outreach/screening costs if needed.'},{title:'Offer assessed and fitted care',detail:'One or both ears as indicated produce one person-level outcome; failed offers remain in costs.'},{title:'Support useful incremental hearing',detail:'Count use and benefit before equivalent alternative care catches up, within a finite funded window.'}],
 boundary:'The shared hearing ledger is phc-hsc-adult-hearing-aid-access. PHC’s separately reviewed glasses pathway is distinct; do not credit hearing QALYs twice or silently reroute a gift to PHC without confirming control and restriction. Clinical registry status is not charitable eligibility.'},
 model:{headline:money(result.costPerTenQalys)+' per 10 QALYs',
 body:'The 0.12 external HUI3 increment is utility, not QALYs. We retain half for local transfer, assume 80% pre-fitting completion, half an effective incremental year and 50% financing additionality. The result is 0.012 QALY per offered $1,500 course. These local inputs are explicit judgments, not a measured Center effect.',
 equation:{label:'DONOR DOLLARS PER 10 QALYS',expression:'10 × $1,500 ÷ (0.12 × 0.5 × 0.8 × 0.5 × 0.5)',result:money(result.costPerTenQalys)},
 inputColumnLabel:'Central assumption',
 inputs:[input('cost','Complete course cash commitment','$1,500','$900–$2,500','$600 paid clinical labor, $250 refurbishment/molds, $250 support, $200 coordination/failures and $200 facility/admin allowance; all constructed costs.'),
 input('utility','External utility increment','0.12','0.01–0.12','Three-month hearing-sensitive HUI3 result. The low value is instrument sensitivity, not a local trial finding.'),
 input('transfer','Clinical/population transfer','50%','50–75%','Singapore selected older adults differ from SF adults experiencing homelessness.'),
 input('completion','Pre-fitting completion','80%','50–90%','Separate from later nonuse already included in effective exposure.'),
 input('exposure','Discounted effective health years','0.5','0.25–2; extended case separate','Central stops after one calendar year; favorable stops after four. Annual profiles already include ramp, nonuse, mortality and alternative-care catch-up.'),
 input('funding','Financing additionality','50%','25–75%; zero possible','Replacement funding reduces new services. Public coverage and other accessible care belong in the comparator, not automatic free-benefit claims.')],
 giftHeading:'Finite-horizon scenarios and explicit nulls',
 sensitivity:data.scenarios.map(s=>{const r=hearingAccessModel(s);return {case:s.name.replaceAll('_',' '),headline:money(r.costPerTenQalys),detail:r.netQalys+' incremental QALYs; '+s.calendar_horizon_years+' calendar-year window'};}),
 uncertaintyBoundary:'End-of-year discounting is 3%. Central annual incremental exposure fraction 0.515 gives 0.5 discounted years; favorable 0.538054 in each of four years gives two. These are constructed schedules, not observed adherence. The whole cash budget is committed at time zero, including support across the entire calendar window. Shared pathway harms sit inside financing additionality; independent donor health harms can persist outside it.',
 fundingBoundary:'The favorable $150 support allowance must cover all four years, about $37.50 annually, not just two effective years. Loss, repairs and replacement may make that unrealistic. No current restricted package or additional fitting capacity is verified. No insurance requirement does not imply no public alternatives.'},
 comparisonBridge:{headline:'The attractive extended case is not a complete resource bargain',
 body:'A judgmental $600 donated-stock allowance raises central cost to $1.75M/10 QALYs and the extended case to $123K. This is gross cash-plus-stock per commissioned offer, not a net societal ICER or a retail device price.',
 equation:{label:'CENTRAL CASH PLUS STOCK',expression:'10 × ($1,500 + $600) ÷ 0.012',result:'$1.75M'},
 inputs:[],sensitivity:data.scenarios.slice(0,3).map(s=>({case:s.name.replaceAll('_',' '),headline:money(hearingAccessModel(s).resourceCostPerTenQalys),detail:'Gross resource diagnostic; patient time unknown'})),
 boundary:'At central health, the donor budget must fall below $120 to beat $100K/10 QALYs. Keeping $1,500 would require 6.25 effective years—impossible within the one-year core horizon, not an available sensitivity. No healthcare savings or unpriced extension is credited.'},
 evidence:[{key:'Clinical utility',design:'Kaur et al., 2020 delayed-start community-centre study',population:'Selected Singapore adults with hearing loss seeking aids; analyzed groups 264 and 163',result:'Reported HUI3 utility increment 0.12 after three months.',transfer:'Modified control questionnaire and short follow-up limit transfer. Do not import the paper’s five-year ICER, infer first-ever use from ten-year nonuse, or add dementia/mortality benefits.'},{key:'Continuing use',design:'One-year telephone follow-up',population:'66% response subset',result:'71.4% of respondents reported use.',transfer:'Not whole-cohort persistence and not evidence for the four-year local favorable case.'},{key:'Local operating pathway',design:'PHC and provider websites',population:'SF shared hearing pathway',result:'Necessary hearing care and follow-up are described.',transfer:'Website freshness, marginal costs and actual additional slots are unresolved.'},{key:'Recipient identity',design:'Primary IRS bulk-data audit, datasets labeled June 9, 2026',population:'Historical EIN 94-1322198',result:"Automatic revocation effective November 15, 2025; posted March 10, 2026; reinstatement field blank. No matching entry was found in the checked IRS Publication 78 data.",transfer:"The dataset date does not exclude a later reinstatement or successor organization. An active National Provider Identifier (NPI) does not establish tax-exempt status, current service availability or closure."}],
 reservations:['Recipient status must be resolved before promoting a donation route; the model is clinical research, not tax advice.','The hypothetical $900 four-year course is unusually optimistic on support costs and persistence.','Medi-Cal, Medicare Advantage and appropriate OTC alternatives may shorten incremental access; the cited 2024 Medi-Cal handbook is not a verified 2026 plan-specific authorization.','Patient time and additional outreach are unpriced. Clinical labor is paid in the constructed budget even if currently volunteered.'],
 excludedBenefits:['No second PHC hearing credit, extra retention multiplier or per-ear multiplication.','No imported five-year lifetime ICER, dementia prevention, mortality or employment benefit.','No implication that automatic revocation proves clinic closure or misconduct.'],
 sources:[{publisher:'Kaur et al.',title:'Cost-utility analysis of hearing aid device for older adults in the community',url:data.source_inputs.utility_anchor.source,published:'1 December 2020',retrieved:data.as_of,sourceType:'Primary delayed-start study'},
 {publisher:'PHC',title:'Core Senses partnership',url:data.source_inputs.local_pathway,published:'Not stated',retrieved:data.as_of,sourceType:'Primary program disclosure'},
 {publisher:'Hearing and Speech Center',title:'Donated-device pathway',url:data.source_inputs.donated_device_pathway,published:'Not stated',retrieved:data.as_of,sourceType:'Provider disclosure'},
 {publisher:'IRS',title:'Tax-exempt bulk data and dataset dates',url:data.identityEvidence.bulkPage,published:'Dataset labeled June 9, 2026',retrieved:data.as_of,sourceType:'Primary identity data'},
 {publisher:'IRS',title:'Automatic-revocation records',url:data.identityEvidence.revocationZip,published:'Dataset labeled June 9, 2026',retrieved:data.as_of,sourceType:'Primary bulk ZIP'},
 {publisher:'IRS',title:'Publication 78',url:data.identityEvidence.publication78Zip,published:'Dataset labeled June 9, 2026',retrieved:data.as_of,sourceType:'Primary bulk ZIP'},
 {publisher:'CMS',title:'Clinical NPI—not exemption',url:data.source_inputs.active_clinical_npi_not_charity_status,published:'Record updated June 8, 2026',retrieved:data.as_of,sourceType:'Primary registry'},
 {publisher:'Medicare',title:'Hearing-aid coverage',url:data.source_inputs.medicare_baseline,published:'Current page',retrieved:data.as_of,sourceType:'Official coverage'},
 {publisher:'DHCS',title:'2024 Medi-Cal handbook',url:data.source_inputs.medi_cal_baseline,published:'2024',retrieved:data.as_of,sourceType:'Historical official baseline'},
 {publisher:'FDA',title:'OTC hearing-aid boundaries',url:data.source_inputs.otc_baseline,published:'Current page',retrieved:data.as_of,sourceType:'Official device guidance'}],
};
export default function Page(){return <CharityResearchReport content={content}/>;}
