import type {Metadata} from 'next';
import CharityResearchReport,{type CharityReportContent} from '@/components/CharityResearchReport';
import data from '@/data/san-francisco/hearing-access-cea-v2.json';
import {hearingCalibratedModel as hearingAccessModel,hearingDiagnostics,modelVersion,scenarios} from '@/lib/hearing-calibrated-model.mjs';
export const metadata:Metadata={title:'Hearing and Speech Center — adult hearing access | Market for Impact',description:'Conditional adult hearing-aid cost-effectiveness with finite health exposure and an unresolved recipient-status warning.'};
const money=(n:number|null)=>n===null?'No finite positive price':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2}).format(n);
const result=hearingAccessModel();
const incomeCases=hearingDiagnostics();
const input=(key:string,label:string,best:string,range:string,basis:string)=>({key,label,best,range,basis,confidence:'Low / judgmental'});
const content:CharityReportContent={
 organization:data.clinical_operator,program:'Adult hearing-aid access with Project Homeless Connect',eyebrow:'SAN FRANCISCO · CONDITIONAL RESEARCH',published:'8 September 2026',calibrationDate:'2026-10-01',modelVersion,
 nutshell:{headline:'Supported hearing care can improve health. Both funding and recipient status need clarification.',
 body:<>Our provisional central estimate is <strong>{money(result.costPerTenQalys)} per better life—10 combined health and income-equivalent years</strong>. The revised central estimate replaces the original $1.25M assumption with independently reassessed hearing exposure and a small net-income contribution. <a href="/api/sf-hearing-model">Inspect the model and sources →</a></>,
 whyItMayWork:'Assessed, fitted and rehabilitated hearing care can improve hearing-sensitive health utility; donating a device alone is not the intervention.',
 whyWeAreCautious:"The external evidence covers a short follow-up period. Local fitting costs, delays in accessing alternative care and continued hearing-aid use are unknown.",
 recommendationBlocker:'IRS data list the historical EIN as automatically revoked, with no reinstatement date recorded. Later reinstatement or a successor is unverified. This does not establish clinic closure; no direct gift is recommended.'},
 summary:[{label:'COST PER BETTER LIFE',value:money(result.costPerTenQalys),detail:'per 10 combined equivalent years; conditional donor cash'},{label:'POSITIVE SCENARIOS',value:'Judgment sensitivities',detail:"Instrument, duration and income assumptions; not a confidence interval"},{label:'CENTRAL CASH BUDGET',value:'$1,500',detail:'Complete offered course, including failures and one-year support'},{label:'FUNDING / RECIPIENT',value:'Unverified',detail:'Historical EIN revocation; no priced marginal offer'}],
 programSection:{body:'PHC’s Core Senses page names the Center as its hearing partner and describes screening, necessary aids, batteries, support and follow-up without requiring insurance. The Center describes donated-device refurbishment. Neither page supplies a current eligible backlog, stock yield or price.',
 steps:[{title:'Start with an eligible willing adult',detail:'This denominator begins after clinical eligibility. Add broad outreach/screening costs if needed.'},{title:'Offer assessed and fitted care',detail:'One or both ears as indicated produce one person-level outcome; failed offers remain in costs.'},{title:'Support useful incremental hearing',detail:'Count use and benefit before equivalent alternative care catches up, within a finite funded window.'}],
 boundary:'The shared hearing ledger is phc-hsc-adult-hearing-aid-access. PHC’s separately reviewed glasses pathway is distinct; do not credit hearing QALYs twice or silently reroute a gift to PHC without confirming control and restriction. Clinical registry status is not charitable eligibility.'},
 model:{headline:money(result.costPerTenQalys)+' per better life',
 body:'The revised external benchmark is 0.11 hearing-sensitive HUI3 utility, with 50% local transfer, 80% completion and 50% financial additionality. A quarter-year care delay leaves nine months of funded benefit; persistence, survival and access to alternative care give 0.491 discounted clinical years. Net household resources are modeled separately. The conservative central overlap allocation excludes 10% of positive clinical credit for the income-responsive subgroup, rather than preserving the original total by subtraction.',
 equation:{label:'DONOR DOLLARS PER BETTER LIFE',expression:'10 × $1,500 ÷ (0.0097151 health years + 0.0002333 income-equivalent years)',result:money(result.costPerTenQalys)},
 incomeLedger:{paragraphs:[
 'Better communication can support work and avoid some household spending. Fitting visits, travel, missed work and lost benefits can offset those gains. A Guatemala before-and-after comparison found a small rise in median household income among recipients while comparison income fell; individual recipient income did not significantly improve. Selection, confounding and different labor markets prevent importing that contrast as a local causal wage effect.',
 'Our provisional central income judgment assumes 10% of additional completed households gain net 2% annual resources during nine months, with an independently specified 80% economic exposure. These are small positive local priors, not measured HSC earnings or the Guatemala median contrast. Net resources include earnings offsets, taxes, withdrawn benefits and work costs. Zero and negative income cases remain plausible.',
 'Using Coefficient Giving’s welfare comparison, income-equivalent years equal 0.5 × additional completed households × affected share × independently discounted income exposure × log(resource ratio). This is a welfare equivalence, not a clinical QALY. Clinical transfer and aid-use persistence do not reduce income again; neither clinical nor income benefit is extended beyond the funded year.',
 'We add no device retail-value saving without evidence that the person otherwise pays for an equivalent aid. Health and household benefits from the same PHC/HSC course must be allocated once in a portfolio. HUI3 includes emotion and cognition. We therefore exclude positive clinical credit proportionately for the assumed 10% earners, assuming they have the same unmet-care distribution as other completed patients. If all earners instead belong to the unmet-care subgroup, a 12.5% exclusion is appropriate. A separate coexistence sensitivity retains communication and income benefits together. Neither allocation removes clinical harms. Funding or completion failure gives no recipient earnings from nonexistent additional fittings; independent donor harm can still remain.',
 ],scenarios:[['central','Central health and income'],['clinical and income coexist','Coexisting health and income'],['zero income','Zero income'],['negative income','Negative income'],['shorter clinical exposure','Shorter clinical exposure'],['no additional funding','No additional funding']].map(([key,label])=>{const r=incomeCases[key as keyof typeof incomeCases];return {case:label,headline:money(r.costPerTenQalys),detail:r.healthYears.toPrecision(4)+' health QALYs + '+r.incomeEquivalentYears.toPrecision(4)+' income-equivalent years per offered course'};})},
 inputColumnLabel:'Central assumption',
 inputs:[input('cost','Complete course cash commitment','$1,500','$900–$2,500','$600 paid clinical labor, $250 refurbishment/molds, $250 support, $200 coordination/failures and $200 facility/admin allowance; all constructed costs.'),
 input('utility','External utility increment','0.11','0.01–0.14','Three-study acoustic hearing-aid HUI3 meta-analysis; EQ5D studies show a near-zero generic change. Heterogeneous instruments, not a local causal estimate.'),
 input('transfer','Clinical/population transfer','50%','50–75%','Singapore selected older adults differ from SF adults experiencing homelessness.'),
 input('completion','Pre-fitting completion','80%','50–90%','Separate from later nonuse already included in effective exposure.'),
 input('exposure','Discounted clinical exposure','0.491','Shorter window and faster alternative care possible','Quarter-year delay, nine months funded benefit, 85% relative persistence, 80% without equivalent care, 98% survival and 3% within-year discounting; local judgments.'),
 input('funding','Financing additionality','50%','25–75%; zero possible','Replacement funding reduces new services. Public coverage and other accessible care belong in the comparator, not automatic free-benefit claims.')],
 giftHeading:'Finite-horizon scenarios and explicit nulls',
 sensitivity:scenarios.map(s=>{const r=hearingAccessModel(s.overrides);return {case:s.name,headline:money(r.costPerTenQalys),detail:r.healthYears.toPrecision(4)+' health years + '+r.incomeEquivalentYears.toPrecision(4)+' income-equivalent years; at most one funded year'};}),
 uncertaintyBoundary:'Discounting is 3% within the year. The old 0.515 profile and four-year favorable scenario are preserved in the historical model, not used in current rankings. Current delay, persistence, unmet care and income exposure are explicit judgments, not observed adherence. The whole cash budget is committed at time zero, including support across the entire calendar window. Shared pathway harms sit inside financing additionality; independent donor health harms can persist outside it.',
 fundingBoundary:'Original FY2022, FY2021 and FY2020 returns show whole expenses of $2,316,008, $2,352,018 and $2,713,993: a historical mean of $2,460,673, not a current funding shortfall or marginal course price. FY2022 audiology expense was $473,752, separate from school and speech programs. Later original accounts were not located. No current restricted package or additional fitting capacity is verified.'},
 comparisonBridge:{headline:'Donated devices are a separate resource input',
 body:'A judgmental $600 donated-stock allowance is added to the $1,500 donor course cost for the gross-resource diagnostic. It is not an induced spending estimate, a retail device price or a net societal ICER.',
 equation:{label:'CENTRAL CASH PLUS STOCK',expression:'10 × ($1,500 + $600) ÷ combined health and income-equivalent years',result:money(result.resourceCostPerTenQalys)},
 inputs:[],sensitivity:scenarios.slice(0,3).map(s=>({case:s.name,headline:money(hearingAccessModel(s.overrides).resourceCostPerTenQalys),detail:'Gross resource diagnostic; patient time unknown'})),
 boundary:'The model counts all offered-course cost before completion and funding substitution. Extending benefit beyond the funded year would require a separately costed support plan, not an unpriced lifetime assumption. No healthcare savings or unpriced extension is credited.'},
 evidence:[{key:'Clinical utility',design:'Kaur et al., 2020 delayed-start community-centre study',population:'Selected Singapore adults with hearing loss seeking aids; analyzed groups 264 and 163',result:'Reported HUI3 utility increment 0.12 after three months.',transfer:'Modified control questionnaire and short follow-up limit transfer. Do not import the paper’s five-year ICER, infer first-ever use from ten-year nonuse, or add dementia/mortality benefits.'},{key:'Continuing use',design:'One-year telephone follow-up',population:'66% response subset',result:'71.4% of respondents reported use.',transfer:'Not whole-cohort persistence and not evidence for the four-year local favorable case.'},{key:'Local operating pathway',design:'PHC and provider websites',population:'SF shared hearing pathway',result:'Necessary hearing care and follow-up are described.',transfer:'Website freshness, marginal costs and actual additional slots are unresolved.'},{key:'Recipient identity',design:'Primary IRS bulk-data audit, revocation data labeled September 8 and Publication 78 labeled September 10, 2026',population:'Historical EIN 94-1322198',result:"Automatic revocation effective November 15, 2025; posted March 10, 2026; reinstatement field blank. No matching entry was found in the checked IRS Publication 78 data.",transfer:"The dataset date does not exclude a later reinstatement or successor organization. An active National Provider Identifier (NPI) does not establish tax-exempt status, current service availability or closure."}],
 reservations:['Recipient status must be resolved before promoting a donation route; the model is clinical research, not tax advice.','Hearing-sensitive and generic utility instruments disagree; local benefit magnitude and persistence remain uncertain.','Medi-Cal, Medicare Advantage and appropriate OTC alternatives may shorten incremental access; the current adult DHCS guidance includes aid/fitting/repair coverage, but does not establish actual approvals or accessible fitting slots for this cohort.','Patient time and additional outreach are unpriced. Clinical labor is paid in the constructed budget even if currently volunteered.'],
 excludedBenefits:['No second PHC hearing credit, extra retention multiplier or per-ear multiplication.','No imported five-year lifetime ICER, dementia prevention, mortality or measured local employment gain; signed income cases are explicit judgments.','No implication that automatic revocation proves clinic closure or misconduct.'],
 sources:[{publisher:'Borre et al.',title:'Impact of Hearing Loss and Its Treatment on Health-Related Quality of Life Utility',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC9905346/',published:'2022',retrieved:'2026-10-01',sourceType:'Original systematic review: heterogeneous utility instruments; Kaur included, not independent replication'},
 {publisher:'Kaur et al.',title:'Cost-utility analysis of hearing aid device for older adults in the community',url:data.source_inputs.utility_anchor.source,published:'1 December 2020',retrieved:'2026-10-01',sourceType:'Primary delayed-start study'},
 {publisher:'PHC',title:'Core Senses partnership',url:data.source_inputs.local_pathway,published:'Not stated',retrieved:'2026-10-01',sourceType:'Primary program disclosure'},
 {publisher:'Hearing and Speech Center',title:'Donated-device pathway',url:data.source_inputs.donated_device_pathway,published:'Not stated',retrieved:'2026-10-01',sourceType:'Provider disclosure'},
 {publisher:'IRS',title:'Tax-exempt bulk data and dataset dates',url:data.identityEvidence.bulkPage,published:'September 2026 dataset labels',retrieved:'2026-10-01',sourceType:'Primary identity data'},
 {publisher:'IRS',title:'Automatic-revocation records',url:data.identityEvidence.revocationZip,published:'September 2026 dataset labels',retrieved:'2026-10-01',sourceType:'Primary bulk ZIP'},
 {publisher:'IRS',title:'Publication 78',url:data.identityEvidence.publication78Zip,published:'September 2026 dataset labels',retrieved:'2026-10-01',sourceType:'Primary bulk ZIP'},
 {publisher:'CMS',title:'Clinical NPI—not exemption',url:data.source_inputs.active_clinical_npi_not_charity_status,published:'Record updated June 8, 2026',retrieved:'2026-10-01',sourceType:'Primary registry'},
 {publisher:'Medicare',title:'Hearing-aid coverage',url:data.source_inputs.medicare_baseline,published:'Current page',retrieved:'2026-10-01',sourceType:'Official coverage'},
 {publisher:'DHCS',title:'2024 Medi-Cal handbook',url:data.source_inputs.medi_cal_baseline,published:'2024',retrieved:'2026-10-01',sourceType:'Historical official baseline'},
 {publisher:'FDA',title:'OTC hearing-aid boundaries',url:data.source_inputs.otc_baseline,published:'Current page',retrieved:'2026-10-01',sourceType:'Official device guidance'},
 {publisher:'Spreckley et al.',title:'Hearing aids and livelihoods in Guatemala',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC7277678/',published:'2020',retrieved:'2026-10-01',sourceType:'Primary nonrandomized comparison'},
 {publisher:'Coefficient Giving',title:'Cost-effectiveness and income-welfare comparison',url:'https://coefficientgiving.org/research/cost-effectiveness/',published:'Current methodology',retrieved:'2026-10-01',sourceType:'Primary valuation framework'},
 {publisher:'DHCS',title:'Adult hearing-aid benefit and covered support',url:'https://www.dhcs.ca.gov/services/hearing-aid-benefit-cap-benefits-frequently-asked-questions-for-members/',published:'Current official coverage',retrieved:'2026-10-01',sourceType:'Primary coverage guidance'},
 ...[['2022','202301359349320515'],['2021','202211369349314371'],['2020','202131349349306533']].map(([year,id])=>({publisher:'Hearing and Speech Center / IRS',title:'FY'+year+' original Form 990',url:'https://projects.propublica.org/nonprofits/full_text/'+id+'/IRS990',published:year,retrieved:'2026-10-01',sourceType:'Primary return reconstruction'}))],
};
export default function Page(){return <CharityResearchReport content={content}/>;}
