import type { Metadata } from 'next';
import CharityResearchReport, { type CharityReportContent } from '@/components/CharityResearchReport';
import model from '@/data/san-francisco/rams-depression-cea-v1.json';
import { signedCourseQalyModel } from '@/lib/signed-course-qaly-model.mjs';
export const metadata: Metadata = { title:'RAMS | Market for Impact', description:'An explicit depression-counseling model with psychodynamic/CBT transfer uncertainty.' };
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2});
const scenarios=model.scenarios.map(s=>({...s,result:signedCourseQalyModel(s)}));const central=scenarios[1];
const content:CharityReportContent={
 organization:model.organization,program:model.program,eyebrow:'CHARITY RESEARCH · SAN FRANCISCO · EXPLORATORY',published:'7 September 2026',modelVersion:model.version,
 nutshell:{headline:'Accessible counseling is a plausible health investment. The local treatment match matters.',body:<><strong>Our central analyst estimate is $4.21M per better life (10 QALYs).</strong> We model a hypothetical fifteen-contact depression course—not a verified RAMS CBT program. RAMS describes predominantly psychodynamic training, so the external CBT result is a heavily qualified calibration. <a href="https://ai.rhyslindmark.com/donate/api/sf-rams-model">Inspect the model →</a></>,whyItMayWork:'Culturally and linguistically responsive counseling can help people with depression who would otherwise lack effective care.',whyWeAreCautious:'Local modality, patient mix, existing treatment and marginal funding differ from the reference trial.',recommendationBlocker:'No current depression-course quote or verified additional treatment capacity.'},
 summary:[{label:'CENTRAL ESTIMATE',value:'$4.21M',detail:'per 10 incremental QALYs; conditional local transfer'},{label:'POSITIVE SCENARIOS',value:'$359K–$160M',detail:'Not a RAMS confidence interval; null/harm possible'},{label:'COURSE ALLOWANCE',value:'$3,000',detail:'Assumed fifteen contacts plus intake/support'},{label:'FUNDING ROOM',value:'Unverified',detail:'Reimbursement and existing care may replace donations'}],
 programSection:{body:'RAMS Adult/Older Adult Outpatient provides counseling, case management, psychiatric services and other support, emphasizing underserved linguistic and cultural communities. Its training materials describe psychodynamic approaches. This report isolates a hypothetical depression-counseling course within that service, not all outpatient clients.',steps:[{title:'Identify the treatment subgroup',detail:'A depression-focused course needs an actual diagnosis, severity and current-care definition. Do not extrapolate the reference to psychosis, bipolar disorder or every clinic client.'},{title:'Price an offered course',detail:'Fifteen contacts is our planning dose, not a verified standardized RAMS protocol. Include intake, supervision, coordination and noncompletion effort.'},{title:'Measure added health',detail:'Compare with realistic existing counseling and medication access; treatment received anyway is not caused by the gift.'}],boundary:'The mixed adult public contract also includes Broderick residential and API collaborative services. Dividing it by outpatient clients would not estimate marginal course cost.'},
 model:{headline:'Central scenario: $4.21M per 10 QALYs.',body:'The external trial contributes .057 cumulative one-year QALYs per offered course. We retain 25% as a local calibration and assume 50% funding additionality. Both fractions and the $3,000 cost are judgment calls, not measured RAMS inputs.',equation:{label:'DOLLARS PER BETTER LIFE',expression:'10 × $3,000 ÷ (0.057 × 25% × 50%)',result:'$4,210,526 per 10 QALYs'},inputs:model.judgments.map(j=>({key:j.key,label:j.label,confidence:j.key==='referenceQalys'?'External randomized endpoint; not local efficacy':'Analyst assumption',best:String(central[j.key as keyof typeof central]),range:scenarios.map(s=>String(s[j.key as keyof s])).join(' / '),basis:j.basis})),inputColumnLabel:'Favorable / central / unfavorable inputs',giftHeading:'Illustrative $100,000: 33.3 gross course-equivalents before additionality; 0.2375 additional QALYs',sensitivity:scenarios.map(s=>({case:s.name,headline:money.format(s.result.costPerTenQalys!)+' per 10 QALYs',detail:s.result.additionalQalys.toPrecision(3)+' QALYs per $100,000; actual capacity unverified'})),uncertaintyBoundary:model.nullBoundary,fundingBoundary:'Funding additionality addresses genuinely added treatment versus reimbursement/replacement. The separate transfer fraction addresses modality, subgroup and counterfactual differences; neither is a measured percentage of a RAMS gift.'},
 comparisonBridge:{headline:'An integrated QALY estimate is not a utility score or a session effect.',body:'CoBalT used one-year EQ-5D area under the curve and imputed missing data. Its offered-treatment estimate already includes nonattendance. Multiplying by another year or routine completion rate would count those adjustments twice.',equation:{label:'ADDITIONAL QALYS PER OFFERED COURSE',expression:'0.057 × 25% × 50%',result:'0.007125 QALYs'},inputs:[],sensitivity:[],boundary:'The 25% transfer assumption is not a finding that psychodynamic therapy is one-quarter as effective as CBT. Longer psychoanalytic studies are triangulation, not benefits to divide by session count.'},
 evidence:[{key:'local',design:'Local service and training descriptions',population:'Mixed-age and mixed-diagnosis outpatient care',result:'Counseling delivery and psychodynamic training verified; depression-specific dose and cost are not.',transfer:'This is not a claim that RAMS delivers the CoBalT manualized CBT intervention.'},{key:'cobalt',design:'External randomized adjunct-CBT trial',population:'469 UK adults with antidepressant-resistant depression',result:'Imputed incremental .057 one-year QALYs, 95% CI .015–.099; complete joint cost/QALY data for 78%.',transfer:'Different modality and care context; exclusions and UK utility tariffs limit transfer. Imputation assumptions matter.'},{key:'tads',design:'External psychoanalytic economic trial',population:'Treatment-resistant depression; much longer therapy',result:'Approximately sixty sessions and CORE-6D valuation over a much longer follow-up.',transfer:'Supports investigating psychodynamic care, but cannot supply a per-session coefficient for this course; uncertainty includes null.'}],
 reservations:['The local modality and course are not the reference intervention.','Public reimbursement and existing psychotherapy may leave little marginal room.','Cost and transfer fractions are subjective.','Missing trial data and local subgroup selection can change the result.'],excludedBenefits:model.excluded,sources:model.sources};
export default function RamsReport(){return <CharityResearchReport content={content}/>;}
