import type{Metadata}from'next';import CharityResearchReport,{type CharityReportContent}from'@/components/CharityResearchReport';import model from'@/data/san-francisco/united-playaz-cea-v1.json';import{youthMortalityModel}from'@/lib/youth-mortality-model.mjs';
export const metadata:Metadata={title:'United Playaz | Market for Impact',description:'An explicit high-risk mentorship mortality hypothesis, not gun counts converted to lives.'};
const scenarios=model.scenarios.map(s=>({...s,result:youthMortalityModel(s)}));const central=scenarios[1];const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2});
const content:CharityReportContent={organization:model.organization,program:model.program,eyebrow:'CHARITY RESEARCH · SAN FRANCISCO · EXPLORATORY',published:'7 September 2026',modelVersion:model.version,
nutshell:{headline:'Violence prevention could matter greatly. Reaching people at genuinely high risk is decisive.',body:<><strong>Our central analyst estimate is $26.7M per better life (10 QALYs).</strong> This is a hypothetical intensive mentorship/crisis-response place, not a measured United Playaz mortality effect or a valuation of gun buybacks. Current evidence does not support a sub-$100K health claim.</>,whyItMayWork:'Trusted, sustained support may interrupt dangerous conflicts and connect young people to safer alternatives.',whyWeAreCautious:'Local contacts do not establish intensive dose, fatal-risk reduction or current additional capacity.',recommendationBlocker:'No verified marginal place quote, risk profile or local causal mortality estimate.'},
summary:[{label:'CENTRAL ESTIMATE',value:'$26.7M',detail:'per 10 QALYs; explicit mortality hypothesis'},{label:'POSITIVE SCENARIOS',value:'$333K–$4B',detail:'Not a confidence interval; null/harm possible'},{label:'PLACE ALLOWANCE',value:'$10,000',detail:'Annual planning proxy, not a quote'},{label:'FUNDING ROOM',value:'Unverified',detail:'Joint delivery and restricted allocation unresolved'}],
programSection:{body:'United Playaz and TLCBD describe a Tenderloin youth safe-space pilot operating three days weekly, with 57 early contacts reported in May 2026. We model a separately defined intensive year for high-risk youth; a visit or contact is not that place.',steps:[{title:'Specify risk without inventing it',detail:'Use an ethically collected subgroup risk estimate, not neighborhood stereotypes, arrest counts or the city average.'},{title:'Define effective engagement',detail:'Document what staff deliver across a year. A safe space is not automatically the paid-work/CBT package in external trials.'},{title:'Measure causal safety',detail:'Separate fatal victimization, nonfatal injury and arrests. Compare with realistic alternative services and avoid crediting every neighborhood trend.'}],boundary:'This report excludes gun-buyback activity. Collected weapons are not deaths prevented.'},
model:{headline:'Central scenario: $26.7M per 10 QALYs.',body:'The relative risk reduction is explicitly conditional on effective engagement. The engagement factor is therefore applied once. None of the assumed local coefficients is a transferred READI intention-to-treat estimate.',equation:{label:'DOLLARS PER BETTER LIFE',expression:'10 × $10,000 ÷ (.005 × .10 × .75 × .5 × 20)',result:'$26,666,667 per 10 QALYs'},inputs:model.judgments.map(j=>({key:j.key,label:j.label,confidence:'Analyst assumption; not measured locally',best:String(central[j.key as keyof typeof central]),range:scenarios.map(s=>String(s[j.key as keyof s])).join(' / '),basis:j.basis})),inputColumnLabel:'Favorable / central / unfavorable inputs',giftHeading:'Illustrative $100,000: 0.0375 additional QALYs; actual capacity unverified',sensitivity:scenarios.map(s=>({case:s.name,headline:money.format(s.result.costPerTenQalys!)+' per 10 QALYs',detail:s.result.additionalQalys.toPrecision(3)+' QALYs per $100,000'})),uncertaintyBoundary:model.nullBoundary,fundingBoundary:'A secondary launch budget divided by intended participants is only a planning calibration. It does not identify what the next gift buys, which entity receives it or whether startup and recurring costs differ.'},
comparisonBridge:{headline:'What would it take to beat $100K per better life?',body:model.threshold,equation:{label:'REQUIRED NET ANNUAL DEATHS PREVENTED PER PLACE',expression:'10 × $10,000 ÷ ($100,000 ×20 QALYs/death)',result:'More than 0.05 deaths per place-year'},inputs:[],sensitivity:[],boundary:'This is a threshold calculation, not a plausible local effect estimate. Nonfatal and broader benefits may matter but are not invented to reach the target.'},
evidence:[{key:'local',design:'Partner service report',population:'Tenderloin youth safe-space contacts',result:'Confirms local delivery and early reach, not causal violence reduction.',transfer:'Do not divide annual costs by contacts as though all received intensive support.'},{key:'readi',design:'External randomized paid-work/CBT program',population:'High-risk Chicago men; 20-month outcome window',result:'Full-sample homicide ITT around −.004, SE .0061, p=.516; mortality evidence is uncertain.',transfer:'Different dose and population. Pooled shooting/homicide outcomes and arrests are not mortality coefficients; ITT already incorporates uptake.'}],
reservations:['The assumed risk subgroup and treatment dose are not verified locally.','A rare fatal outcome requires credible comparison data.','Null and harm are possible despite a plausible theory.','Health-only results do not measure all youth-development value.'],excludedBenefits:model.excluded,sources:model.sources};export default function UnitedPlayazReport(){return <CharityResearchReport content={content}/>;}
