/* eslint-disable @next/next/no-html-link-for-pages -- Native anchors preserve canonical base-path navigation. */
import type {Metadata} from 'next';
import priorities from '@/data/bay/donor-priorities.json';
import {unifiedResearch} from '@/lib/unified-research-index';
import '../../givebetter.css';
import './city-theory.css';
export const metadata:Metadata={title:'What we learned from 100 reports — GiveBetter x SF',description:'Our ten giving priorities, gift scopes and marginal-funding questions.'};
export default function CityTheory(){return <div className="givebetter">
<header className="givebetter-masthead"><a href="/">Give<span>Better</span> <small>x SF</small></a></header>
<main className="donor-synthesis"><aside aria-label="Table of contents"><h2>Contents</h2><a href="#summary">Summary</a><a href="#mechanisms">What seems promising?</a><a href="#comparison">How to compare</a><a href="#priorities">Ten giving priorities</a><a href="#method">Method and limits</a></aside>
<article><h1>What we learned from 100 reports</h1><p className="donor-reviewed">Research synthesis · 11 September 2026</p>
<section id="summary"><h2>Summary</h2><p><strong>Our first places to investigate are ReCARES, Project Homeless Connect and Pacific Hearing Connection.</strong> They connect relatively specific services to identifiable health needs. Pacific Vision Foundation remains a fourth diligence lead, but its whole-gift calculation captures only first-eye health; most portfolio health is unquantified. A patient-care restriction would be a different giving decision.</p><p>These are recommendations for where to focus giving diligence, not verified prices for purchasing health outcomes. General mission support is possible today. For a larger effectiveness-driven gift, we would first confirm the extra useful care, complete cost and available capacity.</p></section>
<section id="mechanisms"><h2>What seems promising?</h2><p>Look for a specific obstacle between a person and effective care. Reused medical equipment, supported hearing care and timely dental or eye treatment can combine modest cash costs with existing clinical knowledge and donated resources. But more screening is not necessarily more completed treatment, and a donated device must fit its recipient and remain useful.</p><p>The question is what an additional gift changes. Does it remove a cash constraint, or add demand to a full clinic? What care would happen anyway, and how much sooner or better would the outcome be? Donated staff time, equipment and public services have real costs even when they do not appear on the charity’s bill.</p><p>Housing and policy are not ruled out. <a href="/charities/glide">GLIDE’s housing-prevention model</a> illustrates a potentially valuable timely intervention, but rights, income and stability are only partly captured by health estimates. Less certain QALYs do not establish less total social value. Our clinical leads are easier to investigate, not proven universally superior.</p></section>
<section id="comparison"><h2>How to compare the estimates</h2><p><strong>A better life means 10 additional QALYs.</strong> One QALY is one year of full-health equivalent; gains can be shared across people. Under $100,000 per better life requires more than 0.0001 additional QALY per donor dollar. It is a hypothesis to test, not a target for choosing assumptions.</p><p>A conditional program and an unrestricted organization gift answer different questions. GLIDE’s rental-assistance estimate is not the value of every Foundation donation. Breathe now retains the whole gift while quantifying a limited clinical subset; it does not establish a complete expected return. NEMS assumes recurring support over 20 funded years. Project Homeless Connect models the designated project, not its whole fiscal sponsor.</p><p>Whole-cost estimates can omit substantial benefits in the other direction. The new <a href="/charities/oakland-eviction-defense-center">Oakland Eviction Defense Center</a> report is distinct from San Francisco Eviction Defense Collaborative: its $21.4M housing-health estimate does not replace that organization’s research.</p><p>We keep null, harmful and unfavorable findings. The <a href="/charities/heppac">HEPPAC correction</a> shows why: removing repeated-rescue credit worsened the estimate, while a separate survival-prior revision improved it. Neither change establishes a cash-priced opportunity.</p></section>
<section id="priorities"><h2>Our ten giving priorities</h2><p>Editorial order, not numerical rank. None has a verified marginal health offer in the reviewed public evidence. The questions below are for a prospective donor; we have not contacted these organizations.</p>
{priorities.map((item,i)=>{const row=unifiedResearch.find(r=>r.href==='/charities/'+item.slug);if(!row)throw new Error('Missing donor report '+item.slug);return <section className="donor-priority" id={item.slug} key={item.slug}><h3>{i+1}. <a href={row.href}>{row.organization}</a></h3><p><strong>Gift scope:</strong> {item.scope}</p><p>{item.fundingEvidence}</p><details><summary>What to confirm before a larger gift</summary><ul>{item.donorQuestions.map(q=><li key={q}>{q}</li>)}</ul><p>Primary sources, reviewed 11 September 2026: {item.sourceURLs.map((url,n)=><span key={url}>{n>0?' · ':''}<a href={url}>Source {n+1}</a></span>)}</p></details></section>})}</section>
<section id="method"><h2>Method and limits</h2><p>The research library contains 79 Bay reports; 21 expanded-geography reports remain in the archive. This synthesis reviews their mechanisms, cost scope, additionality and funding evidence rather than sorting numbers alone. Shared clinical evidence and correlated assumptions mean 100 reports are not 100 independent experimental results.</p><p>Public donation examples, waitlists and reserves do not prove a marginal funding gap. A useful next step is a dated, accepted gift purpose with full delivery costs, available partner capacity, existing commitments and expected additional useful care. No organization is required to guarantee QALYs.</p><p>Each linked report preserves its sources, dates, model and uncertainties. The <a href="/api/sf-city-theory">original 25-program ledger</a> remains historical evidence, not the current recommendation list. <a href="/research">Read all research</a> or <a href="/archive/expanded-geography-research">browse expanded geography</a>.</p></section>
</article></main></div>;}
