/* eslint-disable @next/next/no-html-link-for-pages -- Native anchors preserve canonical Sites base-path navigation. */
import type {Metadata} from 'next';
import registry from '@/data/san-francisco/city-registry-v1.json';
import theory from '@/data/san-francisco/city-theory-v1.json';
import './city-theory.css';
export const metadata:Metadata={title:'What makes city giving cost-effective? | Market for Impact',description:'What we learned from 25 San Francisco program models, and the hypotheses we will test next.'};
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2});
const price=(slug:string)=>money.format(registry.rows.find(r=>r.slug===slug)!.centralUsdPerTenQalys);
export default function CityTheory(){return <main className="charity-report city-theory">
<header className="charity-report-topbar"><a className="brand" href="/"><span className="brand-mark">M</span><span>Market for Impact</span></a><nav aria-label="Research navigation"><a href="/research">All research</a><a href="#ledger">The common ledger</a><a href="#cohort">The 25 models</a></nav></header>
<div className="charity-report-layout"><aside className="charity-report-toc" aria-label="On this page"><span>RESEARCH SYNTHESIS</span><a href="#bottom-line">Our bottom line</a><a href="#housing">Is housing winning?</a><a href="#hypotheses">What to test next</a><a href="#threshold">The $100K test</a><a href="#ledger">Cost and causal ledger</a><a href="#cohort">Original25 models</a><small>7 September 2026<br/>{theory.version}</small></aside>
<article className="charity-report-article"><header className="charity-report-title"><p className="kicker">SAN FRANCISCO · WORKING THEORY</p><h1>What makes city giving cost-effective?</h1><p>Lessons from 25 exploratory program models—not a new charity ranking.</p></header>
<section className="charity-nutshell" id="bottom-line"><span>OUR BOTTOM LINE</span><h2>Fund the missing step, not necessarily the whole system.</h2><p>{theory.thesis}</p><p>Our current instinct is to look for severe untreated problems, short causal pathways and inexpensive ways to unlock existing capacity. That is a research priority, not yet proof of a 100× advantage. Current marginal funding room remains unverified.</p></section>
<section className="charity-section" id="housing"><p className="charity-section-number">1 · CHECK THE APPARENT WINNER</p><h2>Three housing estimates are not three independent results.</h2><p>GLIDE ({price('glide')}), Compass ({price('compass-family-services')}) and Hamilton ({price('hamilton-families')}) all divide different costs by the same assumed <strong>.072 QALY per assisted household</strong>: .144 external modeled QALYs, retained at 50%. The apparent ordering mostly reflects their cost numerators, not separate local health measurements.</p>
<div className="city-comparison"><div><strong>GLIDE</strong><span>$3,077 per case</span><p>Historical assistance cohort plus assumed delivery allowance.</p></div><div><strong>Compass</strong><span>≈$9,704 per family</span><p>Broad historical program expense divided by classified families.</p></div><div><strong>Hamilton</strong><span>$10,000 per case</span><p>Judgmental marginal assistance and delivery allowance.</p></div></div>
<p>The underlying <a href={theory.sources[0].url}>VA simulation</a> assumes stable-housing utility 1 and unstable-housing utility .434; it reports 90.7 additional stable days and .144 QALYs over two years. A rough scale check, <code>(1 − .434) × 90.7/365 ≈ .141 QALY</code>, shows how consequential that utility contrast is. This is not an exact decomposition of the simulation or a measured SF effect.</p>
<p>The <a href={theory.sources[1].url}>underlying standard-gamble valuation</a> is not the same measurement as clinical EQ-5D change. Nor is it interchangeable with the smaller judgmental utility gains in the THC, Larkin or EDC models. These bridges also lack the separate numerical funding-additionality factor used in several newer models. First clarify what the existing discount covers; do not add another arbitrary 50% or silently favor inconsistent bookkeeping.</p>
<p><strong>Our conclusion:</strong> housing prevention remains worth investigating, but the present estimates do not establish that housing is the best category. The homepage now tracks the four lowest central model estimates; that numerical order is not a judgment of evidence strength.</p></section>
<section className="charity-section" id="hypotheses"><p className="charity-section-number">2 · A FALSIFIABLE SEARCH STRATEGY</p><h2>Where we would look next—and what would change our minds.</h2><div className="city-hypotheses">{theory.researchPriorities.map((h,i)=><section key={h.title}><span>HYPOTHESIS {i+1}</span><h3>{h.title}</h3><p>{h.claim}</p><p>{h.support}</p><p><strong>Reject or weaken it if:</strong> {h.falsifier}</p></section>)}</div></section>
<section className="charity-section" id="threshold"><p className="charity-section-number">3 · GET TO BRASS TACKS</p><h2>What does under $100K per better life require?</h2><p><strong>More than .0001 additional QALY per donor dollar.</strong> This is $10,000 per QALY—not the much looser $100,000-per-QALY benchmark sometimes used in health economics.</p>
<ul><li><a href="/charities/project-homeless-connect">PHC glasses</a>, an extra-cohort comparator, models about $71K/ 10 QALYs. Holding other assumptions fixed, it misses the target if cost exceeds $140.63, utility gain falls below .02667, or effective use falls below .533 years. These are one-at-a-time thresholds, not jointly guaranteed margins.</li><li><a href="/charities/san-francisco-aids-foundation">SFAF naloxone</a>, another extra-cohort comparator, models about $56K/ 10 QALYs. It needs more than 1.1266% additional acute survival per retained reported reversal at other central inputs, versus an assumed 2%. Person-linked repeat events, alternative rescue and later survival could overturn this.</li><li><a href="/charities/glide">GLIDE</a> at $3,077 per case needs more than .3077 QALY per household—over twice the undiscounted VA model’s .144. A low price cannot be obtained just by assuming the current bridge is certain.</li><li><a href="/charities/united-playaz">United Playaz</a> at $10K per place and 20 QALYs per death needs more than .05 net deaths prevented per place-year. That exceeds its central assumed .005 annual fatal risk even before imperfect effects.</li></ul>
<p>The two extra-cohort leads are not verified funding offers. In particular, SFAF’s dose-based outreach model and HYA’s supported medication-initiation model have different doses, resource boundaries and follow-up. Their price ratio does not prove naloxone is 83× better than medication treatment.</p></section>
<section className="charity-section" id="ledger"><p className="charity-section-number">4 · MAKE COMPARISONS HONEST</p><h2>Use the same questions, not the same arbitrary discount.</h2><ol>{theory.causalLedger.map(x=><li key={x}>{x}</li>)}</ol><div className="city-comparison">{theory.costLedger.map(x=><div key={x.name}><h3>{x.name}</h3><p>{x.question}</p><p>{x.boundary}</p></div>)}</div>
<p><strong>Correlated uncertainty:</strong> shared housing simulations, employment studies, loneliness valuations and mortality assumptions mean these are not 25 independent bets. Joint recipients and repeat rescues prevent adding lifetime health gains across overlapping providers. The SFAF public-service bundle names HYA, GLIDE and HRTC, so funding and benefits also require a cross-provider reconciliation.</p>
<p><strong>Health-only is not all social value.</strong> High modeled costs for food, education, jobs, housing or legal services do not prove those organizations are bad. Most current models omit consumption, earnings, rights, dignity and neighborhood effects. We will state the boundary rather than invent QALYs for omitted benefits.</p></section>
<section className="charity-section" id="cohort"><p className="charity-section-number">5 · INSPECT THE EVIDENCE BASE</p><h2>All 25 original models, with their different accounting choices.</h2><p>{registry.scope} Prices below are positive central scenarios, not probability-weighted expected values. Open each report for ranges, null/harm and funding conditions.</p><details className="city-cohort"><summary>Open the 25-program comparison ledger</summary><div className="city-registry">{registry.rows.map(r=><section key={r.ein} data-model-ein={r.ein}><h3><a href={'/charities/'+r.slug}>{r.organization}</a></h3><strong>{money.format(r.centralUsdPerTenQalys)} / 10 QALYs</strong><dl><dt>Cost basis</dt><dd>{r.costPerspective}</dd><dt>Benefit horizon</dt><dd>{r.horizon}</dd><dt>Assumption dependency</dt><dd>{r.assumptionGroup}</dd></dl><a href={'https://github.com/Rhys-Lindmark/market-for-impact/blob/main/data/san-francisco/'+r.modelFile}>Versioned model source ↗</a></section>)}</div></details><p><a href="/api/sf-city-theory">Download the theory and computed model ledger →</a></p></section>
<section className="charity-section"><h2>What happens next?</h2><ol>{theory.nextOrder.map(x=><li key={x}>{x}</li>)}</ol><p>The final visual rebuild will choose four after the broader research, with photos and the remaining reports elsewhere. Current picks update with the modeled estimates while research continues.</p><p><a href="/research">Return to all the research →</a></p></section>
<section className="charity-section"><h2>Method and sources</h2><p>The ledger reads versioned central outputs or calculates them from model inputs, and checks original EIN coverage, model-file hashes and numerical parity. Cost-perspective and horizon labels are analyst classifications, not automatically established facts. This synthesis is a working opinion to be revised as the next cohorts are researched.</p>{theory.sources.map(s=><p key={s.url}><a href={s.url}>{s.title}</a> · {s.published}; retrieved {s.retrieved}. {s.role}.</p>)}</section>
</article></div></main>;}
