import type {Metadata} from 'next';
import CharityResearchReport,{type CharityReportContent} from '@/components/CharityResearchReport';
import data from '@/data/san-francisco/brightline-filtration-cea-v1.json';
import {filtrationModel} from '@/lib/home-environment-model.mjs';
export const metadata:Metadata={title:'Brightline Defense — SF air filtration | Market for Impact',description:'A conditional six-month adult SRO filtration model with explicit costs, utility assumptions, existing funding and null outcomes.'};
const money=(n:number|null)=>n===null?'No finite positive price':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2}).format(n);
const central=data.coreScenarios.central,r=filtrationModel(central);
const core=Object.entries(data.coreScenarios).map(([name,s])=>({name,s,result:filtrationModel(s)}));
const stress=Object.entries(data.separateStressScenarios).map(([name,s])=>({name,s,result:filtrationModel(s)}));
const labels:Record<string,string>={paidDirectDeliveryCostUsd:'Complete paid delivery cost, USD',assumedPlateauUtilityGain:'Assumed plateau utility gain',onsetMonths:'Months of linear onset',realizedExposureFraction:'Realized exposure share',fundingAdditionality:'Additional delivery share',sharedHarmQalyPerAdditionalEpisode:'Shared intervention harm, QALY',donorSpecificHarmQalyPerOffer:'Donor-specific harm, QALY'};
const content:CharityReportContent={
 organization:data.organization,program:'Proposed additional adult SRO filtration and maintenance episode',eyebrow:'SAN FRANCISCO · EXPLORATORY RESEARCH',published:'8 September 2026',modelVersion:data.modelId,donationUrl:data.donationIdentity.officialDonationUrl,
 nutshell:{headline:'Cleaner indoor air is plausible. A cheap health gain is not yet demonstrated.',
 body:<>Our provisional best estimate is <strong>{money(r.costPerTenQalys)} per better life—10 incremental QALYs</strong>. Brightline has distributed purifiers in Eastern San Francisco. We model a proposed additional six-month episode for one symptomatic adult, not the effectiveness of every Brightline activity. Its cost, health gain and additional delivery are judgment calls. <a href="/api/sf-home-environment-models">Inspect the model and sources →</a></>,
 whyItMayWork:'Reducing indoor particles may relieve respiratory illness when devices are correctly sized, used and maintained.',
 whyWeAreCautious:'Relevant trials do not establish a positive generic utility effect for symptomatic SRO adults. Particle removal and reported satisfaction are not QALYs.',
 recommendationBlocker:'We have not verified a priced additional SRO cohort, accepted gift restriction or remaining funding need.'},
 summary:[{label:'COST PER BETTER LIFE',value:money(r.costPerTenQalys),detail:'per 10 QALYs; six-month conditional donor model'},{label:'POSITIVE CORE SCENARIOS',value:'$267K–$576M',detail:'Joint judgments, not a confidence interval; null and harm remain possible'},{label:'CENTRAL UNIT BUDGET',value:'$450',detail:'One adult episode; all direct inputs assumed purchased'},{label:'FUNDING ROOM',value:'Unknown',detail:'Existing public support is not an unfunded offer'}],
 programSection:{body:'Brightline combines environmental-justice advocacy, community air monitoring and purifier distribution. Its Eastern SF case study describes 150 purifiers; a later announcement reports 200 homes. These overlapping historical reach figures are not added together. The research hypothesis here is narrower: properly sized non-ozone filtration, installation, power, filters and follow-up for one adult SRO resident with respiratory symptoms. Delivery of that exact complete course is not verified.',
 steps:[{title:'Select additional recipients',detail:'Identify symptomatic adults not already receiving suitable funded equipment or comparable assistance.'},{title:'Install and maintain',detail:'Match clean-air delivery to the room; confirm tolerated fan speed, electrical safety, replacement filters and power funding.'},{title:'Measure health, not only particles',detail:'Track repeated preference-based utility against a realistic concurrent comparator.'}],
 boundary:data.actualVersusProposed+' '+data.counterfactual},
 model:{headline:money(r.costPerTenQalys)+' per 10 QALYs',body:'The central $450 budget is $200 device + $100 consumables/electricity + $150 outreach, installation and follow-up. Every component is an unquoted allowance. A judgmental 0.01 utility gain rises linearly over six months: 0.25 integrated years. Assuming half the delivery is additional gives 0.00125 incremental QALY. No positive utility coefficient is measured for this local program.',
 equation:{label:'DOLLARS PER 10 INCREMENTAL QALYS',expression:'10 × $450 ÷ [0.5 × (0.01 × 0.25 − 0) − 0]',result:money(r.costPerTenQalys)},inputColumnLabel:'Central assumption',
 inputs:Object.entries(labels).map(([key,label])=>({key,label,confidence:'Analyst judgment',best:String(central[key as keyof typeof central]),range:core.filter(x=>x.name!=='null').map(x=>String(x.s[key as keyof typeof x.s])).join(' / '),basis:data.namedInputs[key as keyof typeof data.namedInputs].meaning})),
 giftHeading:'Joint six-month scenarios—not available donation packages',
 sensitivity:core.map(x=>({case:x.name,headline:money(x.result.costPerTenQalys),detail:x.result.netQalys+' incremental QALY per offer; '+x.s.calendarMonths+' months'})),
 uncertaintyBoundary:'Zero utility gain or pure replacement can give no positive benefit. Shared harms are reduced only under identical replacement; donor-specific disruption is subtracted even when no extra beneficial service is delivered.',
 fundingBoundary:'The regional Air District allocated $4M for filtration, not $4M to Brightline. Brightline was named in a separate community-capacity grant selection with up to $300K per organization over three years; its exact executed filtration budget, spending and remaining balance are unverified. Neither number is room for more funding. Donated inputs could lower cash cost but remain resources; participant time and wider societal costs are excluded.'},
 comparisonBridge:{headline:'Longer persistence is a separate stress test—not the headline',body:'The $89K result requires the favorable $150 budget and 0.03 utility gain, then an extra six months at full effect with no additional delivery cost. That persistence is unverified and excluded from the core range and ranking.',
 equation:{label:'SEPARATE TWELVE-MONTH STRESS',expression:'10 × $150 ÷ (0.75 × 0.03 × 0.75 years)',result:money(stress[0].result.costPerTenQalys)},inputs:[],
 sensitivity:stress.map(x=>({case:x.name,headline:money(x.result.costPerTenQalys),detail:x.result.netQalys+' incremental QALY; not a core ranking input'})),boundary:'At central health assumptions, a complete episode would need to cost under $12.50 to beat $100K per 10 QALYs. We have not found that offer.'},
 evidence:[{key:'CLEAN AIR',design:'Randomized active versus sham filtration trial',population:'116 former smokers with moderate/severe COPD; two units for six months',result:'Primary SGRQ difference −1.55 (95% CI −5.75 to 2.65): no established improvement. A secondary exacerbation outcome favored filtration.',transfer:'SGRQ is disease-specific, not a generic utility coefficient; the population and device dose differ from this SRO proposal.'},{key:'AIRWEIGHS',design:'Randomized child asthma filtration trial',population:'164 children randomized; 12-week modified intention-to-treat analysis',result:'No overall symptom-day benefit was established. ASUI is preference-based but disease-specific, not a measured adult-SRO QALY gain.',transfer:'We retain this contrary evidence rather than extrapolating from particle reduction alone.'},{key:'Local delivery',design:'Provider case study and announcements',population:'Eastern SF households and SRO outreach',result:'Historical distribution is documented; reported symptom improvements are uncontrolled.',transfer:'Reach proves activity, not causal efficacy, current available places or donor additionality.'}],
 reservations:[...data.acceptanceGates,'The positive utility assumptions are speculative. A null or negative effect could reverse this provisional opinion.','General donation recipient Brightline Defense, EIN33-1131608, is linked through the official donation-provider account. This is not verification of a restricted offer or current legal standing.'],excludedBenefits:data.nonAdditivityAndExclusions,
 sources:data.sources.map(s=>({publisher:('publisher' in s?s.publisher:undefined)??'Primary research publisher',title:s.id,url:s.url,published:('date' in s?s.date:undefined)??('publication' in s?s.publication:undefined)??'Not stated',retrieved:('retrieved' in s?s.retrieved:undefined)??'2026-09-08 research audit',sourceType:s.access})),
};
export default function Page(){return <CharityResearchReport content={content}/>;}
