import LongFormResearchReport from '@/components/LongFormResearchReport';
import {markdown,version} from '@/lib/spur-calibrated-report.mjs';
import ledger from '@/data/san-francisco/spur-v2-sources.json';
import receipts from '@/docs/geography-discovery/spur-legacy-recalibration-2026-10-03.receipts.json';
export const metadata={title:'SPUR | GiveBetter x SF',description:'Housing, useful transit, cleaner homes and signed household resources.'};
const sources=[...new Set(ledger.map(s=>s.url))].filter(url=>!receipts.sources.some(s=>s.url===url)).map(url=>{
 const entries=ledger.filter(s=>s.url===url),s=entries[0];
 return {title:s.title,url,publisher:s.publisher,published:[...new Set(entries.flatMap(e=>'published' in e?[String(e.published)]:[]))].join('; ')||'Not recorded',retrieved:[...new Set(entries.map(e=>e.retrieved))].join('; '),limit:entries.map(e=>'access' in e?String(e.access):'').filter(Boolean).join(' ')};
}).concat(receipts.sources.map(s=>({title:s.url.includes('Form_990')?'SPUR original Form 990: '+s.url.match(/SPUR_(\d{4})/)?.[1]:s.url.includes('annual-reports')?'SPUR current annual report':s.url.includes('250700')?'San Francisco rezoning economic impact analysis':s.url.includes('sfplanning')?'Adopted Family Zoning plan':s.url.includes('mtc.ca.gov')?'Existing Bay Area transit loan agreement':s.url.includes('upjohn')?'Housing supply working-paper abstract':s.url.includes('21821543')?'Housing affordability and mental health: longitudinal abstract':s.url.includes('34144434')?'Rental assistance and distress: study abstract':s.url.includes('permitting')?'Permitting Progress': 'SPUR financial disclosure index',url:s.url,publisher:s.url.includes('spur.org')?'SPUR':'Original agency or research source',published:'Period described in report',retrieved:'2026-10-03',limit:s.url.includes('Form_990')?'Selected original financial passages via browser fallback; no full-return audit or original-byte verification claimed.':s.url.includes('250700')?'Pages 18–21, pre-final-amendment forecast.':s.url.includes('europepmc')||s.url.includes('upjohn')?'Indexed original abstract only.':'Selected disclosure or baseline passages only.'})));
export default function Page(){return <LongFormResearchReport organization="SPUR" program="Housing, transportation, environmental health and civic systems" markdown={markdown} sources={sources} donationUrl="https://www.spur.org/join-renew-give/donate" modelVersion={version} modelUrl="/api/spur-v2-model" minutes={22} modelLabel="GPT-6 Astra Light" calibrationDate="2026-10-03" sectionTitles={{'1-what-does-the-organization-actually-do':'1. What do they do?','2-what-does-the-spending-record-establish':'Spending breakdown','3-delivery-and-monitoring-what-is-known-and-what-remains-missing':'2. Monitoring and information sharing','4-causal-evidence-and-transfer':'Clinical evidence and policy transfer','5-whole-gift-economics-and-finite-model':'4. What do you get for your dollar?','6-additional-funding-and-realistic-alternatives':'5. Funding and previous grants','7-qualitative-assessment-and-strongest-disconfirmation':'3. Qualitative assessment'}}/>;}
