import type {Metadata} from 'next';
import CharityResearchReport,{type CharityReportContent} from '@/components/CharityResearchReport';
import data from '@/data/international/amf-cea-v1.json';
import {amfModel} from '@/lib/amf-model.mjs';
export const metadata:Metadata={title:'Against Malaria Foundation — GiveBetter research',description:'A conditional public-net-gift model: global health benefits, explicit uncertainty and no credited Bay Area benefit.'};
const central=data.scenarios.find(s=>s.id==='central')!;
const result=amfModel(central);
const money=(n:number|null)=>n===null?'No positive-health ratio':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const inputKeys=['price','extra','people','childShare','mortality','rrr','transport','delay','additionality','horizon','annualSurvival','utility','persistentFraction','sharedHarm','independentHarm'] as const;
const labels:Record<string,string>={price:'Donor cash per net',extra:'Other associated resources per net',people:'People per net-equivalent',childShare:'Population share aged 6–59 months',mortality:'Annual all-cause mortality per eligible child-year',rrr:'Relative mortality reduction',transport:'Effect retained in new context',delay:'Campaign delay in years',additionality:'Combined funding and output additionality',horizon:'Post-event survival horizon in years',annualSurvival:'Subsequent annual survival',utility:'Health-state utility',persistentFraction:'Persistent survival-difference fraction',sharedHarm:'Shared harm per additional net, QALYs',independentHarm:'Independent harm per purchased net, QALYs'};
const sourceTitles=['Ghana cluster-randomized mortality trial','Public gifts and non-net costs','Global accounts, year ended June 2025','Immediate funding gap','Charity registrations','August 2026 DRC grant announcement','Research behind the DRC grant','Modern Tanzania net-type trial','Twenty-two-year survival cohort','Ghana follow-up: primary indexed abstract','Institutional survival-cohort record'];
const content:CharityReportContent={
 organization:data.organization,eyebrow:'International research',program:'Ordinary public giving for malaria nets',published:'8 September 2026',modelVersion:data.modelId,
 nutshell:{headline:money(result.globalUsdPer10Qaly)+' per better life globally: promising, but not a precise forecast.',
 body:<>Our central estimate is <strong>{money(result.globalUsdPer10Qaly)} per 10 global QALYs</strong> ({money(result.globalUsdPerQaly)} per QALY). Adding an illustrative allowance for co-funded delivery gives {money(result.grossAssociatedUsdPer10Qaly)} per 10 QALYs in gross associated resources—not a net societal cost estimate. We credit no direct Bay Area benefit; indirect local effects are unmeasured. <a href="/api/amf-model">Inspect every input, formula, source and scenario</a>.</>,
 whyItMayWork:'A focused organization supplies an intervention with randomized child-survival evidence and an identified funding pipeline. Ordinary public gifts buy nets across campaigns chosen by AMF.',
 whyWeAreCautious:'The next campaign mix, baseline mortality, displacement, net durability and long-run survival are not measured by this model. Most transfer and lifetime inputs are analyst judgments. The .015 annual child-mortality prior may be high against contemporary national benchmarks; it is not demonstrably conservative.',
 recommendationBlocker:'Confirm current campaign allocation, costs, co-funding and additionality. A provider-reported funding gap does not guarantee that the next gift causes the modeled benefit.'},
 summary:[{label:'Global health',value:money(result.globalUsdPer10Qaly),detail:'per 10 incremental QALYs, central donor-cash scenario'},{label:'Bay Area health',value:'0% credited',detail:'Direct benefit is overseas; unknown indirect local effects receive no credit. There is no finite positive Bay cost/QALY ratio.'}],
 programSection:{body:'AMF finances insecticide-treated nets and works with distribution and monitoring partners. Its ordinary public-gift policy directs donations to net purchases; specified other donors and partners cover non-net costs.',
 steps:[{title:'Campaign selection and distribution',detail:'AMF selects eligible campaigns and partners. Household registration, logistics and net distribution are necessary complements, not free resources.'},{title:'Protection and follow-up',detail:'Nets reduce exposure to malaria vectors. Presence, use and condition are monitored, but those observations alone do not establish the marginal mortality effect of a new donation.'}],
 boundary:data.scope+' This is not an all-expense institutional grant or a GiveWell pooled-fund gift. No bespoke country restriction is assumed.'},
 model:{headline:money(result.globalUsdPer10Qaly)+' per 10 global QALYs',
 body:'For 1,000 purchased net-equivalents, the central $3,000 donor budget produces 3.086 modeled incremental QALYs. A historical community-trial mortality effect is transported to a hypothetical marginal campaign. This is a linear planning model, not a transmission simulation or a calibrated AMF campaign average.',
 equation:{label:'Net incremental health',expression:'Eligible child-years × usual-care all-cause mortality × relative reduction × context transfer × additionality × discounted protection × discounted survival/utility − harms',result:'3.086 global QALYs per 1,000 nets; $3,000 ÷ 3.086 × 10 = $9,720'},
 inputs:[...inputKeys.map(key=>({key,label:labels[key],best:String(central[key]),range:String(Math.min(...data.scenarios.map(s=>s[key])))+'–'+String(Math.max(...data.scenarios.map(s=>s[key]))),confidence:key==='rrr'?'Historical trial anchor; transfer uncertain':'Explicit analyst planning assumption',basis:key==='mortality'?data.judgments.mortality:key==='childShare'?'Not a measured AMF campaign-mix demographic share.':key==='price'||key==='extra'?data.judgments.cost:key==='additionality'?data.judgments.additionality:['horizon','annualSurvival','utility','persistentFraction'].includes(key)?data.judgments.survival:'See the versioned model for units, provenance and joint scenarios.'})),{key:'coverage',label:'Trial-equivalent functional protection in years 1–3',best:'.8 / .5 / .2',range:'Scenario-specific; zero after year 3',confidence:'Judgment, not measured individual net usage',basis:data.judgments.coverage}],
 giftHeading:'An ordinary public net-purchase gift',
 sensitivity:data.scenarios.map(s=>{const r=amfModel(s);return {case:s.id,headline:money(r.globalUsdPer10Qaly)+' per 10 global QALYs',detail:r.globalQaly.toPrecision(5)+' net QALYs per 1,000 nets; gross associated-package price '+money(r.grossAssociatedUsdPer10Qaly)+'.'};}),
 uncertaintyBoundary:'These are joint assumptions, not confidence intervals or probability-weighted expectations. The three-year survival-postponement scenario is $55,575/10 global QALYs in donor cash. Null and harm cases retain no positive ratio. No additional morbidity, income, education or community multiplier is credited.',
 fundingBoundary:'AMF displayed an immediate $70.67M gap on 8 September 2026: $128.38M available against $199.06M approved potential use. Rounded figures do not reconcile exactly. The $276M DRC grant announced in August is already-funded baseline, not output of a fresh public gift. This is dated provider pipeline evidence, not a verified individual donation offer.'},
 evidence:[{key:'ghana',design:'Cluster-randomized trial, 1993–95',population:'Children aged 6–59 months in northern Ghana',result:'Binka et al. found all-cause mortality RR .83 (95% CI .69–1.00). Follow-up through 2000 found no indication of increased later mortality.',transfer:'The historical .17 relative reduction anchors the model. Modern mortality, campaign composition and .5 transfer remain judgments; do not multiply all-cause deaths by a malaria fraction again.'},{key:'survival',design:'Prospective observational cohort',population:'Tanzanian children followed for 22 years',result:'Early net use was associated with survival into adulthood; observational design and incomplete follow-up limit causal interpretation.',transfer:'This supports persistence plausibility, not the assumed 40-year horizon, .99 annual survival, .85 utility or .8 persistence. Those are inspectable priors.'},{key:'modern',design:'Randomized comparison of net types',population:'Modern Tanzania malaria-control setting',result:'Chlorfenapyr nets improved malaria outcomes relative to standard pyrethroid nets; other comparisons were less favorable.',transfer:'Resistance and product choice matter. Infection outcomes do not directly identify mortality or QALYs, and are not added to the historical trial effect.'}],
 reservations:[data.judgments.mortality,data.judgments.survival,data.judgments.resourcePerspective,'The favorable $361/10Q scenario is not our central estimate or a verified bargain. No scenario was tuned to pass the $100,000 target.','A US donor or legal registration does not make beneficiaries Bay Area residents. Local indirect impacts remain unknown.'],
 excludedBenefits:['Nonfatal malaria, adult and pregnancy health, income and education effects are not credited.','The model does not import GiveWell moral weights or count the already-funded DRC grant again.','No automatic additional community-protection multiplier beyond the historical community trial.'],
 sources:data.evidence.primarySourceUrls.map((url,i)=>({publisher:new URL(url).hostname,title:sourceTitles[i],url,published:i===0?'April 1996':i===2?'Year ended June 2025':i===5?'24 August 2026':i===6?'August 2026':i===7||i===8||i===10?'2022':i===9?'2002':'Undated, live provider page',retrieved:'8 September 2026',sourceType:'Primary source; access and interpretation limits documented in model'}))
};
export default function Page(){return <CharityResearchReport content={content}/>;}
