import type { Metadata } from 'next';
import CharityResearchReport, { type CharityReportContent } from '@/components/CharityResearchReport';
import model from '@/data/san-francisco/larkin-cash-housing-cea-v1.json';
import { cashHousingModel } from '@/lib/cash-housing-model.mjs';
export const metadata: Metadata = {title:'Larkin Street Youth Services | Market for Impact',description:'A transparent cash-plus housing scenario, with explicit health assumptions and a cost-effectiveness threshold.'};
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2});
const scenarios=model.scenarios.map(s=>({...s,result:cashHousingModel(s)}));
const central=scenarios[1];
const content:CharityReportContent={
 organization:model.organization,program:model.program,eyebrow:'CHARITY RESEARCH · SAN FRANCISCO · EXPLORATORY',published:'7 September 2026',modelVersion:model.version,
 nutshell:{headline:'Cash can help young people find stability. This dose is not a cheap health-only bet.',body:<><strong>Our central scenario is {money.format(central.result.costPerTenQalys!)} per better life (10 QALYs).</strong> It models a new program at the completed Trust Youth Initiative’s cash dose—not a measured Larkin effect or an available donation offer. The housing and health inputs are explicit best guesses. <a href="https://ai.rhyslindmark.com/givebetter/api/sf-larkin-model">Inspect the full model →</a></>,whyItMayWork:'Flexible cash plus optional support can pay deposits, bridge income gaps and let young people choose housing arrangements.',whyWeAreCautious:'The available results do not identify additional housed person-years or a causal health-utility gain. Housing is not automatically attributable to cash.',recommendationBlocker:'No priced additional replication or verified funding gap. AIM may differ from the completed pilot.'},
 summary:[{label:'OUR BEST GUESS',value:'$40.4M',detail:'per 10 incremental QALYs; conditional health-only scenario'},{label:'POSITIVE SCENARIOS',value:'$6.07M–$2.42B',detail:'Judgmental stress tests, not confidence bounds'},{label:'CASH PLUS SUPPORT',value:'$50,500',detail:'Published $40,500 dose + assumed $10,000 support'},{label:'FUNDING ROOM',value:'Unverified',detail:'Completed pilot; successor economics unknown'}],
 programSection:{body:'SF Trust Youth Initiative combined two years of unconditional payments with optional supportive services for young adults experiencing homelessness. Larkin announced completion in December 2025 and named Accelerating Independent Missions (AIM) as the next initiative. We do not assume AIM has the same dose, costs or effects.',steps:[{title:'Finance a genuinely new cohort',detail:'Separate new cash and staff capacity from replacement of existing funding.'},{title:'Offer flexible cash and support',detail:'The historic dose was $1,500 monthly for 24 months plus $4,500.'},{title:'Compare housing trajectories',detail:'Count additional stable-housing days against ordinary services, then apply a transparent health-only bridge.'}],boundary:'TYI, AIM, federal RHY prevention and residential housing are separate until a program/funding crosswalk proves otherwise. Do not divide Larkin’s whole budget by every young person served.'},
 model:{headline:'Our best estimate: $40.4M per 10 QALYs.',body:'We assume six additional months housed over 30 months, a 0.05 health-utility improvement during that time, and 50% donor-funded additional capacity. These are deliberately exposed analyst judgments, not trial results. The $10,000 support assumption covers 96 loaded staff hours at $100 plus $400 administration.',equation:{label:'DOLLARS PER BETTER LIFE',expression:'10 × $50,500 ÷ (0.5 years × 0.05 × 50%)',result:'$40,400,000 per 10 QALYs'},inputs:model.judgments.map(j=>({key:j.key,label:j.label,confidence:'Published cash dose; otherwise explicit judgment',best:String(central[j.key as keyof typeof central]),range:scenarios.map(s=>String(s[j.key as keyof typeof s])).join(' / '),basis:j.basis})),inputColumnLabel:'Favorable / central / unfavorable inputs',giftHeading:'Illustrative $100,000: 1.98 packages and 0.0248 additional QALYs',sensitivity:scenarios.map(s=>({case:s.name,headline:money.format(s.result.costPerTenQalys!)+' per 10 QALYs',detail:s.result.additionalQalys.toPrecision(3)+' QALYs per $100,000; not available funding room'})),uncertaintyBoundary:model.nullBoundary,fundingBoundary:'FY2025 audited government-contract revenue was $22.58M and total expenses $36.78M. These whole-organization accruals neither price TYI nor establish an unfunded tranche. We do not net presumed public savings out of donor cost.'},
 comparisonBridge:{headline:'Could this beat $100,000 per 10 QALYs?',body:'The cash alone would require more than 4.05 additional QALYs per participant. In a deliberately extreme 30-month health-only ceiling of one extra QALY per year, that is impossible: even the cash-only price is $162,000 per 10 QALYs. This ceiling assumes utility gains between zero and one and no mortality or later effects; it is not a universal limit on cash benefits.',equation:{label:'CASH-ONLY THRESHOLD',expression:'10 × $40,500 ÷ 2.5 QALYs',result:'$162,000 even at this extreme short-horizon ceiling'},inputs:[],sensitivity:[],boundary:'Longer durable benefits, mortality effects, lower-cost interventions or benefits outside health could change the conclusion. They need separate evidence, not silently extended follow-up.'},
 evidence:[{key:'sf-design',design:'Primary SF study design',population:'85 young adults; 45 TYI and 40 usual-care enrollment groups',result:'Three initially randomized invitees were reassigned after nonresponse.',transfer:'Enrollment-group comparisons are not clean intention-to-treat estimates. Severe untreated mental-health/substance-use conditions were excluded.'},{key:'sf-results',design:'Conference abstract and organization summary',population:'SF pilot participants',result:'The abstract uses paired baseline-to-month-18 tests; the organization reports 86% permanently housed at 24 months.',transfer:'Neither result supplies the cumulative causal housing-days used by this model. The 86% denominator/comparator is not supplied in the announcement.'},{key:'nyc',design:'External cash-plus analogue',population:'NYC young adults; different dose and housing system',result:'Published enrollment-group trajectories suggest benefit but include reassignment and differential response.',transfer:'A difference in any homelessness during one month is not the same as additional housed years. Not used as a numeric effect input.'}],
 reservations:['Housing-to-health utility is subjective and correlated with other housing models.','Causal housing duration and missing follow-ups remain unresolved.','Whole-organization financial pressure is not program-specific funding room.','AIM and other prevention programs could have different economics.'],excludedBenefits:model.excluded,sources:model.sources,
};
export default function LarkinReport(){return <CharityResearchReport content={content}/>;}
