import type {Metadata} from 'next';
import CharityResearchReport,{type CharityReportContent} from '@/components/CharityResearchReport';
import model from '@/data/san-francisco/selfhelp-falls-cea-v1.json';
import {fallsCourseModel} from '@/lib/falls-course-model.mjs';
export const metadata:Metadata={title:'Self-Help for the Elderly | Market for Impact',description:'A proposed therapeutic tai chi course with explicit QALY and implementation assumptions.'};
const scenarios=model.scenarios.map(s=>({...s,result:fallsCourseModel(s)}));const central=scenarios[1];
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2});
const content:CharityReportContent={
organization:model.organization,program:model.program,eyebrow:'CHARITY RESEARCH · SAN FRANCISCO · EXPLORATORY',published:'7 September 2026',modelVersion:model.version,
nutshell:{headline:'Targeted fall prevention deserves a closer look. The course and risk group matter.',body:<><strong>Our central independent bridge is $2.4M per better life (10 QALYs).</strong> A different reading of the published QALY result yields $600K with the same local assumptions. We would investigate a trial-matched course, not assume the existing six-week service has that effect.</>,whyItMayWork:'Small-group balance training may improve health at a relatively low cost when it reaches older adults at high fall risk.',whyWeAreCautious:'The proposed curriculum is not verified locally, and the external paper has a consequential utility/QALY ambiguity.',recommendationBlocker:'No current quote, trial-matched implementation commitment or verified added places.'},
summary:[{label:'CENTRAL ESTIMATE',value:'$2.4M',detail:'per 10 QALYs; independent endpoint bridge'},{label:'ALTERNATIVE UNIT READING',value:'$600K',detail:'Using .04 directly as integrated QALYs'},{label:'COURSE ALLOWANCE',value:'$600',detail:'Analyst planning cost; not a provider quote'},{label:'FUNDING ROOM',value:'Unverified',detail:'Expired CalFresh grant is not current capacity'}],
programSection:{body:'Self-Help describes a six-week Sun-style Tai Chi for Arthritis and Fall Prevention course. We model a prospective, separately specified 24-week therapeutic TJQMBB course for high-fall-risk older adults. These are not interchangeable programs.',steps:[{title:'Recruit the intended risk group',detail:'The reference involved older people with prior falls or impaired mobility. General social exercise participants may have less scope for benefit.'},{title:'Specify delivery',detail:'Two classes weekly for 24 weeks, qualified instruction and safety screening require an actual local delivery plan.'},{title:'Measure incremental health',detail:'Compare with realistic existing exercise and care. The trial comparison was stretching, not no activity.'}],boundary:'The January–March 2026 CalFresh closeout grant covered mixed activities and wind-down. Its consumer targets are not completed six-month courses or a current funding gap.'},
model:{headline:'Central scenario: $2.4M per 10 QALYs.',body:'We make an independent endpoint-utility hypothesis and assume gradual onset over a rounded six months. This is not a reproduction or correction of the published economic analysis.',equation:{label:'DOLLARS PER BETTER LIFE',expression:'10 × $600 ÷ (.04 × .5 years × .5 onset × .5 transfer × .5 additionality)',result:'$2,400,000 per 10 QALYs'},inputs:model.judgments.map(j=>({key:j.key,label:j.label,confidence:'Explicit analyst calibration',best:String(central[j.key as keyof typeof central]),range:scenarios.map(s=>String(s[j.key as keyof s])).join(' / '),basis:j.basis})),inputColumnLabel:'Favorable / central / unfavorable inputs',giftHeading:'Illustrative $100,000: 0.417 additional QALYs; actual capacity unverified',sensitivity:scenarios.map(s=>({case:s.name,headline:money.format(s.result.costPerTenQalys!)+' per 10 QALYs',detail:s.result.additionalQalys.toPrecision(3)+' QALYs per $100,000'})),uncertaintyBoundary:model.nullBoundary,fundingBoundary:'The 50% additionality assumption is not verified funding room. An expired contract does not establish what a gift buys now.'},
comparisonBridge:{headline:'The published units materially change the answer.',body:model.unitAmbiguity,equation:{label:'ALTERNATIVE INTEGRATED-QALY READING',expression:'10 × $600 ÷ (.04 × .5 × .5)',result:'$600,000 per 10 QALYs'},inputs:[],sensitivity:[],boundary:'Methods describe duration weighting and the table calls .04 QALYs; prose describes utility scores. Additional duration and onset are our hypothesis, not a demonstrated necessary adjustment. Neither reading establishes a sub-$100K opportunity.'},
evidence:[{key:'trial',design:'External randomized active-comparator trial',population:'670 older adults at high fall risk in Oregon',result:'Therapeutic tai ji quan reduced falls compared with stretching.',transfer:'Different curriculum from the current local Sun-style course; no separate injury benefits added to utility.'},{key:'economic',design:'External six-month economic evaluation',population:'Same trial',result:'Reports a .04 difference with inconsistent utility/QALY terminology.',transfer:'Payer cost-effectiveness is not marginal philanthropic cost-effectiveness.'},{key:'null',design:'Separate Sun-style randomized trial',population:'Relatively well older adults',result:'Did not establish a fall reduction.',transfer:'Risk selection and curriculum fidelity can erase expected benefit.'}],
reservations:['A trial-matched course is prospective, not verified current delivery.','Unit interpretation changes the central estimate fourfold.','Costs, local transfer and additionality are assumptions.','Null or adverse effects remain possible.'],excludedBenefits:model.excluded,sources:model.sources};
export default function SelfHelpReport(){return <CharityResearchReport content={content}/>;}
