import {givewellBenchmarks} from '@/lib/givewell-reconciliation.mjs';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
export default function GiveWellComparison({slug}:{slug:string}){
 const b=givewellBenchmarks.find(x=>x.slug===slug)!;
 return <section className="report-reading-column"><h2>Why does this differ from GiveWell?</h2>
 <p><a href="https://www.givewell.org/impact-estimates">GiveWell’s August 2026 summary</a> estimates {money(b.givewellCostPerLife)} per life saved for this program, based on its 2022–2024 funding opportunities. This is a modeled mortality outcome—not a QALY estimate or a quote for the next unrestricted gift.</p>
 <p>Our original v1 scenario implied {money(b.independentCostPerLife)} per early death prevented, before converting survival into QALYs. It credited about {b.finiteQalyPerLife.toFixed(2)} discounted QALYs per prevented death, using a finite 40-year survival curve, background mortality, .85 utility, .8 persistence and 3% discounting. Those survival inputs are judgments, not measured life tables.</p>
 <p>Using GiveWell’s mortality estimate with that same event-time survival assumption gives <strong>{money(b.sameSurvivalConversion.usdPer10Qalys)} per 10 QALYs</strong>, before a new gift’s implementation delay. Using an illustrative 50 QALYs per life instead gives {money(b.illustrative50Conversion.usdPerQaly)} per QALY, or {money(b.illustrative50Conversion.usdPer10Qalys)} per 10 QALYs. Fifty undiscounted years are not automatically fifty discounted QALYs.</p>
 <p>GiveWell’s aggregate lives-saved estimate may include different ages and timing from our early-child-death model. Applying the same QALYs per life here is a diagnostic assumption, not an age-matched survival calculation.</p>
 <h3>What we learned</h3>
 <p>There is no factor-of-ten arithmetic error. Our original model compounds conservative transfer and funding assumptions that were not calibrated to GiveWell’s analysis. Its result should be read as a constructed scenario, not proof that GiveWell overstates impact. We should not apply our full adjustment ladder again to GiveWell’s already-adjusted mortality estimate.</p>
 {slug==='new-incentives'?<p>New Incentives has an especially important denominator difference: our cost is per eligible catchment infant, while GiveWell’s technical example uses enrolled infants. Coverage gains cannot be multiplied across those denominators without an enrollment conversion. A separate 70% funding penalty also accounts for much of our lower modeled impact. These differences require matched state and funding assumptions, not an automatic replacement with a national average.</p>:<p>For malaria nets, trial transfer, effective protection over time and funding replacement can overlap if each is used as a generic uncertainty penalty. They must represent different causal losses. Campaign geography and partner delivery costs also differ from a simple net-purchase budget.</p>}
 <p>GiveWell evaluates specific funding opportunities. Displacing its funding may move impact to another program rather than eliminate it. Conversely, a historical average does not establish the effect of every direct gift. The current v2 report replaces that mortality ladder with the historical benchmark and age-aware timing assumptions. We retain the original model for auditability. None of these global calculations establishes SF benefit.</p>
 <p><a href="/api/givewell-reconciliation">Inspect the comparison inputs and formulas</a>.</p>
 </section>;
}
