import {remedyLocalScenarios} from '@/lib/local-impact-data';
import {spilloverScenario} from '@/lib/local-impact-model.mjs';
const money=(n:number|null)=>n===null?'No finite positive ratio':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:1}).format(n);
export default function LocalImpactNote({slug,directQ,gift}:{slug:string,directQ:number,gift:number}){
 return <section className="report-reading-column"><h2>How much might this help San Francisco?</h2>{slug==='remedy-alliance'?<>
 <p>Our rough local estimate is <strong>{money(remedyLocalScenarios[0].sfUsdPer10Q)} per 10 SF-resident QALYs</strong>, or {money(remedyLocalScenarios[0].bayUsdPer10Q)} per 10 Bay Area QALYs. We assign 0.5% of marginal national health to SF and 2% to the Bay, including SF. These are broad analyst judgments—not measured shipment or beneficiary shares. The full national gift remains the cost.</p>
 <p>California’s <a href="https://www.dhcs.ca.gov/individuals/naloxone-distribution-project/products-available-through-the-ndp-2/">public program confirms a Remedy supply pathway</a>. Local overdose burden makes some benefit plausible, but substantial existing provision and unknown marginal destinations make the share highly uncertain. There is no second local funding discount. Shared clinical benefits and harms are assumed to have the same regional proportions.</p>
 <details><summary>Local-share sensitivities</summary><ul>{remedyLocalScenarios.map(s=><li key={s.name}>{s.name}: SF {money(s.sfUsdPer10Q)}; Bay {money(s.bayUsdPer10Q)} per 10 QALYs.</li>)}</ul><p>These hold national clinical assumptions fixed. Null or harmful national effects do not become positive through geography. Independent harms need their own location assumptions; they are not automatically distributed by benefit shares.</p></details>
 </>:<>
 <p>Direct benefits accrue overseas. Preventing infections could indirectly protect SF residents through travel and reduced importation, but no evidence currently calibrates this charity’s local effect. We leave the SF comparison price unquantified rather than show its global price as a local bargain.</p>
 <details><summary>Tiny local-spillover math</summary><p>If additional SF health were one millionth of the modeled direct overseas health, the same gift would cost <strong>{money(spilloverScenario(directQ,gift,1e-6,1e-6).sfUsdPer10Q)} per 10 SF QALYs</strong>. This is an illustrative coefficient, not an estimated share or an evidence-based bound.</p><ul>{[0,1e-8,1e-6,1e-4].map(e=><li key={e}>Additional SF QALYs per direct overseas QALY: {e}. Local cost: {money(spilloverScenario(directQ,gift,e,e).sfUsdPer10Q)} per 10 QALYs.</li>)}</ul><p>These scenarios carry forward the direct model’s finite schedule only as a simplifying diagnostic. They do not model an infinite transmission or innovation tail. Overseas health is not reassigned to SF; SF is nested within Bay, so the two cannot be added.</p></details>
 <p>Relevant mechanisms: <a href="https://www.cdc.gov/mmwr/volumes/73/wr/mm7314a1.htm">measles importation</a> and <a href="https://www.cdc.gov/advanced-molecular-detection/php/success-stories/malaria-parasite-2023.html">rare local malaria transmission</a>. Neither source estimates AMF or New Incentives’ effect on SF.</p>
 </>}</section>;
}
