import {test,expect} from '@playwright/test';
test('CCA conditional health-and-income report, API and list agree',async({page,request})=>{
 await page.route('https://market-for-impact.rhyslindmark.chatgpt.site/_next/**',async route=>{const u=new URL(route.request().url());await route.fulfill({response:await request.get(u.pathname+u.search)});});
 await page.goto('/california/charities/coalition-for-clean-air');
 await expect(page.getByRole('heading',{level:1,name:'Coalition for Clean Air',exact:true})).toBeVisible();
 await expect(page.locator('.report-research-effort summary')).toContainText('GPT-6.1 Sol');
 await expect(page.locator('#cost')).toContainText('$10.2 million');
 await expect(page.locator('#cost')).toContainText('$3.34 million');
 await expect(page.locator('#cost')).toContainText('household');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 const response=await request.get('/api/geography-reports/california/coalition-for-clean-air');expect(response.ok()).toBe(true);
 const report=await response.json(),central=report.model.scenarios.find((s:any)=>s.id==='central');
 expect(central.editionQalys).toBeCloseTo(.009792597827729082,12);
 expect(central.incomePathways).toEqual([]);
 expect(report.model.scenarios.find((s:any)=>s.id==='baselineAliveProductivity').incomePathways.length).toBeGreaterThan(0);
 await page.goto('/california/all');
 const row=page.locator('[data-research-table] tbody tr').filter({hasText:'Coalition for Clean Air'});
 await expect(row.locator('td').nth(0)).toContainText('$10.2M');await expect(row.locator('td').nth(1)).toContainText('$2.0M');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
