import {test,expect} from '@playwright/test';
test('Code Tenderloin keeps finite health and net income ledgers synchronized',async({page,request})=>{
 await page.goto('/charities/code-tenderloin');
 await expect(page.getByRole('heading',{name:'Code Tenderloin',exact:true})).toBeVisible();
 await expect(page.locator('article')).toContainText('$1.72 million');
 await expect(page.locator('.report-research-effort summary')).toContainText('Research time:');
 await expect(page.locator('.report-research-effort summary')).toContainText('GPT-6.1 Sol');
 const donate=page.getByRole('link',{name:'Donate',exact:true});await expect(donate).toHaveCount(2);
 for(const link of await donate.all())await expect(link).toHaveAttribute('href','https://www.codetenderloin.org/donate');
 expect(await page.locator('article table').count()).toBe(0);
 await expect(page.locator('article')).toContainText('Historical sponsored-program spending');
 await expect(page.locator('article')).toContainText('$3,841,331');
 await expect(page.locator('article')).toContainText('alternative pay');
 const response=await request.get('/api/code-tenderloin-model');expect(response.ok()).toBeTruthy();
 const data=await response.json();expect(data.historical.evaluated).toHaveLength(15);
 expect(data.evaluated.bayUsdPerBetterLife).toBeCloseTo(1716763.7050172826,5);
 expect(data.evaluated.sfUsdPerBetterLife).toBeCloseTo(1869364.923241041,5);
 expect(data.evaluated.incomeEquivalentYears).toBeGreaterThan(0);
 expect(data.evaluated.schedule).toHaveLength(10);
 expect(data.diagnostics.some((x:{combinedYears:number;sfUsdPerBetterLife:number|null})=>x.combinedYears<0&&x.sfUsdPerBetterLife===null)).toBeTruthy();
 await page.goto('/research');await expect(page.locator('[data-research-slug="code-tenderloin"]')).toContainText('Code Tenderloin');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});
