import {test,expect} from '@playwright/test';
test('hearing report retains finite model and precise recipient warning',async({page})=>{
 await page.goto('/charities/hearing-and-speech-center');
 await expect(page.getByRole('heading',{level:1,name:'Hearing and Speech Center of Northern California',exact:true})).toBeVisible();
 await expect(page.locator('#summary')).toContainText('does not establish misconduct or closure');
 await expect(page.locator('.report-research-effort summary')).toContainText('GPT-6.1 Sol');
 await expect(page.locator('.report-research-effort summary')).toContainText('GPT-5.6 Sol Medium');
 await page.locator('.report-research-effort summary').click();
 await expect(page.locator('.report-research-effort')).toContainText('estimated before tracking');
 await expect(page.locator('.report-reading-column article')).toContainText('No finite positive price');
 await expect(page.locator('.report-heading .report-donate')).toHaveAttribute('href', /^(https:\/\/|#funding)/);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await expect(page.getByRole('heading',{name:'Health and income effects',exact:true})).toBeVisible();
 const response=await page.request.get('/api/sf-hearing-model');
 const j=await response.json();expect(j.evaluated[0].costPerTenQalys).toBe(1250000);
 expect(j.model_id).toBe('hsc-health-income-calibration-2026-10-01');
 expect(j.evaluated[0].healthYears).toBe(.012);
 expect(j.evaluated[0].incomeEquivalentYears).toBe(0);
 expect(j.incomeDiagnostics.earnings.costPerTenQalys).toBeCloseTo(1201162.5676101055,6);
 expect(j.incomeDiagnostics.earningsLoss.incomeEquivalentYears).toBeLessThan(0);
 expect(j.incomeDiagnostics.noFunding.costPerTenQalys).toBeNull();
 expect(j.financialReview.averageAnnualExpenses).toBe(2460673);
 expect(j.evaluated.at(-1).status).toBe('harm');
});
