import {test,expect} from '@playwright/test';
test('hearing report retains finite model and precise recipient warning',async({page})=>{
 await page.goto('/charities/hearing-and-speech-center');
 await expect(page.getByRole('heading',{level:1,name:'Hearing and Speech Center of Northern California',exact:true})).toBeVisible();
 await expect(page.locator('#summary')).toContainText('does not establish misconduct or closure');
 await expect(page.locator('.report-research-effort summary')).toContainText('GPT-6.1 Sol');
 await expect(page.locator('.report-research-effort summary')).toContainText('GPT-5.6 Sol Medium');
 await page.locator('.report-research-effort summary').click();
 await expect(page.locator('.report-research-effort')).toContainText('estimated before tracking');
 await expect(page.locator('.report-reading-column article')).toContainText('No finite positive price');
 await expect(page.locator('.report-heading .report-donate')).toHaveAttribute('href', /^(https:\/\/|#funding)/);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await expect(page.getByRole('heading',{name:'Health and income effects',exact:true})).toBeVisible();
 const response=await page.request.get('/api/sf-hearing-model');
 const j=await response.json();expect(j.evaluated[0].costPerTenQalys).toBeCloseTo(1507782.8809835732,6);
 expect(j.model_id).toBe('hsc-independent-health-income-current-2026-10-01');
 expect(j.evaluated[0].healthYears).toBeCloseTo(.009715095408402447,12);
 expect(j.evaluated[0].incomeEquivalentYears).toBeGreaterThan(0);
 expect(j.incomeDiagnostics['clinical and income coexist'].costPerTenQalys).toBeCloseTo(1360194.2070968456,6);
 expect(j.incomeDiagnostics['negative income'].incomeEquivalentYears).toBeLessThan(0);
 expect(j.incomeDiagnostics['no additional funding'].costPerTenQalys).toBeNull();
 expect(j.financialReview.averageAnnualExpenses).toBe(2460673);
 expect(j.evaluated.at(-1).status).toBe('harm');
 await page.goto('/san-francisco/all');
 await expect(page.locator('[data-research-slug="hearing-and-speech-center"]')).toHaveAttribute('data-cost-per-ten-qalys',String(j.evaluated[0].bayCostPerTenQalys));
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
