import {test,expect} from '@playwright/test';
import {EXPECTED_RESEARCH_COUNT} from './research-contract';
test('HEPPAC separates hypothetical SF attribution from total gift impact',async({page})=>{
 test.setTimeout(60000);
 await page.goto('/san-francisco/all');
 await expect(page.locator('[data-research-slug]')).toHaveCount(EXPECTED_RESEARCH_COUNT);
 const row=page.locator('[data-research-slug="heppac"]');
 await expect(row).toHaveAttribute('data-estimate-geography','Bay Area');
 await row.locator('a').first().click();
 await expect(page.getByRole('heading',{level:1})).toContainText('HEPPAC');
 await expect(page.locator('#research-summary')).toContainText('$15.3M');
 await expect(page.locator('#research-summary')).toContainText('$7.99M');
 const response=await page.request.get('/api/heppac-model');expect(response.ok()).toBe(true);
 const data=await response.json(), w=data.evaluated.conditionalOrdinaryGiftWeighted;
 expect(data.verifiedMarginalFundingOffer).toBeNull();
 expect(data.measuredWholeGiftExpectedValue).toBeNull();
 expect(w.bayDonorPer10HealthyYearEquivalent).toBeCloseTo(7988917.899119561,6);
 expect(data.central.bayDonorPer10HealthyYearEquivalent).toBeCloseTo(15262220.77152425,6);
 expect(data.evaluated.healthOnly.conditionalOrdinaryGiftWeighted.bayDonorPer10Qaly).toBeCloseTo(8133469.099019436,6);
 expect(data.evaluated.healthOnly.originalEventLinearBayPrice).toBeCloseTo(11112456.578235215,6);
 expect(w.sfDonorPer10HealthyYearEquivalent).toBeGreaterThan(w.bayDonorPer10HealthyYearEquivalent);
 expect(w.bayDonorPer10HealthyYearEquivalent).toBeGreaterThan(w.donorPer10HealthyYearEquivalent);
 await page.goto('/san-francisco/all');await expect(page.locator('[data-research-slug="heppac"]')).toHaveAttribute('data-cost-per-ten-qalys',String(data.central.bayDonorPer10HealthyYearEquivalent));await page.goto('/charities/heppac');
 const links=page.locator('a.report-donate');await expect(links).toHaveCount(1);
 for(const link of await links.all())await expect(link).toHaveAttribute('href','https://heppac.org/donate/');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await expect(page.locator('nav.report-contents [data-toc-primary]')).toHaveCount(7);
 await expect(page.locator('.report-research-effort summary')).toContainText('GPT-6.1 Sol');
 await expect(page.locator('.report-research-effort summary')).not.toContainText('unrecorded');
 await expect(page.locator('#spending-breakdown-and-financial-appendix')).toContainText('$3,524,429');
});
