import {test,expect} from '@playwright/test';
test('Changent report/list/API distinguish current combined finite and historical lifetime prices',async({page})=>{
 test.setTimeout(60000);
 await page.goto('/archive/expanded-geography-research');
 const row=page.locator('[data-research-slug="nurse-family-partnership"]');
 await expect(row).toHaveAttribute('data-cost-per-ten-qalys',String(12252706.21073911));
 await row.locator('a').first().click();
 await expect(page.getByRole('heading',{level:1})).toHaveText('Changent / Nurse-Family Partnership');
 await expect(page.locator('#research-summary')).toContainText('$12.25M');
 await expect(page.locator('#research-summary')).toContainText('$10.24M');
 await expect(page.locator('#what-do-you-get-for-your-dollar')).toContainText('$12.52M');
 const response=await page.request.get('/api/nfp-model');expect(response.ok()).toBe(true);
 const data=await response.json();
 expect(data.evaluated.weighted.conditionalDonorCostPer10Equivalent).toBeCloseTo(12252706.210739108,6);
 expect(data.evaluated.inputs.fy2024Surplus).toBe(-2489261);
 expect(data.evaluated.geography.totalBay).toBeNull();expect(data.evaluated.ordinaryWholeGiftExpectedValue).toBeNull();
 expect(data.lifetimeDiagnostic.weighted.donorCostPer10Qaly).toBeCloseTo(10239968.547563247,6);
 await expect(page.locator('a.report-donate')).toHaveCount(1);
 await expect(page.locator('a.report-donate')).toHaveAttribute('href','https://changent.org/get-involved/support-our-work/');
 await expect(page.locator('nav.report-contents [data-toc-primary]')).toHaveCount(7);
 await expect(page.locator('.report-research-effort summary')).toContainText('GPT-6.1 Sol');
 await expect(page.locator('.report-research-effort summary')).toContainText('GPT-5.6 Sol');
 await expect(page.locator('.report-research-effort summary')).not.toContainText('unrecorded');
 await expect(page.locator('#spending-breakdown-and-financial-appendix')).toContainText('$33,975,561');
 await expect(page.locator('[data-expense-appendix]')).toHaveAttribute('data-average-expenses',String(33975561.333333336));
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
