import type { Metadata } from 'next';
import CharityResearchReport, { type CharityReportContent } from '@/components/CharityResearchReport';
import model from '@/data/san-francisco/openhouse-companionship-cea-v1.json';
import { supportiveHealthModel } from '@/lib/supportive-health-model.mjs';
export const metadata: Metadata = { title: 'Openhouse | Market for Impact', description: 'A transparent health-only model for additional Friendly Visitor companionship.' };
const money = new Intl.NumberFormat('en-US', {style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2});
const scenarios = model.scenarios.map(s => ({...s,result:supportiveHealthModel(s)}));
const central = scenarios[1];
const content: CharityReportContent = {
 organization:model.organization,program:model.program,eyebrow:'CHARITY RESEARCH · SAN FRANCISCO · EXPLORATORY',published:'7 September 2026',modelVersion:model.version,
 nutshell:{headline:'Companionship can matter. The size of its added health benefit remains uncertain.',body:<><strong>Our central analyst estimate is $5.33M per better life (10 QALYs).</strong> This is a proposed six-month Friendly Visitor match, not Openhouse housing or a measured local QALY result. <a href="https://ai.rhyslindmark.com/givebetter/api/sf-openhouse-model">Inspect the model →</a></>,whyItMayWork:'Regular, affirming contact may reduce loneliness and depressive symptoms for isolated LGBTQ older adults.',whyWeAreCautious:'Local evaluation is uncontrolled with incomplete follow-up; external befriending trials do not supply a clean local QALY coefficient.',recommendationBlocker:'No priced marginal match plan or verified additional volunteer/staff capacity.'},
 summary:[{label:'CENTRAL ESTIMATE',value:'$5.33M',detail:'per 10 incremental QALYs; subjective health bridge'},{label:'POSITIVE SCENARIOS',value:'$593K–$320M',detail:'Not confidence bounds; null and harm possible'},{label:'COST PER MATCH',value:'$1,000',detail:'Assumed six-month cash budget, not a quote'},{label:'FUNDING ROOM',value:'Unverified',detail:'Existing grants are not an available donor tranche'}],
 programSection:{body:'Friendly Visitor matches connect LGBTQ older adults with volunteers for regular companionship and practical connection. An organization-authored November 2025 description reports 80 current pairs and weekly or biweekly contact, following assessment. This model asks what an additional six-month match might achieve.',steps:[{title:'Assess and match',detail:'Identify an isolated person who wants the service and a suitable, supported volunteer.'},{title:'Sustain useful contact',detail:'Staff screening, training, supervision and transport support are real delivery inputs; an assigned match is not automatically a sustained relationship.'},{title:'Measure incremental health',detail:'Compare with usual contact and support, tracking retention and preference-based health utility rather than treating visits as health outcomes.'}],boundary:'Exclude housing construction, rent assistance and the wider intergenerational program. A mixed-program grant divided by 80 current pairs is not a marginal-match cost.'},
 model:{headline:'Central scenario: $5.33M per 10 QALYs.',body:'We assume a $1,000 cash cost, a .01 health-utility improvement for half a year when effectively engaged, 75% sustained engagement and 50% funding additionality. These are judgment calls with explicit uncertainty, not measured Openhouse coefficients.',equation:{label:'DOLLARS PER BETTER LIFE',expression:'10 × $1,000 ÷ (0.01 × 0.5 years × 75% × 50%)',result:'$5,333,333 per 10 QALYs'},inputs:model.judgments.map(j=>({key:j.key,label:j.label,confidence:'Analyst assumption',best:String(central[j.key as keyof typeof central]),range:scenarios.map(s=>String(s[j.key as keyof s])).join(' / '),basis:j.basis})),inputColumnLabel:'Favorable / central / unfavorable inputs',giftHeading:'Illustrative $100,000: 100 proposed matches and 0.1875 additional QALYs',sensitivity:scenarios.map(s=>({case:s.name,headline:money.format(s.result.costPerTenQalys!)+' per 10 QALYs',detail:s.result.additionalQalys.toPrecision(3)+' QALYs per $100,000; capacity unverified'})),uncertaintyBoundary:model.nullBoundary,fundingBoundary:'The city intergenerational grant combines staff, operating costs and a partner subcontract across a wider service scope. It is context, not a cost-per-match denominator. Volunteer time is outside this donor-cash numerator but constrains delivery.'},
 comparisonBridge:{headline:'Loneliness, satisfaction and QALYs are different measures.',body:'The .01 utility gain is a subjective health assumption. External randomized befriending findings make the mechanism plausible but do not numerically calibrate this value. The local quality-of-life scale is a satisfaction measure, not preference-based utility.',equation:{label:'ADDED HEALTH PER PROPOSED MATCH',expression:'0.01 × 0.5 years × 75% × 50%',result:'0.001875 QALYs'},inputs:[],sensitivity:[],boundary:'No conversion of satisfaction points, no volunteer QALYs and no assumed mortality or dementia prevention. Engagement and funding additionality address different losses.'},
 evidence:[{key:'local',design:'Local uncontrolled evaluation, 2017–2021',population:'Openhouse participants across several services',result:'Friendly Visitor follow-up was small and incomplete: 22 baseline respondents and 16 matched six-month respondents.',transfer:'Selection, missing follow-up and the absence of a comparison group prevent a causal health-utility estimate.'},{key:'befriendas',design:'External randomized trial',population:'345 Australian aged-care residents',result:'Reported lower depression and loneliness at 16 weeks, without significant anxiety or social-support differences.',transfer:'Different setting and population; symptom-scale effects are not QALYs and are not inserted as utility.'},{key:'pliny',design:'External feasibility trial',population:'Community-dwelling older adults offered telephone friendship groups',result:'Volunteer recruitment and retention problems stopped delivery early; participant recruitment targets were met, but planned economic evaluation was incomplete.',transfer:'Volunteer capacity and sustained service delivery can defeat a plausible theory of change.'}],
 reservations:['The health-utility bridge is subjective.','The marginal match budget and capacity need a current quote.','Incomplete follow-up may select the participants who benefit most.','Replacing existing funds or offering unwanted contact can erase or reverse benefits.'],excludedBenefits:model.excluded,sources:model.sources
};
export default function OpenhouseReport(){return <CharityResearchReport content={content}/>;}
