/* eslint-disable @next/next/no-html-link-for-pages -- Native anchors preserve the canonical base path. */
import accounts from '@/data/san-francisco/large-bay-v1.json';
import programs from '@/data/san-francisco/large-bay-programs-v1.json';
import ymca from '@/data/san-francisco/ymca-dpp-cea-v1.json';
import sf from '@/data/san-francisco/sf-marin-food-bank-qaly-bridge-audit-v1.json';
import {foodAccessModel,benefitAccessModel,foodPharmacyModel,diabetesPreventionModel} from '@/lib/large-bay-impact-model.mjs';
import './large-bay.css';
export const metadata={title:'Five large Bay nonprofits: cost-effectiveness | Market for Impact'};
const money=(x:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(x);
const rows=[
 ...programs.map(p=>{const calc=p.calculator==='food'?foodAccessModel:p.calculator==='benefits'?benefitAccessModel:foodPharmacyModel;return{slug:p.slug,name:p.organization,program:p.program,geography:p.geography,price:calc(p.scenarios[1]).costPerTenQalys as number,low:calc(p.scenarios[0]).costPerTenQalys as number,high:calc(p.scenarios[2]).costPerTenQalys as number};}),
 {slug:'ymca-greater-sf',name:ymca.organization,program:ymca.program,geography:ymca.geography,price:diabetesPreventionModel(ymca.scenarios[1]).costPerTenQalys as number,low:diabetesPreventionModel(ymca.scenarios[0]).costPerTenQalys as number,high:diabetesPreventionModel(ymca.scenarios[2]).costPerTenQalys as number},
 {slug:'sf-marin-food-bank',name:'San Francisco–Marin Food Bank',program:'Community Markets',geography:'San Francisco and Marin',price:sf.modeledBridge.bestCostPerTenQalysUsd,low:Math.min(...sf.modeledBridge.sensitivity.map(s=>s.costPerTenQalysUsd)),high:Math.max(...sf.modeledBridge.sensitivity.map(s=>s.costPerTenQalysUsd))},
].sort((a,b)=>a.price-b.price);
export default function LargeBay(){return <main className="large-bay">
<nav aria-label="Research navigation"><a href="/">Market for Impact</a><a href="/research">All research →</a></nav>
<header><p className="kicker">BAY AREA · PROGRAM COST-EFFECTIVENESS</p><h1>Are these five large Bay nonprofits cost-effective?</h1><p>Specific programs, not entire organizations. Lower dollars per 10 incremental QALYs is better.</p></header>
<section className="bay-caveat"><h2>None clears $100,000 in the central estimate.</h2><p>YMCA diabetes prevention comes closest at about $2.10 million per better life. Its favorable scenario falls below $100,000, but requires low costs and persistent effects together; it is not the central finding or a verified offer.</p><p>These uncertain health-only models omit some economic and dignity benefits. All five lack a verified marginal donation tranche. Bay-only programs remain separate from SF-city recommendations. Positive ranges are joint assumptions, not confidence intervals; null or harm remains possible.</p></section>
<div className="bay-list">{rows.map((r,i)=><article key={r.slug} data-bay-org={r.slug} data-central-price={r.price}><div><p className="kicker">{i+1} · {r.geography}</p><h2>{r.name}</h2><h3>{r.program}</h3><p>No leading health-only opportunity under the central model. The report explains the mechanism, contrary evidence and assumptions that could change this conclusion.</p><a href={'/charities/'+r.slug}>Read the research report →</a></div><aside><strong className="bay-price">{money(r.price)}</strong><span>per better life · 10 incremental QALYs</span><p>Positive scenarios: {money(r.low)}–{money(r.high)}.</p><p>Very low confidence · funding room unverified</p></aside></article>)}</div>
<section className="bay-method"><h2>Size and accounting context</h2><p>{accounts.selection} This is not an exhaustive largest-five ranking. Goodwill and other large organizations require separate program reviews.</p><p>FY2025 whole-entity expenses are not cash budgets, funding gaps or SF-only expenditure. Donated food is substantial; transfers between food banks can be counted twice, so do not sum these totals.</p>{accounts.rows.map(r=><details key={r.id}><summary>{r.name}: {money(r.expenses)} audited expenses</summary><p>{r.foodExpense===null?'No comparable donated-food expense identified.':money(r.foodExpense)+' in donated food/supplies; remaining expenses still include noncash items.'} <a href={r.url}>Primary audit · printed pages {r.pages} ↗</a></p></details>)}</section>
</main>;}
