/* eslint-disable @next/next/no-html-link-for-pages -- Native anchors preserve canonical Sites base-path navigation. */
import type {Metadata} from 'next';
import data from '@/data/san-francisco/large-bay-v1.json';
import './large-bay.css';
export const metadata:Metadata={title:'Five large Bay Area nonprofits | Market for Impact'};
const money=(x:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(x);
export default function LargeBay(){return <main className="large-bay">
<nav aria-label="Research navigation"><a href="/">Market for Impact</a><a href="/research">All research →</a></nav>
<header><p className="kicker">BAY AREA · ORGANIZATION DISCOVERY</p><h1>Five large Bay Area nonprofits worth examining.</h1><p>Start with scale. Then ask what an extra donation actually changes.</p></header>
<section className="bay-caveat"><h2>Large is not the same as cost-effective.</h2><p>{data.selection} We selected local direct-service organizations, excluding hospitals, universities, grantmakers and national organizations.</p><p>Figures cover July 1, 2024–June 30, 2025. Four are food banks: donated food accounts for roughly 66–82% of their reported expenses. These are not cash budgets, funding gaps or dollars spent exclusively in the Bay. Do not sum the totals: food transferred between banks can be counted more than once.</p></section>
<div className="bay-list">{data.rows.map((r,i)=><article key={r.id} data-bay-org={r.id}><div><p className="kicker">{i+1} · {r.geography}</p><h2>{r.name}</h2><p>{r.program}</p><p><strong>What we would investigate:</strong> {r.next}</p></div><aside><strong className="bay-price">{money(r.expenses)}</strong><span>FY2025 audited expenses</span><p>{r.foodExpense===null?'No comparable donated-food expense identified; not a cash-only total.':money(r.foodExpense)+' in donated food/supplies distributed ('+(100*r.foodExpense/r.expenses).toFixed(1)+'% of expenses). The remainder still includes noncash items.'}</p><a href={r.url}>Read the audit · printed pp. {r.pages} ↗</a></aside></article>)}</div>
<section><h2>Our next research bet</h2><p>The interesting question is not “which has the biggest budget?” It is whether a small extra gift can unlock an otherwise unavailable service. We would prioritize a concrete food-benefit access or targeted food-health program, and a YMCA youth or health intervention, before estimating their additional health gains per donor dollar.</p><p>We already model a specific SF–Marin Food Bank program in <a href="/research">the research library</a>; it is not an organization-wide estimate. The other four do not yet have provider-specific cost-effectiveness models here. Any future comparison will use <strong>dollars per 10 additional QALYs</strong>, with explicit assumptions and uncertainty—not annual expenses divided by people served.</p></section>
<section className="bay-method"><h2>Selection and accounting notes</h2><p>This is a bounded shortlist with a common fiscal year, not a complete nonprofit census. <a href="https://sfgoodwill.org/wp-content/uploads/2024/06/SFGW_2022-23_AnnualReport_Final.pdf">Goodwill San Francisco Bay reported $141,713,620 in FY2023 expenses</a>, above two names here; we have not verified a newer comparable primary filing. A strict largest-five ranking would need that follow-up and a broader entity search.</p><p>Whole-entity audited expense includes noncash items and may include activity outside the Bay. SF–Marin’s audit is consolidated with End Hunger LLC. YMCA has substantial membership and government funding; volunteer labor is not automatically recognized as expense. Size and accounting ratios alone do not establish impact, donation additionality or current room for funding.</p><p>Source check: {data.retrieved}. Version: {data.version}. Links beside each organization point to its primary audited statements.</p></section>
</main>}
