import type {Metadata} from 'next';
import CharityResearchReport,{type CharityReportContent} from '@/components/CharityResearchReport';
import model from '@/data/san-francisco/lyon-earlier-care-cea-v1.json';
import {earlierCareModel} from '@/lib/earlier-care-model.mjs';
export const metadata:Metadata={title:'Lyon-Martin | Market for Impact',description:'An exploratory model of earlier adult testosterone access, with a three-month health horizon.'};
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2});
const scenarios=model.scenarios.map(s=>({...s,result:earlierCareModel(s)}));const central=scenarios[1];
const content:CharityReportContent={
 organization:model.organization,program:model.program,eyebrow:'CHARITY RESEARCH · SAN FRANCISCO · EXPLORATORY',published:'7 September 2026',modelVersion:model.version,
 nutshell:{headline:'Earlier access may help. The value of shortening the wait is the question.',body:<><strong>Our conditional best guess is $4.57M per better life (10 QALYs)</strong> for a proposed donor-funded acceleration of adult testosterone starts. This is not an estimate of all gender-affirming care, nor a judgment about whether an individual should receive treatment. <a href="https://ai.rhyslindmark.com/givebetter/api/sf-lyon-model">Inspect the model →</a></>,whyItMayWork:'Extra clinical and navigation capacity could bring forward wanted, clinically appropriate treatment.',whyWeAreCautious:'The small external trial’s utility interval includes no benefit and harm. Local waiting times and marginal costs are unknown.',recommendationBlocker:'We have not identified a priced tranche that demonstrably shortens waits rather than replacing existing financing.'},
 summary:[{label:'OUR BEST GUESS',value:'$4.57M',detail:'per 10 incremental QALYs; conditional analyst model'},{label:'POSITIVE SCENARIOS',value:'$95K–$768M',detail:'Not confidence bounds; null and harm possible'},{label:'COST PER SUPPORTED START',value:'$1,000',detail:'Assumed all-in access budget, not a clinic quote'},{label:'FUNDING ROOM',value:'Unverified',detail:'Capital expansion is not a hormone-access tranche'}],
 programSection:{body:'Lyon-Martin provides hormone prescribing, monitoring and support within a broader clinical service. This proposed slice covers clinically eligible adults seeking masculinization whose treatment would otherwise start later. It excludes minors, estrogen therapy, surgery and other clinic programs.',steps:[{title:'Identify an avoidable wait',detail:'Establish the real alternative start date, not simply whether an appointment was booked.'},{title:'Add appropriate capacity',detail:'Finance clinical and navigation time with labs, medication access and reimbursement accounted for.'},{title:'Count only the earlier health window',detail:'Credit health while care is brought forward; do not assign lifetime treatment benefit to a short delay.'}],boundary:'Clinical eligibility and treatment decisions belong to the patient and qualified clinicians. This is philanthropic program research, not medical advice.'},
 model:{headline:'Our best estimate: $4.57M per 10 QALYs.',body:'The nominal $1,000 budget is an assumption: three $250 clinical/lab/medication encounter bundles plus $250 allocated coordination, including unsuccessful engagement. We assume half the supported starts are actually accelerated and retain half the external effect for transfer.',equation:{label:'DOLLARS PER BETTER LIFE',expression:'10 × $1,000 ÷ (0.07 × 0.25 years × 50% × 50% × 50%)',result:'≈ $4.57M per 10 QALYs'},inputs:model.judgments.map(j=>({key:j.key,label:j.label,confidence:'Trial utility anchor or explicit assumption',best:String(central[j.key as keyof typeof central]),range:scenarios.map(s=>String(s[j.key as keyof typeof s])).join(' / '),basis:j.basis})),inputColumnLabel:'Favorable / central / unfavorable inputs',giftHeading:'Illustrative $100,000: 100 supported starts and 0.219 additional QALYs',sensitivity:scenarios.map(s=>({case:s.name,headline:money.format(s.result.costPerTenQalys!)+' per 10 QALYs',detail:s.result.additionalQalys.toPrecision(3)+' QALYs per $100,000; not verified funding capacity'})),uncertaintyBoundary:model.nullBoundary,fundingBoundary:'A February 2026 HRC approval schedule proposes $202,000 annually for mixed integrated care. An April DPH planning list separately shows $1,742,500 for core services. These are different funding lenses—not a current hormone budget or an unfunded balance. The capital campaign’s additional-patient goal covers multiple services.'},
 comparisonBridge:{headline:'A three-month endpoint is not three months at full benefit.',body:'The randomized study compares immediate initiation with a three-month wait. Our central onset factor assumes a linear ramp from zero to the utility difference at month three. There is no further duration multiplication or separate credit for symptom-score changes.',equation:{label:'HEALTH PER SUPPORTED START',expression:'0.07 × 0.25 × 0.5 × 0.5 × 0.5',result:'0.0021875 incremental QALYs'},inputs:[],sensitivity:[],boundary:'The favorable sub-$100K case jointly assumes $250 cost, 75% additionality, larger utility benefit and immediate full onset. It is a research possibility—not the expected price or an available opportunity.'},
 evidence:[{key:'rct',design:'Randomized secondary analysis; Australia',population:'64 adults enrolled; 62 completed, 31 per arm',result:'Baseline-adjusted EQ-5D-5L difference 0.07 at three months; reported 95% CI −0.07 to 0.21, nonsignificant.',transfer:'Open-label, short follow-up and UK utility tariff. EQ-VAS is not preference-based utility; symptom changes are not deaths prevented. Published interval and P value are retained without deriving a probability distribution.'}],
 reservations:['Local wait duration and accelerated-start count are unknown.','Cost and additionality are judgments, not observed Lyon-Martin economics.','The utility interval includes harm; positive scenarios alone do not establish effectiveness.','No long-term or mortality benefit is credited.'],excludedBenefits:model.excluded,sources:model.sources,
};
export default function LyonMartinReport(){return <CharityResearchReport content={content}/>;}
