import type { Metadata } from 'next';
import CharityResearchReport, { type CharityReportContent } from '@/components/CharityResearchReport';
import model from '@/data/san-francisco/progress-crisis-cea-v1.json';
import { supportiveHealthModel } from '@/lib/supportive-health-model.mjs';
export const metadata: Metadata = {title:'Progress Foundation | Market for Impact',description:'Crisis residential care versus hospitalization: a health-only model with a credible null.'};
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2});
const scenarios=model.scenarios.map(s=>({...s,result:supportiveHealthModel(s)}));const central=scenarios[1];
const content:CharityReportContent={
 organization:model.organization,program:model.program,eyebrow:'CHARITY RESEARCH · SAN FRANCISCO · EXPLORATORY',published:'7 September 2026',modelVersion:model.version,
 nutshell:{headline:'A less institutional crisis setting may save public money. Extra health gains are not established.',body:<><strong>Our subjective positive scenario is $391M per better life (10 QALYs).</strong> No added health benefit versus hospital care is at least as credible. This is not a finding that residential care is ineffective; it may deliver similar outcomes at lower public cost. <a href="https://ai.rhyslindmark.com/givebetter/api/sf-progress-model">Inspect the model →</a></>,whyItMayWork:'A small, supportive residential setting can provide acute stabilization outside a hospital for suitable voluntary patients.',whyWeAreCautious:'The closest randomized studies do not establish superior health outcomes. Payer savings are not automatically donor savings or QALYs.',recommendationBlocker:'No current marginal Avenues quote, verified funding gap or demonstrated health advantage over available hospital care.'},
 summary:[{label:'POSITIVE CENTRAL SCENARIO',value:'$391M',detail:'per 10 QALYs; null at least as credible'},{label:'POSITIVE STRESS CASES',value:'$69.5M–$13.0B',detail:'Not confidence bounds; harm possible'},{label:'EPISODE ALLOWANCE',value:'$15,000',detail:'Assumed current two-week budget, not quote'},{label:'FUNDING ROOM',value:'Unverified',detail:'Existing public contract and contingency must be reconciled'}],
 programSection:{body:'Avenues is a 24-hour acute diversion residence for San Francisco adults, offering an alternative to psychiatric hospitalization with an average stay of about two weeks. This comparison assumes hospital care would otherwise be available.',steps:[{title:'Assess clinical suitability',detail:'Residential care is not a substitute for hospital treatment for every crisis. Maintain transfer and safety backup.'},{title:'Provide short-term stabilization',detail:'Model one two-week episode, keeping it distinct from Dore’s urgent-care clinic and longer-term residential rehabilitation.'},{title:'Compare real alternatives',detail:'Estimate health and cost differences versus hospital treatment, not the whole improvement from crisis to recovery.'}],boundary:'Benefits of treatment itself occur in both arms. Do not count all recovery as caused by choosing residential care.'},
 model:{headline:'Positive scenario: $391M per 10 QALYs; a credible null remains.',body:'We assume $15,000 per episode, a small .02 utility advantage during fourteen days and 50% added funding capacity. This is a transparent hypothesis, not an estimated trial effect. No lasting health effect is added.',equation:{label:'DOLLARS PER BETTER LIFE',expression:'10 × $15,000 ÷ (0.02 × 14/365 years × 50%)',result:'$391,071,429 per 10 QALYs'},inputs:model.judgments.map(j=>({key:j.key,label:j.label,confidence:'Analyst assumption; external evidence does not establish benefit',best:String(central[j.key as keyof typeof central]),range:scenarios.map(s=>String(s[j.key as keyof s])).join(' / '),basis:j.basis})),inputColumnLabel:'Favorable / positive central / unfavorable inputs',giftHeading:'Illustrative $100,000: 6.67 gross episode-equivalents; 3.33 incremental after additionality',sensitivity:scenarios.map(s=>({case:s.name,headline:money.format(s.result.costPerTenQalys!)+' per 10 QALYs',detail:s.result.additionalQalys.toPrecision(3)+' QALYs per $100,000; capacity unverified'})),uncertaintyBoundary:model.nullBoundary,fundingBoundary:'The 2023 SF analysis pools four ADUs and estimated annual clients, not current marginal Avenues episodes. Public funding and expansion contingency may displace philanthropy. Government-payer hospital savings are not deducted from the donor numerator.'},
 comparisonBridge:{headline:'Similar health at lower cost is different from buying extra QALYs.',body:'With this donor-cost and hospital-comparator perspective, equivalent health yields no finite positive-benefit price. A public-payer allocation model could reach a different conclusion, but requires actual released resources and their alternative use.',equation:{label:'FOURTEEN-DAY BOUNDARY',expression:'10 × $15,000 ÷ (1.0 utility × 14/365 years)',result:'$3.91M per 10 QALYs even at full utility advantage'},inputs:[],sensitivity:[],boundary:'This model-bound sensitivity caps the utility difference at 1.0; it is not a universal utility maximum, since some valued health states are below zero. It applies only to this cost and short pathway, not all Progress Foundation services. It is not a sub-$100K lead on the modeled pathway.'},
 evidence:[{key:'local',design:'Local administrative budget and program description',population:'Four SF ADUs, with Avenues as this report’s target',result:'FY2022–23 budget $6,431,386 and 584 estimated annual clients; approximately $11,013 per estimated client.',transfer:'Old pooled budget/client ratio is not an observed episode cost, current price or marginal funding quote.'},{key:'howard',design:'Small UK randomized crisis-house pilot',population:'Voluntary female admissions; 19 assigned crisis house and 22 ward',result:'No significant adjusted health/QALY difference; incomplete EQ-5D follow-up.',transfer:'Do not treat lack of significance as equivalence. An inconsistent displayed adjusted QALY coefficient is not imported; preference-arm findings are not randomized evidence.'},{key:'fenton',design:'US randomized residential-versus-hospital evaluation',population:'Adults accepting voluntary acute care',result:'Lower government-payer episode costs, without significant symptom or community-day differences.',transfer:'Not QALYs. Non-entry and hospital transfers limit extrapolation; hospital backup remains part of delivery.'}],
 reservations:['No demonstrated added QALYs versus hospitalization.','A positive utility advantage is a subjective hypothesis.','Public funding displacement may erase donor additionality.','Safety, hospital transfers and actual marginal capacity need a current plan.'],excludedBenefits:model.excluded,sources:model.sources};
export default function ProgressReport(){return <CharityResearchReport content={content}/>;}
