import type {Metadata} from 'next';
import CharityResearchReport,{type CharityReportContent} from '@/components/CharityResearchReport';
import data from '@/data/san-francisco/rtsf-falls-cea-v1.json';
import {homeModificationModel} from '@/lib/home-environment-model.mjs';
export const metadata:Metadata={title:'Rebuilding Together SF — fall prevention | Market for Impact',description:'Conditional cost per 10 QALYs for additional home fall-hazard modifications, with conflicting trials and explicit donor funding assumptions.'};
const money=(n:number|null)=>n===null?'No finite positive price':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2}).format(n);
const core=data.scenarios.map(s=>({...s,result:homeModificationModel(s.inputs)})),central=core.find(s=>s.id==='central')!,r=central.result;
const stress=data.stressTests.map(s=>({...s,result:homeModificationModel(s.inputs)}));
const labels:Record<string,string>={conditionalDonorCashCostUsd:'Conditional donor cash, USD',directDeliveryResourceCostUsd:'Direct delivery resources, USD',participantTimeCostUsd:'Participant/caregiver time, USD',fallRateDifferencePerPersonYear:'Rounded external all-falls rate difference',clinicalTransfer:'Local clinical transfer',effectiveYears:'Effective years within the first year',expectedQalyLossPerFall:'Assumed QALYs lost per all-fall event',fundingAdditionality:'Additional delivery share',incrementalHarmQaly:'Shared intervention harm, QALY'};
const content:CharityReportContent={
 organization:data.organization.name,program:'Proposed skilled fall-hazard modification expansion',eyebrow:'SAN FRANCISCO · EXPLORATORY RESEARCH',published:'8 September 2026',modelVersion:data.id,donationUrl:'https://rebuildingtogethersf.org/get-involved/our-partners/',
 nutshell:{headline:'Practical home safety. Mixed trial results. A conditional—not ready-to-buy—health opportunity.',
 body:<>Our provisional best estimate is <strong>{money(r.costPerTenQalys)} per better life—10 incremental QALYs</strong> for an additional complete home-modification course. RTSF provides real SF repair services; we model a proposed skilled fall-prevention expansion, not its entire portfolio. The positive health estimate relies on a secondary trial result and a judgmental QALY bridge despite null primary outcomes. <a href="/api/sf-home-environment-models">Inspect the model and sources →</a></>,
 whyItMayWork:'Removing actionable hazards may prevent falls when tailored installation is paired with assessment, training and follow-up.',
 whyWeAreCautious:'A larger related trial did not show health gains. RTSF has not demonstrated the exact trial protocol or a causal local effect.',
 recommendationBlocker:'No quoted additional course or verified unfunded cohort beyond existing repair commitments.'},
 summary:[{label:'COST PER BETTER LIFE',value:money(r.costPerTenQalys),detail:'per 10 QALYs; conditional all-direct-input donor scenario'},{label:'POSITIVE CORE SCENARIOS',value:'$267K–$1.5B',detail:'Within one year; joint judgments, not confidence bounds'},{label:'CENTRAL COURSE COST',value:'$1,000',detail:'All direct inputs valued; participant time shown separately'},{label:'FUNDING ROOM',value:'Unknown',detail:'100 people is an existing funded target—not an unfunded queue'}],
 programSection:{body:'Rebuilding Together San Francisco describes home repairs, mobility and safety modifications. The proposed course evaluated here adds skilled OT-equivalent assessment, tailored installation/removal, behavior training and a six-month booster for one high-risk adult aged65+ per enrolled household. Current RTSF delivery of that exact course is unverified. The local affiliate—not national Rebuilding Together—is the organization assessed; its official giving instructions list EIN94-3107808.',
 steps:[{title:'Confirm a new eligible course',detail:'Prior falls or fear of falling plus actionable hazards; reconcile usual care, existing funding and landlord obligations.'},{title:'Assess and install',detail:'Skilled assessment and tailored modifications, with permissions, safe installation and behavior training.'},{title:'Follow up and measure',detail:'Track all enrolled households, failed visits, falls, injuries and preference-based utility through the year.'}],boundary:'One high-risk adult per household. Fixture lifespan is not health-effect duration; do not automatically add caregiver, household or mortality benefits.'},
 model:{headline:money(r.costPerTenQalys)+' per 10 QALYs',body:'The central budget is $300 skilled assessment/booster/travel/records + $400 installation + $200 materials + $100 coordination. These are planning judgments; the skilled allowance may be too lean. We take 0.8 fewer all-falls per person-year from rounded HARP rates, retain half for local transfer, assign 0.01 QALY per prevented all-fall event, and assume half the delivery is additional. This produces 0.002 incremental QALY per course. The utility mapping is not measured by either trial.',
 equation:{label:'DOLLARS PER 10 INCREMENTAL QALYS',expression:'10 × $1,000 ÷ [0.5 × (0.8 × 0.5 × 1 × 0.01 − 0)]',result:money(r.costPerTenQalys)},inputColumnLabel:'Central assumption',
 inputs:Object.entries(labels).map(([key,label])=>({key,label,confidence:key==='fallRateDifferencePerPersonYear'?'Derived secondary trial rate':'Analyst judgment',best:String(central.inputs[key as keyof typeof central.inputs]),range:core.slice(0,3).map(s=>String(s.inputs[key as keyof typeof s.inputs])).join(' / '),basis:('meaning' in data.namedInputs[key as keyof typeof data.namedInputs]?data.namedInputs[key as keyof typeof data.namedInputs].meaning:undefined)??'See derivation and source limitations; not a local measured coefficient.'})),
 giftHeading:'One-year scenarios—not verified courses available to donors',
 sensitivity:core.map(s=>({case:s.id,headline:money(s.result.costPerTenQalys),detail:s.result.netQalys+' incremental QALY; expanded resource price including time '+money(s.result.expandedResourcePrice)})),
 uncertaintyBoundary:'Null and negative outcomes remain possible. The model treats funding replacement as identical replacement of both benefits and intervention harms. It does not cover separate donor-driven disruption; that would require an additional harm term outside the funding factor.',
 fundingBoundary:'The application page describes funding to serve100 people by December31,2026—not100 unfunded or remaining places. A separate service page says Senior Home Repair intake is closed; this does not establish universal closure. Donor cash equals direct resources only under our no-subsidy assumption. Paid and donated labor remain resources; subtracting cofunding does not prove extra delivery. The expanded central price is $5.5M including $100 participant/caregiver time; this is still not a complete societal-cost model.'},
 comparisonBridge:{headline:'Persistence and harmful-outcome stresses are separate',body:'A favorable second year lowers the price to about $133K, but requires unobserved persistence with no extra maintenance cost. It is not in the core range or ranking. The OTIS-magnitude harm stress is an external illustration, not an RTSF finding.',
 equation:{label:'SEPARATE TWO-YEAR STRESS',expression:'10 × $800 ÷ (0.8 × 1 × 2 × 0.05 × 0.75)',result:'≈ $133K per 10 QALYs'},inputs:[],sensitivity:stress.map(s=>({case:s.id,headline:money(s.result.costPerTenQalys),detail:s.result.netQalys+' incremental QALY; not a core ranking input'})),boundary:'At central health assumptions, direct course cost must fall below $20 to beat $100K per 10 QALYs. No such complete offer is verified.'},
 evidence:[{key:'HARP',design:'Randomized home-hazard intervention trial',population:'310 high-risk community-dwelling older adults in St Louis;12 months',result:'Rounded all-fall rates were2.3 versus1.5 per person-year. This secondary result favored intervention; primary time-to-first-fall and HRQoL results were not significant.',transfer:'The0.8 difference is not an adjusted absolute effect or serious-injury rate. Every fall is not a fracture; the QALY mapping averages noninjurious events and truncated consequences.'},{key:'OTIS',design:'Larger randomized occupational-therapy home assessment trial with economic evaluation',population:'1,331 adults aged65+ in the UK',result:'No benefit established; the economic analysis estimated −0.0042 QALYs and £18.78 additional payer cost over12 months.',transfer:'Protocol differs from HARP but supplies important counterevidence. Net UK payer cost is not an SF delivery quote; no medical savings are credited.'},{key:'Local program',design:'Provider service, application and giving disclosures',population:'San Francisco repair recipients',result:'Actual local modifications and existing funded delivery are documented; exact trial fidelity and marginal availability are not.',transfer:'Funded targets are baseline services, not additional outcomes attributable to a new gift.'}],
 reservations:[...data.fundingRoom.constraints,'The .01 central QALY loss per all-fall event is a judgment, not a calibrated injury-mix estimate; .05 favorable is also speculative. Repeated-event overlap could inflate the result.','No evidence warrants treating donated labor as costless or automatically translating years of fixture durability into years of utility benefit.'],excludedBenefits:data.safeguards,
 sources:Object.entries(data.sources).map(([title,s])=>({publisher:title.startsWith('rtsf')||title==='recipient'?'Rebuilding Together San Francisco':title==='harp'?'JAMA Network Open':'NIHR / NCBI Bookshelf',title,url:s.url,published:s.published??'Not stated',retrieved:'2026-09-08',sourceType:s.type})),
};
export default function Page(){return <CharityResearchReport content={content}/>;}
