import type {Metadata} from 'next';
import CharityResearchReport,{type CharityReportContent} from '@/components/CharityResearchReport';
import data from '@/data/san-francisco/hac-developer-pathway-cea-v1.json';
import {hacModel,resolveHacScenario} from '@/lib/urban-policy-model.mjs';
export const metadata:Metadata={title:'Housing Action Coalition — developer assistance | Market for Impact',description:'An explicit conditional estimate of additional SF housing health from developer assistance, with costs, attribution and uncertainty.'};
const money=(n:number|null)=>n===null?'No finite positive price':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2}).format(n);
const central=data.scenarios[0], result=hacModel(central);
const input=(key:string,label:string,best:string,range:string,basis:string)=>({key,label,best,range,basis,confidence:'Judgmental'});
const content:CharityReportContent={
 organization:data.organization,program:'Developer Pathway Program: additional SF technical assistance',eyebrow:'SAN FRANCISCO · CONDITIONAL RESEARCH',published:'8 September 2026',modelVersion:data.model_id,
 nutshell:{headline:'More housing could improve health. This particular funding pathway is not yet a strong bargain.',
 body:<>Our provisional best estimate is <strong>{money(result.costPerTenQalys)} per better life—10 incremental QALYs</strong>. We model an additional advisory year for an SF housing project within an actual regional program. The project, price and causal health gains are not verified. <a href="/api/sf-urban-policy-models">Inspect the model and sources →</a></>,
 whyItMayWork:'Technical and financing advice could unblock a project whose additional homes reduce unhealthy crowding or housing insecurity.',
 whyWeAreCautious:'Completion leverage and health per net home are judgments. The $80K favorable case needs a much larger project and stronger leverage than demonstrated for this cohort.',
 recommendationBlocker:'No specific additional SF project, unfunded place, restricted offer or correct accepting entity is verified.'},
 summary:[{label:'COST PER BETTER LIFE',value:money(result.costPerTenQalys),detail:'per 10 QALYs; conditional donor budget'},{label:'POSITIVE SCENARIOS',value:'$80K–$15B',detail:'Joint stresses, not confidence bounds; null/harm possible'},{label:'ADVISORY BUDGET',value:'$15,000',detail:'Complete project-year allowance, not a provider quote'},{label:'FUNDING ROOM',value:'Unknown',detail:'Existing pilot has support; applications are closed'}],
 programSection:{body:'HAC and Onyx Equity Partners provide a year of project-readiness, financing and entitlement advice, supported by Sobrato Family Foundation. Eligibility spans the nine Bay counties and Sacramento. The 2026 cohort includes an SF-based developer, but that does not establish an SF project or completed units.',
 steps:[{title:'Find the binding bottleneck',detail:'Identify an actual SF project that would benefit from extra technical assistance beyond existing support.'},{title:'Deliver additional advice',detail:'Include failed projects and all delivery costs; a new membership is not automatically a new service.'},{title:'Measure net additional housing and health',detail:'Count completion or acceleration relative to the same project without this support, then health-relevant resident exposure.'}],
 boundary:'This is a conditional research case for a real program, not an available construction grant. HAC has separate c3 and c4 recipients; its giving form says memberships default to c4 unless requested otherwise. The modeled restriction and accepting entity are unverified. Count HAC/Onyx as one pathway, not two organizations producing the same homes.'},
 model:{headline:money(result.costPerTenQalys)+' per 10 QALYs',
 body:'The central case assumes 20 net SF homes, a 10-point completion improvement and 50% funding additionality: one expected gift-attributable net home. We assume 0.1 health-affected people per home, a 0.02 net annual utility gain and five discounted incremental health years: 0.01 QALY per net home. Every modeled input is judgmental, not a measured HAC effect.',
 equation:{label:'DONOR DOLLARS PER 10 QALYS',expression:'10 × $15,000 ÷ (20 × 0.10 × 0.50 × 0.10 × 0.02 × 5)',result:money(result.costPerTenQalys)},
 inputColumnLabel:'Central assumption',
 inputs:[input('cost','Full advisory-project-year budget','$15,000','$7,500–$30,000','100 technical hours at $100 fully loaded, 40 coordination hours at $75, plus $2,000 operating cost. Include failed effort; all allowances are judgments.'),
 input('homes','Net SF homes conditional on completion','20','5–100','Net of demolition, replacement and offsetting construction. No SF unit count is verified; 100-home favorable scope is especially speculative.'),
 input('completion','Completion probability improvement','10 percentage points','2–25 points; zero possible','Difference from funded/public/other-provider support already available. Do not apply a second generic realization factor.'),
 input('funding','Funding additionality','50%','10–75%; zero possible','Does the gift expand assistance beyond Sobrato support, fees and substitute funds?'),
 input('people','Health-affected people per net home','0.1','0.1–0.5','Not all new occupants escape homelessness. No program-matched evidence fixes this bridge.'),
 input('utility','Net annual utility change','0.02','0.01–0.02; zero or negative','Includes shared displacement/construction harms; not a direct conversion of rent savings to health.'),
 input('years','Discounted incremental health years','5','2–5 effective years','Finite exposure after completion, discounted to gift date and cut off at comparator catch-up; not building lifetime.')],
 giftHeading:'Joint scenarios—not donation offers',
 sensitivity:data.scenarios.map(s=>{const r=hacModel(resolveHacScenario(data,s));return {case:s.id.replaceAll('_',' '),headline:money(r.costPerTenQalys),detail:r.netQalys+' incremental QALYs; '+r.status};}),
 uncertaintyBoundary:'At 3% annual discount with benefits starting three years after the gift, five effective years implies about 5.96 subsequent calendar years of health benefit. This is an interpretation of the judgment, not evidence or another multiplier. Later completion or earlier catch-up lowers the effective horizon. Shared harms are already in net utility; only separate donor-caused health harm belongs outside funding additionality.',
 fundingBoundary:'The $500 standard fee ($250 for specified alumni) is a participant payment, not service cost. The advertised $12,000 service value is not audited spending. Existing underwriting, a closed pilot and unverified SF project mean no marginal offer is established. No fee is subtracted from our full delivery allowance.'},
 comparisonBridge:{headline:'The favorable case needs substantial, genuinely additional housing',
 body:'At central costs and health per home, beating $100K/10 QALYs requires more than 150 gift-attributable net homes, versus one in the central model. The favorable case needs more than 15 and assumes 18.75.',
 equation:{label:'CENTRAL THRESHOLD',expression:'$15,000 ÷ ($10,000 per QALY × 0.01 QALY per net home)',result:'More than 150 net homes'},
 inputs:[],sensitivity:[{case:'Favorable, but only 20 homes',headline:'$400K',detail:'per 10 QALYs; all other favorable inputs unchanged'},{case:'Favorable, but 25% funding additionality',headline:'$240K',detail:'per 10 QALYs; all other favorable inputs unchanged'}],
 boundary:'Full-resource cost is unpriced, not zero. Participant labor, net construction/land opportunity costs, public implementation and follow-on costs need a project-specific counterfactual. Financing and transfers are not themselves resource costs. This is donor-budget effectiveness, not a complete societal comparison.'},
 evidence:[{key:'Actual program',design:'Current provider program and cohort pages',population:'Regional developers; an SF-based participant, not a verified SF project',result:'A one-year technical-assistance program, existing partners and closed applications are documented.',transfer:'No causal completion effect, additional SF slot or marginal cost is measured.'},{key:'Housing affordability mechanism',design:'Philadelphia Fed working-paper summary, February 2020',population:'Large new apartment buildings in low-income areas',result:'Evidence supports an intermediate local rent mechanism.',transfer:'Not evidence of HAC impact, small-infill transfer or QALYs per home. Supportive-housing and voucher effects cannot automatically transfer to market housing.'}],
 reservations:['The favorable 100-home case is not established for the named SF-based participant.','A project could be built anyway, remain unfinanceable or offset other construction; endorsements are not outcomes.','The selected technical-assistance program is not an organization-wide evaluation of every HAC policy activity.','Health effects, delivery cost and funding additionality need empirical calibration.'],
 excludedBenefits:['No electoral or historical policy-win credit.','No second Onyx or general advocacy credit for the same homes.','No lifetime-of-building benefit or direct income/rent-to-QALY conversion.'],
 sources:data.sources.map(s=>({publisher:'Provider or primary research',title:s.title,url:s.url,published:s.source_date_label,retrieved:data.review_date,sourceType:s.supports})),
};
export default function Page(){return <CharityResearchReport content={content}/>;}
