import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {calculate,scenarios,anchors} from '../lib/alameda-health-consortium-model.mjs';
const r=calculate();
assert.deepEqual(r,JSON.parse(readFileSync(new URL('../data/bay/alameda-health-consortium-results.json',import.meta.url))));
assert.equal(r.bayCostPer10,8386424.071630219);
const c=r.results.find(x=>x.id==='central');
assert.equal(c.additionalCoveragePeople,7323*.1+9339*.03);
assert.equal(c.coverageQ,c.additionalCoveragePeople*.01*.5);
assert.equal(c.pediatricPersonEquivalents,130977/120);
assert.equal(c.behavioralQ,130977/120*.25*.25*.04*.5*.25*.5);
assert.equal(c.workforceQ,83*.5*20*.01*.2*.5);
assert.equal(c.annualBayQ,(c.coverageQ+c.behavioralQ+c.workforceQ-1)*.7*.98);
assert.equal(r.weightedAnnualBayQ,r.results.reduce((q,s)=>q+s.weight*s.annualBayQ,0));
assert.equal(r.results[0].annualBayQ,0);assert.equal(r.results[1].annualBayQ,0);assert.ok(r.results[2].annualBayQ<0);
for(const x of r.results.slice(0,3))assert.equal(x.bayCostPer10,null);
assert.equal(calculate({gift:0}).weightedGiftBayQ,0);
assert.equal(calculate({gift:5000}).weightedGiftBayQ,r.weightedGiftBayQ/2);
assert.equal(calculate({wholeExpense:anchors.wholeExpense*2}).bayCostPer10,r.bayCostPer10*2);
for(const value of [null,42,'bad',[],false])assert.throws(()=>calculate(value));
for(const value of [null,{},[],42])assert.throws(()=>calculate({worlds:value}));
for(const key of ['gift','wholeExpense'])for(const value of [-1,NaN,Infinity,'2'])assert.throws(()=>calculate({[key]:value}));
for(const patch of [{id:' '},{weight:NaN},{weight:.9},{scale:4},{minutesPerPerson:0},{coverageYears:Infinity},{bhTrialQ:1},{bay:2},{harmQ:-1}])assert.throws(()=>calculate({worlds:[{...scenarios[4],weight:1,...patch}]}));
assert.throws(()=>calculate({worlds:[{...scenarios[4],weight:.5},{...scenarios[4],weight:.5}]}));
const noBroad=calculate({worlds:scenarios.map(s=>({...s,bhNonOverlap:0,chwNonOverlap:0}))});
assert.ok(noBroad.weightedAnnualBayQ<r.weightedAnnualBayQ);
const zero=calculate({worlds:[{...scenarios[4],weight:1,scale:0}]});assert.equal(zero.weightedAnnualBayQ,0);assert.equal(zero.bayCostPer10,null);
const report=JSON.parse(readFileSync(new URL('../data/bay/alameda-health-consortium-report.json',import.meta.url)));
for(const e of report.evidence)for(const k of ['key','design','population','result','transfer'])assert.ok(typeof e[k]==='string'&&e[k].trim());
for(const e of report.model.sensitivity)for(const k of ['case','headline','detail'])assert.ok(typeof e[k]==='string'&&e[k].trim());
assert.ok(report.evidence.some(e=>e.key==='retention-null'));
assert.equal(report.modelVersion,r.modelVersion);
console.log('AHC v1 passed: full snapshot, independent pathway arithmetic, signed/null, scale, malformed inputs, finite bounds, overlap and renderer fields.');
