import assert from 'node:assert/strict';
import fs from 'node:fs';
import * as m from '../lib/berkeley-free-clinic-model.mjs';
const r=m.calculate();
const saved=JSON.parse(fs.readFileSync(new URL('../data/bay/berkeley-free-clinic-results-v1.json',import.meta.url),'utf8'));
const compact={modelVersion:'berkeley-free-clinic-whole-org-v1',weighted:{giftQaly:r.expectedGiftQaly,donorUsdPer10Qaly:r.donorUsdPer10Qaly,verifiedCompleteGrossResourceUsdPer10Qaly:r.verifiedCompleteGrossResourceUsdPer10Qaly,illustrativeVolunteerInclusiveGrossUsdPer10Qaly:r.illustrativeVolunteerInclusiveGrossUsdPer10Qaly,favorableTailShare:r.favorableTailShareOfSignedExpectedQaly,noFavorableDonorUsdPer10Qaly:r.noFavorableDonorUsdPer10Qaly,modeledBayResidentUsdPer10Qaly:r.modeledBayResidentUsdPer10Qaly,modeledSfResidentUsdPer10Qaly:r.modeledSfResidentUsdPer10Qaly},scenarios:r.scenarios.map(s=>({name:s.name,giftQaly:s.giftQaly,donorUsdPer10Qaly:s.donorUsdPer10Qaly,illustrativeGrossUsdPer10Qaly:s.illustrativeVolunteerInclusiveGrossUsdPer10Qaly,uniqueClientEquivalents:s.uniqueServiceClientEquivalents,healthBenefitingClientEquivalents:s.healthBenefitingClientEquivalents}))};
assert.deepStrictEqual(compact,saved);
assert.strictEqual(r.diagnostics.cashCostPerReportedClient,453528/2007);assert.strictEqual(r.diagnostics.encountersPerReportedClient,3153/2007);
assert.strictEqual(r.diagnostics.currentVolunteerHoursProxy,31000*150/180);assert.strictEqual(r.verifiedCompleteGrossResourceUsdPer10Qaly,null);
assert.strictEqual(r.inputs.fy2025NetAssetsOrFundBalancesUsd,1193255);assert.strictEqual(r.inputs.currentRenovationCostUsd,196809);assert.strictEqual(r.inputs.currentRenovationAccountingTreatment,null);
assert(r.scenarios.find(s=>s.name==='harm').giftQaly<0);assert.strictEqual(r.scenarios.find(s=>s.name==='null').giftQaly,0);
assert(r.favorableTailShareOfSignedExpectedQaly>.75);assert(r.noFavorableDonorUsdPer10Qaly>r.donorUsdPer10Qaly);
assert.strictEqual(r.verifiedBayServiceSiteShare,1);assert.strictEqual(r.measuredBayResidentShare,null);assert.strictEqual(r.measuredSfResidentShare,null);assert(r.modeledSfResidentImpactShare<=r.modeledBayResidentImpactShare);
const doubled=m.calculate({ordinaryGiftUsd:200000});assert.strictEqual(doubled.expectedGiftQaly,r.expectedGiftQaly*2);assert.strictEqual(doubled.donorUsdPer10Qaly,r.donorUsdPer10Qaly);
const zero=m.calculate({},m.SCENARIOS.map(s=>Object.assign({},s,{fundingAdditionality:0})));assert.strictEqual(zero.expectedGiftQaly,0);assert.strictEqual(zero.donorUsdPer10Qaly,null);assert.strictEqual(zero.modeledBayResidentUsdPer10Qaly,null);
const content=JSON.parse(fs.readFileSync(new URL('../data/bay/berkeley-free-clinic-report.json',import.meta.url),'utf8'));assert.strictEqual(content.organization,r.organization);assert(content.model.equation.result.includes('$3,617,451'));assert(content.summary.some(x=>x.label==='VERIFIED GROSS'&&x.value==='Unavailable'));
console.log('PASS Berkeley Free Clinic: exact saved results, whole-expense client unit, signed/null, volunteer proxy, geography, zero and 2x scaling');
assert(Array.isArray(content.evidence)&&content.evidence.length>=3);
for(const item of content.evidence)for(const field of ['key','population','design','result','transfer'])assert(typeof item[field]==='string'&&item[field].trim());
for(const field of ['reservations','excludedBenefits','sources'])assert(Array.isArray(content[field]));
