import assert from 'node:assert/strict';
import fs from 'node:fs';
import {calculate,scenarios,anchors,discountedYears} from '../lib/bike-east-bay-model.mjs';
const r=calculate(),near=(a,b)=>assert.ok(Math.abs(a-b)<1e-10*Math.max(1,Math.abs(b)));
assert.equal(anchors.wholeExpense,1897776+7478+3141);
assert.deepEqual(r,JSON.parse(fs.readFileSync(new URL('../data/bay/bike-east-bay-results.json',import.meta.url))));
const c=r.results.find(x=>x.id==='central');near(c.residualAnnualDeaths,6/5*.75);near(c.residualAnnualSevere,35/5*.75);
let integral=0;for(let i=0;i<100000;i++)integral+=3/100000*(1.03)**(-(4+(i+.5)*3/100000));near(discountedYears(3,4),integral);
near(c.roadQ,(6/5*10+35/5*2)*.75*.2*integral*.1*.5);
near(c.activityQ,1158*.1*.3*.005*.5*.8);near(c.budgetBayQ,(c.roadQ+c.activityQ-.1)*.4*.98);
near(r.bayCostPer10,19089887.645172846);near(r.weightedGiftBayQ,r.weightedBayQ*10000/1908395);
assert.equal(r.results[0].giftBayQ,0);assert.equal(r.results[1].giftBayQ,0);assert.ok(r.results[2].giftBayQ<0);assert.equal(r.results[2].bayCostPer10,null);
assert.ok(r.favorableShare>1);assert.equal(r.probabilityBelow1M,0);assert.equal(r.completeResourceCostPer10,null);
assert.equal(calculate({gift:0}).weightedGiftBayQ,0);near(calculate({gift:5000}).weightedGiftBayQ,r.weightedGiftBayQ/2);near(calculate({wholeExpense:anchors.wholeExpense*2}).bayCostPer10,r.bayCostPer10*2);
for(const x of [null,42,'bad',[]])assert.throws(()=>calculate(x));
for(const gift of [-1,10001,Infinity,NaN,'100'])assert.throws(()=>calculate({gift}));
for(const worlds of [[],null,[null],[[]],Array(101).fill(scenarios[0])])assert.throws(()=>calculate({worlds}));
for(const[k,v]of Object.entries({id:' ',weight:-1,riskScale:4,residual:2,fatalQ:Infinity,seriousQ:11,reduction:2,years:11,lag:16,contribution:2,realization:-1,participantScale:4,extraCycling:2,extraActivity:2,utility:1,activityYears:3,nonOverlap:2,funding:2,bay:2,harm:-1}))assert.throws(()=>calculate({worlds:[{...scenarios[4],weight:1,[k]:v}]}));
assert.throws(()=>calculate({worlds:[{...scenarios[4],id:'a',weight:.5},{...scenarios[4],id:' a ',weight:.5}]}));assert.throws(()=>calculate({worlds:[scenarios[4]]}));
const no=scenarios.filter(s=>s.id!=='favorable').map(s=>({...s,weight:s.weight/.9}));assert.equal(calculate({worlds:no}).bayCostPer10,null);
assert.equal(calculate({worlds:[{...scenarios[4],weight:1,reduction:-.2,utility:0}]}).bayCostPer10,null);
const report=JSON.parse(fs.readFileSync(new URL('../data/bay/bike-east-bay-report.json',import.meta.url)));
assert.equal(report.modelVersion,r.modelVersion);
for(const e of report.evidence)for(const k of ['key','design','population','result','transfer'])assert.ok(e[k]?.length);
for(const e of report.model.sensitivity)for(const k of ['case','headline','detail'])assert.ok(e[k]?.length);
for(const e of report.sources)for(const k of ['publisher','title','url','published','retrieved','sourceType'])assert.ok(e[k]?.length);
assert.ok(!report.donationUrl);assert.ok(report.sources.some(s=>s.url.includes('giving-season-2018')));
console.log('Bike East Bay: saved parity, cost addbacks, independent injury/activity/integral math, signed/null, bounds, malformed inputs, identity/weights, renderer and provenance pass.');
