import assert from 'node:assert/strict';
import fs from 'node:fs';
import {calculate,oldBaseline,FINANCE,WORLDS} from '../lib/breathe-v2-model.mjs';
const saved=JSON.parse(fs.readFileSync(new URL('../data/san-francisco/breathe-v2-results.json',import.meta.url)));
assert.deepEqual(calculate(),saved.result);
assert.deepEqual(oldBaseline(),saved.old);
assert.deepEqual(calculate({oldAllocation:true}),saved.oldAllocation);
assert.equal(oldBaseline().bay.donor_per_10q,5739210.197176861);
assert.equal(FINANCE.environment+FINANCE.lung+FINANCE.tobacco+FINANCE.community+FINANCE.admin+FINANCE.eventDirect,FINANCE.whole);
for(const x of [null,42,'x',[],true])assert.throws(()=>calculate(x));
for(const x of [NaN,Infinity,-1,100001,Number.MIN_VALUE])assert.throws(()=>calculate({gift:x}));
assert.equal(calculate({gift:0}).weighted.bay.qaly,0);
assert.equal(calculate({gift:0}).weighted.bay.pricePer10,null);
assert.equal(calculate().wholeOrganizationExpectedQaly,null);
for(const worlds of [null,[],{},[{id:'x',weight:1,inputs:42}],[{id:' ',weight:1}],[{id:'x',weight:NaN}],[{id:'x',weight:.5}]])assert.throws(()=>calculate({worlds}));
assert.throws(()=>calculate({worlds:[{id:'x',weight:.5},{id:' x ',weight:.5}]}));
assert.throws(()=>calculate({worlds:[{id:'x',weight:1,inputs:{cpap_bay_share:Infinity}}]}));
assert.throws(()=>calculate({worlds:[{id:'x',weight:1,inputs:{bogus:1}}]}));
assert.throws(()=>calculate({worlds:[{id:'x',weight:1,inputs:null}]}));
assert.throws(()=>calculate({worlds:[{id:'x',weight:1,foundation:null}]}));
const signed=calculate({worlds:[WORLDS[1]].map(w=>({...w,weight:1}))});
assert(signed.weighted.bay.qaly<0);assert.equal(signed.weighted.bay.pricePer10,null);
const zero=calculate({worlds:[{...WORLDS[0],weight:1}]});assert.equal(zero.weighted.bay.qaly,0);
const half=calculate({gift:50000});assert(Math.abs(half.weighted.bay.qaly*2-calculate().weighted.bay.qaly)<1e-15);
for(const residual of [NaN,Infinity,10001,'1'])assert.throws(()=>calculate({residualBayQaly:residual}));
assert.equal(calculate({residualBayQaly:1}).wholeOrganizationExpectedQaly,null);
assert.throws(()=>calculate({worlds:[{id:'tiny-positive',weight:1,foundation:{cessation_additionality:0,asthma_additionality:0},inputs:{cpap_qaly_one_year:1e-310}}]}));
const {reportSections,markdownBlocks}=await import('../lib/report-markdown.mjs');
const {markdown}=JSON.parse(fs.readFileSync(new URL('../data/san-francisco/breathe-v2-narrative.json',import.meta.url)));
assert.equal(markdown,fs.readFileSync(new URL('../docs/reports/breathe-v2.md',import.meta.url),'utf8'));
assert(markdown.trim().split(/\s+/u).length>9000);
const sections=reportSections(markdown);assert.equal(sections.length,9);
const ids=new Set(sections.map(s=>s.id));
for(const section of sections)for(const block of markdownBlocks(section.markdown))if(block.id)ids.add(block.id);
for(const match of markdown.matchAll(/\]\(#([^)]*)\)/g))assert(ids.has(match[1]),'Missing anchor: '+match[1]);
const {sources}=JSON.parse(fs.readFileSync(new URL('../data/san-francisco/breathe-v2-sources.json',import.meta.url)));
for(const row of sources)for(const key of ['publisher','title','url','published','retrieved'])assert.equal(typeof row[key],'string');
assert.equal(new Set(sources.map(s=>s.url)).size,sources.length);
const emptyAllocation=calculate({worlds:[{id:'custom',weight:1,foundation:{cessation_allocation:0,asthma_allocation:0},inputs:{cpap_allocation:0}}]}).worlds[0].result;
assert.equal(emptyAllocation.other_allocation_usd,100000-emptyAllocation.central_enabling_cost_usd);
console.log('Breathe V2: saved full-output, old baseline, finance, signed/null, scale and malformed-input regression checks passed');
