import fs from 'node:fs';import assert from 'node:assert/strict';import{calculate,inputsFor,finiteIntegral,triangularIntegral,inputKeys,bpSurvivalQ,expectedValue}from '../lib/clinic-portfolio-model.mjs';
const read=n=>JSON.parse(fs.readFileSync(new URL(n,import.meta.url))),m=read('../data/san-francisco/clinic-portfolio-model-v2.json'),saved=read('../data/san-francisco/clinic-portfolio-results.json');let checks=0;const ok=x=>{assert.ok(x);checks++;},near=(a,b)=>ok(Math.abs(a-b)<=1e-8*Math.max(1,Math.abs(a),Math.abs(b)));
for(const[i,s]of m.scenarios.entries()){const p=inputsFor(m,s),r=calculate(p);assert.deepEqual({case:s.id,...r},saved[i]);checks++;near(r.dental_budget+r.mental_budget+r.remaining_medical_food_budget,p.gift_usd);near(r.all_q,r.dental_q+r.mental_q+r.bp_q+r.residual_q-p.independent_harm_q);ok(r.dental_n<=p.dental_capacity);ok(r.mental_n<=p.mental_capacity);for(const[g,share]of[['all',1],['bay',p.bay_share],['sf',p.sf_share]]){near(r[g+'_q'],r.all_q*share);for(const[t,budget]of[['donor',p.gift_usd],['resource',r.gross_resource_usd]]){const price=r[t+'_'+g+'_per_10q'];if(r[g+'_q']>0)near(price*r[g+'_q'],10*budget);else ok(price===null);}}}
for(const k of inputKeys){const p={...m.central_inputs};delete p[k];assert.throws(()=>calculate(p));checks++;for(const value of[NaN,Infinity,-Infinity,'0']){assert.throws(()=>calculate({...m.central_inputs,[k]:value}));checks++;}for(const value of[m.input_meta[k].min-1,m.input_meta[k].max+1]){assert.throws(()=>calculate({...m.central_inputs,[k]:value}));checks++;}}
assert.throws(()=>calculate({...m.central_inputs,sf_share:1,bay_share:.5}));checks++;assert.throws(()=>calculate({...m.central_inputs,medical_allocation:0}));checks++;
// Independent midpoint quadrature, broad deterministic finite domains.
for(let i=0;i<160;i++){const h=(i%17)/16,rate=i===0?0:(i%23)*.23,n=20000;let a=0,b=0;for(let j=0;j<n;j++){const t=h*(j+.5)/n,e=Math.exp(-rate*t);a+=e*h/n;b+=h?e*(1-t/h)*h/n:0;}near(a,finiteIntegral(rate,h));near(b,triangularIntegral(rate,h));}
let seed=284;const rand=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/2**32;};for(let i=0;i<500;i++){const p={...m.central_inputs};for(const k of inputKeys){const{min,max}=m.input_meta[k];p[k]=min+(max-min)*rand();}const shares=[rand(),rand(),rand(),rand()],sum=shares.reduce((a,b)=>a+b);['dental_allocation','mental_allocation','medical_allocation','food_other_allocation'].forEach((k,j)=>p[k]=shares[j]/sum);const inner=['acute_medical_share','chronic_medical_share','referral_medical_share'],innerSum=inner.reduce((s,k)=>s+p[k],0);inner.forEach(k=>p[k]/=innerSum);p.sf_share*=p.bay_share;const r=calculate(p);Object.values(r).forEach(v=>ok(v===null||Number.isFinite(v)));ok(Math.abs(r.dental_q)<=p.dental_capacity*(.3*p.dental_horizon+.5));ok(Math.abs(r.mental_q)<=p.mental_capacity*(.3*p.mental_horizon/2+.5));}
const c=calculate(m.central_inputs),cap=calculate({...m.central_inputs,gift_usd:1000000});ok(cap.dental_n===30);ok(cap.mental_n===20);ok(cap.donor_sf_per_10q>c.donor_sf_per_10q);ok(c.sf_q<=c.bay_q);ok(c.bay_q<=c.all_q);
// Independent BP survival integration: explicit piecewise hazard time and mortality.
for(let i=0;i<150;i++){const p={...m.central_inputs,bp_baseline_hazard:.003+(i%13)*.004,bp_relative_hazard:.3+(i%17)*.1,bp_latency:(i%7)*.2,bp_active_years:(i%9)*.3,bp_horizon:(i%11)*1.1};const b=p.bp_baseline_hazard,bs=b*(1+(p.bp_relative_hazard-1)*p.bp_modern_gap*p.bp_delivery_transfer),n=40000;let q=0;for(let j=0;j<n;j++){const t=p.bp_horizon*(j+.5)/n,active=Math.max(0,Math.min(t,p.bp_active_years)-p.bp_latency);const sd=Math.exp(-b*t-(bs-b)*active)-Math.exp(-b*t);q+=sd*Math.exp(-p.discount*t)*p.bp_utility*Math.exp(-p.discount*p.bp_delay)*p.bp_horizon/n;}near(q,bpSurvivalQ(p));}
const expected=expectedValue(m);for(const g of['all','bay','sf']){near(expected[g+'_q'],m.expected_value.weights.reduce((v,w)=>v+w.weight*calculate(inputsFor(m,m.scenarios.find(s=>s.id===w.id)))[g+'_q'],0));near(expected['donor_'+g+'_per_10q']*expected[g+'_q'],1e6);}
assert.throws(()=>expectedValue(m,[{id:'Central',weight:.5}]));checks++;
console.log(JSON.stringify({status:'PASS',scenarios:m.scenarios.length,checks}));

