import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{calculate,anchors,scenarios}from'../lib/dentists-on-wheels-model.mjs';const r=calculate(),near=(x,y)=>assert.ok(Math.abs(x-y)<1e-12);
test('first output immutable',()=>{assert.equal(r.bayQ,.06309754566911488);assert.equal(r.bayCostPer10,1584847.6979501315)});
test('full saved output parity',()=>assert.deepEqual(r,JSON.parse(fs.readFileSync('data/bay/dentists-on-wheels-results.json'))));
test('procedure sum exact not patient denominator',()=>{assert.equal(anchors.extractions+anchors.fillings+anchors.rootCanals+anchors.crownsBridges+anchors.dentures,512);assert.equal(r.patients,249)});
test('whole expense',()=>assert.equal(r.expense,103749));
test('balance reconciliation',()=>assert.equal(anchors.cash+anchors.savings,anchors.unrestrictedNetAssets));
test('signed null and harm',()=>{assert.equal(r.rows[0].bayQ,0);assert.equal(r.rows[1].bayQ,0);assert.ok(r.rows[2].bayQ<0)});
test('expectation then ratio',()=>near(r.bayCostPer10,100000/r.rows.reduce((a,s)=>a+s.weight*s.bayQ,0)));
test('central arithmetic',()=>near(r.rows[4].bayQ,10000/103749*249*.3*(.9*.6*.85*.05*.25-.0002)*.98));
test('half gift',()=>near(calculate({gift:5000}).bayQ,r.bayQ/2));
test('zero gift',()=>{assert.equal(calculate({gift:0}).bayQ,0);assert.equal(calculate({gift:0}).bayCostPer10,null)});
test('gift cap',()=>assert.throws(()=>calculate({gift:100000}),RangeError));
test('malformed options',()=>{for(const x of[null,[],42,'x',true])assert.throws(()=>calculate(x),TypeError)});
test('malformed worlds',()=>{for(const worlds of[[],{},null,[null],[[]]])assert.throws(()=>calculate({worlds}))});
test('duplicateid',()=>assert.throws(()=>calculate({worlds:scenarios.map(s=>({...s,id:'x'}))}),TypeError));
test('derived overflow',()=>assert.throws(()=>calculate({expense:Number.MIN_VALUE}),RangeError));
test('bad coefficient',()=>assert.throws(()=>calculate({worlds:scenarios.map(s=>({...s,utility:Infinity}))}),RangeError));
test('duration bounded',()=>assert.throws(()=>calculate({worlds:scenarios.map(s=>({...s,years:10}))}),RangeError));
test('no imaginary resource price',()=>assert.equal(r.completeResourceCostPer10,null));
test('renderer schema',()=>{const p=JSON.parse(fs.readFileSync('data/bay/dentists-on-wheels-report.json'));for(const a of[p.summary,p.programSection.steps,p.model.inputs,p.model.sensitivity,p.evidence,p.reservations,p.excludedBenefits,p.sources])assert.ok(Array.isArray(a)&&a.length);assert.ok(p.model.sensitivity.every(s=>s.case&&s.headline&&s.detail));assert.ok(p.evidence.every(s=>['key','design','population','result','transfer'].every(k=>typeof s[k]==='string')))});
