import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {reportPrice,formatEditionReportPrice} from '../lib/geography-reports.mjs';
const read=p=>JSON.parse(fs.readFileSync(new URL(p,import.meta.url)));
const report=read('../data/geography-reports.json').reports.find(r=>r.edition==='california'&&r.slug==='center-for-independent-living');
const historicalModel=read('../data/california/cil-ca-pre-recalibration-model.json');
test('Frozen CIL repair diagnostic independently reconstructs support, completed episodes and finite function-days',()=>{
 const p=Object.fromEntries(historicalModel.inputs.map(x=>[x.name,x.value]));
 const cost=(p.w*p.b*p.h+p.p)*p.o;
 const episodes=p.C*p.f/cost*p.m*p.s*p.a;
 const years=p.D/365;
 const benefit=p.du*Math.exp(-p.r*p.L)*(-Math.expm1(-p.r*years))/p.r;
 const q=episodes*benefit*p.g_CA;
 const prior=historicalModel.scenarios.find(s=>s.id==='historical-alpha-central');
 assert.ok(Math.abs(cost-450.3927899225193)<1e-10);
 assert.ok(Math.abs(episodes-4.440568421053229)<1e-10);
 assert.ok(Math.abs(q-prior.editionQalys)<1e-12);
 assert.ok(Math.abs(10*p.C/q-59187952.33043336)<1e-5);
});
test('CIL historical withdrawn review preserves diagnostic math without constraining later recalibration',()=>{
 assert.equal(report.stage,'beta');assert.equal(report.acceptance.status,'accepted');
 const historicalReport={...report,model:historicalModel};
 assert.equal(reportPrice(historicalReport),null);assert.equal(formatEditionReportPrice(historicalReport),'$59.2M');
 const central=historicalModel.scenarios.find(s=>s.id==='central');
 assert.equal(central.editionQalys,null);assert.equal(central.allPopulationQalys,null);
 const legacy=historicalModel.scenarios.find(s=>s.id==='historical-alpha-central');
 assert.equal(legacy.editionQalys,0.016895330225604348);
 assert.equal(historicalModel.scenarios.length,5);
 assert.match(report.sections.monitoring,/original auditor report remained inaccessible/);
 assert.match(report.sections.monitoring,/does not establish resolution/);
 assert.ok(report.sources.some(s=>s.id==='cil-whill'));
 const ca=read('../docs/geography-progress.json').editions.find(e=>e.id==='california');
 assert.ok(ca.betaIds.includes(report.organizationId));assert.equal(ca.betaAcceptedPublished,ca.betaIds.length);
 const sessions=read('../data/research-effort.json').organizations[report.organization].sessions;
 const originalSessions=sessions.filter(s=>s.workerId==='ca-cil-beta-20260930');
 assert.equal(originalSessions.length,2);assert.ok(originalSessions.every(s=>s.endedAt));
 assert.ok(originalSessions.every(s=>s.model.id==='gpt-6.1-sol'&&/User-confirmed model assignment/.test(s.model.evidence)));
 const minutes=originalSessions.reduce((n,s)=>n+(Date.parse(s.endedAt)-Date.parse(s.startedAt))/60000,0);
 assert.ok(Math.abs(minutes-5.80905)<1e-8);
});
