import assert from 'node:assert/strict';
import fs from 'node:fs';
import {calculate,evaluate,BASE,FINANCES,historicalMix} from '../lib/glide-v2-model.mjs';
import {calculate as original} from '../lib/glide-v2-original-model.mjs';
const saved=JSON.parse(fs.readFileSync(new URL('../data/san-francisco/glide-v2-results.json',import.meta.url)));
assert.deepEqual(calculate(),saved);
assert.deepEqual(calculate().central,original(BASE));
assert.equal(calculate().central.bay.donor_per_10q,4890656.595775775);
assert.equal(calculate().weightedExpectation,null);
assert.equal(calculate().wholeOrganizationExpectedQaly,null);
for(const x of [null,42,[],true,'x'])assert.throws(()=>calculate(x));
for(const gift of [null,NaN,Infinity,-1,Number.MIN_VALUE,1000001,'100'])assert.throws(()=>calculate({gift}));
assert.throws(()=>calculate({extra:1}));
for(const gift of [0,1e-6,1,10000,100000,1000000])assert.doesNotThrow(()=>calculate({gift}));
for(const x of [null,[],true,NaN])assert.throws(()=>evaluate(x));
for(const f of FINANCES)assert.equal(f.program+f.management+f.fundraising+f.event+f.inventory,f.whole);
assert.ok(Math.abs(Object.values(historicalMix().allocation).reduce((a,b)=>a+b,0)-1)<1e-12);
const z=structuredClone(BASE);z.shared.funding_additionality=0;assert.equal(evaluate(z).bay.qaly,0);
const h=structuredClone(BASE);h.shared.independent_harm_q=1;assert.ok(evaluate(h).bay.qaly<0);
const cap=calculate({gift:1000000});assert.deepEqual(cap.central.bay.qaly,calculate().central.bay.qaly);
assert.ok(Math.abs(cap.central.bay.donor_per_10q/(calculate().central.bay.donor_per_10q*10)-1)<1e-14);
console.log('PASS: exact full saved output, original central parity, finance reconciliation, signed/null/cap and malformed/finite guards');
const report=JSON.parse(fs.readFileSync(new URL('../data/san-francisco/glide-v2-report.json',import.meta.url)));
for(const row of report.summary)for(const key of ['label','value','detail'])assert.equal(typeof row[key],'string');
for(const row of report.evidence)for(const key of ['key','design','population','result','transfer'])assert.equal(typeof row[key],'string');
for(const row of report.sources)for(const key of ['publisher','title','url','published','retrieved','sourceType'])assert.equal(typeof row[key],'string');
assert.equal(new Set(report.sources.map(s=>s.url)).size,report.sources.length);
assert.equal(new Set(report.longForm.sections.map(s=>s.id)).size,report.longForm.sections.length);
const markdown='# GLIDE Foundation — V2 whole-gift, partial-health assessment\n\n'+report.longForm.summary+'\n\n'+report.longForm.sections.map(s=>'## '+s.title+'\n\n'+s.markdown).join('\n\n')+'\n';
assert.equal(fs.readFileSync(new URL('../docs/reports/glide-v2.md',import.meta.url),'utf8'),markdown);
assert.ok(report.longForm.wordCount>=10000);
assert.ok(report.longForm.summaryWordCount>=700&&report.longForm.summaryWordCount<=800);
assert.equal(report.modelVersion,saved.version);
assert.equal(report.model.sensitivity.length,25);
console.log('PASS: canonical renderer fields, unique sources/sections, Markdown/JSON exact parity, 10k long form and approximately750-word summary');
