import fs from 'node:fs';import assert from 'node:assert/strict';
import {calculate,survivalQ} from '../lib/glide-coverage-model.mjs';import {scenarios} from '../lib/glide-coverage-scenarios.mjs';
const m=JSON.parse(fs.readFileSync(new URL('../data/san-francisco/glide-coverage-v2.json',import.meta.url)));let checks=0;const eq=(a,b)=>{assert.ok(Math.abs(a-b)<1e-7*Math.max(1,Math.abs(b)),`${a} vs ${b}`);checks++;};
function quad(a){let sum=0,cuts=[...new Set([0,a.horizon,Math.min(a.horizon,a.rescueYears),Math.min(a.horizon,a.moudYears)])].sort((x,y)=>x-y);for(let i=1;i<cuts.length;i++){let dt=(cuts[i]-cuts[i-1])/20000;for(let j=0;j<20000;j++){let t=cuts[i-1]+dt*(j+.5),int=a.base*t-a.rescue*Math.min(t,a.rescueYears);int+=(a.hr-1)*(a.base*Math.min(t,a.moudYears)-a.rescue*Math.min(t,a.moudYears,a.rescueYears));sum+=(Math.exp(-int)-Math.exp(-a.base*t))*Math.pow(1+a.discount,-t-a.delay)*a.utility*dt;}}return sum;}
for(const {inputs:x}of scenarios(m)){const o=calculate(x),s=x.shared,p=x.survival;const E=Math.min(s.gift,s.capacity_gift),nR=Math.min(E*x.allocation.rescue/(p.rescue_cost*Math.max(1,p.rescue_active_years)),p.rescue_capacity),nM=Math.min(E*x.allocation.moud/(p.moud_annual_foundation_cost*Math.max(1,p.moud_active_years)),p.moud_capacity);eq(o.rescue_nominal,nR);eq(o.moud_nominal,nM);let N=nR*s.funding_additionality,M=nM*s.funding_additionality*(1-p.moud_no_gift_treatment_share)*p.moud_effective_retention,O=Math.min(N,M)*p.rescue_moud_overlap;eq(o.shared_survival_people,O);let a={base:p.baseline_all_cause_hazard,rescue:p.rescue_hazard_reduction,hr:1-(1-p.moud_observed_hr)*p.moud_causal_transfer,rescueYears:p.rescue_active_years,moudYears:p.moud_active_years,horizon:p.horizon_years,utility:p.utility,discount:s.discount,delay:p.delay_years},R=quad({...a,moudYears:0}),T=quad({...a,rescueYears:0}),B=quad(a);eq(o.survival_q,(N-O)*R+(M-O)*T+O*B-N*p.rescue_harm_q-M*p.moud_harm_q);
let ext=E*s.common_external_fraction+nR*p.rescue_external*Math.max(1,p.rescue_active_years)+nM*p.moud_annual_external_cost*Math.max(1,p.moud_active_years),h=x.housing,H=Math.min(E*x.allocation.housing/(h.cost*Math.max(1,h.years)),h.capacity);ext+=H*h.external*Math.max(1,h.years);for(let i=0;i<x.groups.length;i++){let g=x.groups[i],d=Math.max(1,g.years/g.cost_basis_years),n=Math.min(E*x.allocation[g.id]/(g.cost*d),g.capacity),years=0;for(let j=0;j<20000;j++){let t=g.years*(j+.5)/20000;years+=Math.exp(-(g.catchup+g.mortality)*t)*Math.pow(1+s.discount,-t-g.delay)*g.years/20000;}eq(o.groups[i].nominal,n);eq(o.groups[i].qaly,n*s.funding_additionality*(g.unique_health*g.target*g.response*g.utility*years-g.harm_q));ext+=n*g.external*d+(g.id==='infection_linkage'?n*g.target*x.hcv_external_treatment_cost:0);}
eq(o.gross_external,ext);eq(o.gross_resources,s.gift+ext-H*h.cash_transfer*Math.max(1,h.years));eq(o.us.qaly,o.survival_q+o.housing_q+o.groups.reduce((z,g)=>z+g.qaly,0)-s.independent_harm_q);eq(o.bay.qaly,o.us.qaly*s.bay);eq(o.sf.qaly,o.us.qaly*s.sf);for(const r of ['us','bay','sf'])if(o[r].qaly>0){eq(o[r].donor_per_10q,s.gift*10/o[r].qaly);eq(o[r].gross_resources_per_10q,o.gross_resources*10/o[r].qaly);}}
let seed=13;const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/2**32;};for(let i=0;i<100;i++){let base=random(),a={base,rescue:(random()*2-1)*base,hr:2*random(),rescueYears:4*random(),moudYears:4*random(),horizon:10*random(),utility:random(),discount:.2*random(),delay:random()};eq(survivalQ(a),quad(a));}
console.log(JSON.stringify({status:'pass',checks,scenarios:20,random_joint_survival:100,quadrature_steps_per_segment:20000}));
