import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {calculate,scenarios,inputs} from '../lib/greenlight-model.mjs';
const r=calculate(),near=(a,b)=>assert.ok(Math.abs(a-b)<1e-10);
test('all six signed worlds retained',()=>assert.equal(r.rows.length,6));
test('weights sum one',()=>near(scenarios.reduce((a,s)=>a+s.weight,0),1));
test('whole expense verified amount not program-only',()=>assert.equal(inputs.wholeExpense,345616));
test('funding null zero',()=>assert.equal(r.rows[0].bayQalys,0));
test('clinical null zero',()=>assert.equal(r.rows[1].bayQalys,0));
test('harm remains negative',()=>assert.ok(r.rows[2].bayQalys<0));
test('central census correctly deduplicated',()=>near(r.rows[4].annualEpisodeEquivalents,139.5));
test('expectation before division',()=>near(r.bayCostPer10,100000/r.rows.reduce((a,s)=>a+s.weight*s.bayQalys,0)));
test('Bay not greater than all for positive central',()=>assert.ok(r.rows[4].bayQalys<=r.rows[4].allQalys));
test('small scale linear accounting only',()=>near(calculate({gift:5000}).weightedBayQalys,r.weightedBayQalys/2));
test('no 100k scale assurance',()=>assert.throws(()=>calculate({gift:100000}),RangeError));
test('zero gift rejected',()=>assert.throws(()=>calculate({gift:0}),RangeError));
test('bad expense rejected',()=>assert.throws(()=>calculate({wholeExpense:0}),RangeError));
test('bad weights rejected',()=>assert.throws(()=>calculate({worlds:scenarios.slice(1)}),RangeError));
test('utility/years explicitly finite',()=>assert.ok(scenarios.every(s=>s.utility<=1&&s.years<=1)));
test('all output finite or null',()=>assert.ok(r.rows.every(s=>Number.isFinite(s.bayQalys)&&(s.bayCostPer10===null||Number.isFinite(s.bayCostPer10)))));
test('double expense halves health',()=>near(calculate({wholeExpense:691232}).weightedBayQalys,r.weightedBayQalys/2));
test('no clinical effect leaves harms',()=>assert.ok(calculate({worlds:scenarios.map(s=>({...s,benefiting:0}))}).weightedBayQalys<0));
test('absent favorable tail explicitly null',()=>assert.equal(calculate({worlds:scenarios.filter(s=>s.id!=='favorable').map(s=>({...s,weight:s.weight/.9}))}).favorableShareOfSignedExpectation,null));
test('saved results reproduce',()=>near(JSON.parse(fs.readFileSync('data/bay/greenlight-results.json')).weightedBayQalys,r.weightedBayQalys));
test('entire saved default output exact parity',()=>assert.deepEqual(r,JSON.parse(fs.readFileSync('data/bay/greenlight-results.json'))));
test('tiny expense rejects overflow',()=>assert.throws(()=>calculate({wholeExpense:Number.MIN_VALUE}),RangeError));
test('enormous weekly rejects overflow',()=>assert.throws(()=>calculate({worlds:scenarios.map(s=>({...s,weekly:Number.MAX_VALUE}))}),RangeError));
test('malformed world containers rejected',()=>{for(const worlds of [null,{},[],[null],[[]],[1]])assert.throws(()=>calculate({worlds}));});
test('duplicate ids rejected',()=>assert.throws(()=>calculate({worlds:scenarios.map(s=>({...s,id:'duplicate'}))}),TypeError));
test('empty id rejected',()=>assert.throws(()=>calculate({worlds:scenarios.map(s=>({...s,id:' '}))}),TypeError));
test('missing coefficient rejected',()=>assert.throws(()=>calculate({worlds:scenarios.map(s=>({...s,utility:undefined}))}),RangeError));
test('nonfinite weight rejected before summation',()=>assert.throws(()=>calculate({worlds:scenarios.map(s=>({...s,weight:NaN}))}),RangeError));
test('renderer required arrays',()=>{const p=JSON.parse(fs.readFileSync('data/bay/greenlight-report.json'));for(const a of [p.summary,p.programSection.steps,p.model.inputs,p.model.sensitivity,p.evidence,p.reservations,p.excludedBenefits,p.sources])assert.ok(Array.isArray(a)&&a.length>0);assert.ok(p.model.sensitivity.every(s=>typeof s.case==='string'&&typeof s.headline==='string'&&typeof s.detail==='string'));});
