import assert from 'node:assert/strict';
import fs from 'node:fs';
import {calculate,inputs,scenarios} from '../lib/hif-model.mjs';
const r=calculate();
const saved=JSON.parse(fs.readFileSync(new URL('../data/bay/hif-results.json',import.meta.url)));
for(const k of ['modelVersion','gift','wholeExpense','weightedBayQalys','weightedAllQalys','bayCostPer10','allCostPer10','probabilityBelow1m','favorableShare'])assert.equal(r[k],saved[k]);
assert.equal(r.weightedBayQalys,0.001238248121842221);
assert.equal(r.bayCostPer10,80759258.37159649);
assert.equal(r.rows.find(s=>s.id==='central').bayCostPer10,340053545.18944854);
assert.equal(r.rows.find(s=>s.id==='favorable').bayCostPer10,7816222.967203288);
assert(r.favorableShare>1);
assert.equal(r.probabilityBelow1m,0);
assert.equal(calculate({gift:5000}).weightedBayQalys,r.weightedBayQalys/2);
assert.equal(calculate({gift:5000}).bayCostPer10,r.bayCostPer10);
for(const x of [null,42,'bad',[]])assert.throws(()=>calculate(x));
for(const gift of [0,-1,10001,NaN,Infinity])assert.throws(()=>calculate({gift}));
for(const wholeExpense of [0,-1,NaN,Infinity,Number.MIN_VALUE])assert.throws(()=>calculate({wholeExpense}));
for(const worlds of [[],[null],[[]],[{...scenarios[0],id:' '}],scenarios.map(s=>({...s,weight:1}))])assert.throws(()=>calculate({worlds}));
assert.throws(()=>calculate({worlds:scenarios.map(s=>({...s,persons:3}))}));
assert.throws(()=>calculate({anchorDays:366}));
const a={...scenarios[4],id:'a',weight:.5,utility:.1,harm:0};
const h=a.prevention*7.5*a.transfer*a.persons/365*a.utility;
const b={...a,id:'b',utility:0,harm:h*(1-Number.EPSILON*2)};
assert.throws(()=>calculate({wholeExpense:1e300,worlds:[a,b]}),/Aggregate numerical overflow/);
const nullWorld=calculate({worlds:[{...scenarios[0],weight:1}]});assert.equal(nullWorld.bayCostPer10,null);
const harm=calculate({worlds:[{...scenarios[2],weight:1}]});assert(harm.weightedBayQalys<0);assert.equal(harm.bayCostPer10,null);
const report=JSON.parse(fs.readFileSync(new URL('../data/bay/hif-report.json',import.meta.url)));
assert(report.model.equation.result.includes(String(r.weightedBayQalys)));
for(const e of report.evidence)for(const k of ['key','design','population','result','transfer'])assert.equal(typeof e[k],'string');
for(const e of report.model.sensitivity)for(const k of ['case','headline','detail'])assert.equal(typeof e[k],'string');
for(const e of report.sources)for(const k of ['url','published','retrieved'])assert(e[k]);
console.log('HIF exact parity, signed/null, finite bounds, scaling and renderer shape assertions passed.');
const nf=scenarios.filter(s=>s.id!=='favorable').map(s=>({...s,weight:s.weight/.9}));
const sensitivities={covariateDays:calculate({anchorDays:5.7}),noFavorable:calculate({worlds:nf}),fullResponse:calculate({worlds:scenarios.map(s=>({...s,cash:1}))}),halfUtility:calculate({worlds:scenarios.map(s=>({...s,utility:s.utility/2}))}),partnerResources:calculate({wholeExpense:inputs.wholeExpense+240*502}),allInKindAdded:calculate({wholeExpense:inputs.wholeExpense+719183}),olderIRSCost:calculate({wholeExpense:3835012})};
for(const[k,v]of Object.entries(sensitivities)){assert.equal(v.weightedBayQalys,saved.sensitivity[k].bayQalys);assert.equal(v.bayCostPer10,saved.sensitivity[k].bayCostPer10);console.log(k,JSON.stringify({bayQalys:v.weightedBayQalys,bayCostPer10:v.bayCostPer10}));}
