import assert from 'node:assert/strict';
import fs from 'node:fs';
import {calculate,diagnostics,modelVersion} from '../lib/hope-calibrated-model.mjs';
import {calculate as frozen} from '../lib/hope-first-health-income-model.mjs';
const c=calculate().centralScenario,d=diagnostics();
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-10*Math.max(1,Math.abs(b)));
close(c.bayCostPer10,931745.122448699);
close(c.healthYears+c.incomeYears,c.totalYears);
close(c.healthAllYears*.95,c.healthYears);
assert.ok(c.incomeYears>0);
close(frozen().centralScenario.bayCostPer10,554659.5517271358);
assert.equal(d.noChange.bayCostPer10,null);
assert.equal(d.noAssignment.bayCostPer10,null);
assert.ok(d.failedInducedAttempt.totalYears<0);
assert.ok(d.incomeCases.nullHealthPositiveIncome.incomeYears>0);
assert.equal(d.incomeCases.nullHealthPositiveIncome.healthYears,0);
assert.ok(d.horizonCases[5].bayCostPer10>c.bayCostPer10);
assert.equal(calculate().rows.length,1);
for(const x of [null,[],false,{worlds:[]},{inputs:{unknown:1}},{gift:1001},{scope:'bad'}])assert.throws(()=>calculate(x));
const r=JSON.parse(fs.readFileSync(new URL('../data/san-francisco/hope-v2-report.json',import.meta.url)));
assert.equal(r.modelVersion,modelVersion);close(r.model.calibration.usdPerBetterLife,c.bayCostPer10);
assert.equal(r.longForm.markdown,fs.readFileSync(new URL('../docs/reports/hope-v2.md',import.meta.url),'utf8'));
assert.ok(r.longForm.markdown.includes('Independent health and income reassessment'));
console.log('Current HOPE arithmetic, geography, counterfactuals, domain, frozen history and report wiring PASS');
