import assert from 'node:assert/strict';
import fs from 'node:fs';
import {calculate,diagnostics,deliveryWorlds} from '../lib/hope-v2-model.mjs';
import {calculate as original} from '../lib/hope-v2-original-model.mjs';
let n=0;const check=f=>{f();n++;};const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-9*Math.max(1,Math.abs(a),Math.abs(b)));
const r=calculate(),old=original(),d=diagnostics(),saved=JSON.parse(fs.readFileSync(new URL('../data/san-francisco/hope-v2-results.json',import.meta.url)));
check(()=>assert.deepEqual(r.rows,old.rows));
for(const k of ['bayQ','allQ','bayCostPer10','allCostPer10','centralScenario','favorableShareOfSignedQ','withoutFavorableBayCostPer10','subjectiveMassBelow1m','subjectiveMassBelow100k'])check(()=>assert.deepEqual(r[k],old[k]));
check(()=>assert.deepEqual(r,saved.evaluated));check(()=>assert.deepEqual(d,saved.diagnostics));
check(()=>assert.equal(r.currentEvidence.listedSites,9));check(()=>assert.equal(r.currentEvidence.annualExpense,null));
const c=r.centralScenario,s=c.inputs,discount=Math.log1p(.03);let q=0;const steps=100000,dt=s.horizon/steps;
for(let i=0;i<steps;i++){const t=(i+.5)*dt,active=Math.min(t,1),post=Math.max(t-1,0),withS=Math.exp(-(s.baseHazard-s.hazardGain)*active-s.postHazard*post),withoutS=Math.exp(-s.baseHazard*active-s.postHazard*post);q+=(withS-withoutS)*Math.exp(-discount*t)*s.utility*dt;}
check(()=>close(q,c.qPerPerson));check(()=>close(c.bayQ,2.5*(q-s.harm)*.95));
check(()=>close(d.centralTemporal.postSupportShareOfGrossSurvival,.9200086916827611));
check(()=>close(d.halfFunding.bayQ,r.bayQ/2));check(()=>assert.deepEqual(d.halfPacks.rows.map(x=>x.bayQ),d.doubleRepeats.rows.map(x=>x.bayQ)));
check(()=>assert.ok(d.horizon1.bayCostPer10>d.horizon2.bayCostPer10));check(()=>assert.ok(d.horizon2.bayCostPer10>d.horizon5.bayCostPer10));
check(()=>assert.equal(c.riskPeople,200));check(()=>assert.equal(c.additionalPeople,2.5));
check(()=>close(d.centralThresholds[0].requiredAnnualRiskPeople/200*c.bayQ,.01));
check(()=>assert.ok(d.centralThresholds[1].requiredFundingResponse>1));
check(()=>assert.equal(calculate({gift:0}).bayQ,0));check(()=>assert.ok(r.rows.some(x=>x.bayQ<0)));check(()=>assert.ok(r.rows.some(x=>x.bayQ===0)));
for(const options of [null,[],42,'bad',{unknown:1},{gift:Infinity},{gift:-1},{gift:1001},{costs:null},{worlds:null},{worlds:[]},{costs:[{id:'x',expense:Number.MIN_VALUE,weight:1}]},{worlds:deliveryWorlds.map(w=>({...w,id:' '}))},{worlds:deliveryWorlds.map(w=>({...w,id:'same'}))},{worlds:deliveryWorlds.map(w=>({...w,id:w.id+' '}))}])check(()=>assert.throws(()=>calculate(options)));
const report=JSON.parse(fs.readFileSync(new URL('../data/san-francisco/hope-v2-report.json',import.meta.url)));check(()=>assert.equal(report.longForm.markdown,fs.readFileSync(new URL('../docs/reports/hope-v2.md',import.meta.url),'utf8')));check(()=>assert.equal(report.longForm.sections.length,8));
for(const row of report.summary)check(()=>assert.ok(['label','value','detail'].every(k=>typeof row[k]==='string')));
for(const row of report.evidence)check(()=>assert.ok(['key','design','population','result','transfer'].every(k=>typeof row[k]==='string')));
check(()=>assert.ok(!JSON.stringify(report.evidence.find(x=>x.key==='distribution')).includes('Five')));
check(()=>assert.equal(new Set(report.sources.map(s=>s.url)).size,report.sources.length));
check(()=>assert.ok(report.longForm.markdown.includes('Eligibility is for locations in San Mateo County')));
check(()=>assert.ok(report.model.fundingBoundary.includes('San Francisco site is not automatically covered')));
console.log(`${n}/${n} checks passed; unchanged original numeric outputs, full saved parity and independent finite integration.`);
