import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {calculate,costWorlds,deliveryWorlds} from '../lib/hope-pacifica-model.mjs';
const saved=JSON.parse(fs.readFileSync(new URL('../data/bay/hope-pacifica-results.json',import.meta.url))),report=JSON.parse(fs.readFileSync(new URL('../data/bay/hope-pacifica-report.json',import.meta.url)));
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-10*Math.max(1,Math.abs(b)),`${a} vs ${b}`);
test('exact full saved default parity',()=>assert.deepEqual(calculate(),saved));
test('18 worlds normalized',()=>{assert.equal(saved.rows.length,18);close(saved.rows.reduce((a,r)=>a+r.weight,0),1);});
test('observed annual finance and cohort remain null',()=>{assert.equal(saved.anchors.observedAnnualExpense,null);assert.equal(saved.anchors.observedAnnualUniqueRiskPeople,null);});
test('independent numerical survival integration',()=>{let q=0,N=100000,dt=10/N;for(let i=0;i<N;i++){let t=(i+.5)*dt,a=t<1?Math.exp(-.068*t):Math.exp(-.068-.07*(t-1)),b=Math.exp(-.07*t);q+=(a-b)*Math.exp(-Math.log(1.03)*t)*.65*dt;}close(saved.centralScenario.qPerPerson,q);});
test('central conversion and whole cost equation',()=>{assert.equal(saved.centralScenario.riskPeople,200);assert.equal(saved.centralScenario.additionalPeople,2.5);close(saved.centralScenario.bayQ,2.5*(.007611190492759633-.00002)*.95);});
test('signed average before inversion',()=>{close(saved.bayQ,saved.rows.reduce((a,r)=>a+r.weight*r.bayQ,0));close(saved.bayCostPer10,10000/saved.bayQ);});
test('nulls exactly zero and harm negative',()=>{for(const r of saved.rows){if(r.deliveryId.endsWith('null'))assert.equal(r.bayQ,0);if(r.deliveryId==='harm'){assert.ok(r.bayQ<0);assert.equal(r.bayCostPer10,null);}}});
test('zero gift finite zero output',()=>{let r=calculate({gift:0});assert.equal(r.bayQ,0);assert.equal(r.bayCostPer10,null);});
test('finite small gift scales only within allowed range',()=>close(calculate({gift:500}).bayQ,saved.bayQ/2));
test('reject unsupported scale',()=>assert.throws(()=>calculate({gift:10000})));
test('reject malformed top level',()=>{for(const x of[null,[],42,'bad'])assert.throws(()=>calculate(x));});
test('reject malformed delivery worlds',()=>{for(const x of[null,[],[null],[42]])assert.throws(()=>calculate({worlds:x}));});
test('reject duplicate identities',()=>assert.throws(()=>calculate({worlds:deliveryWorlds.map(s=>({...s,id:'same'}))})));
test('reject invalid weights',()=>assert.throws(()=>calculate({costs:[{id:'bad',expense:40000,weight:.5}]})));
test('reject invalid inputs including MAX_VALUE',()=>{for(const v of[NaN,Infinity,Number.MAX_VALUE,-1])assert.throws(()=>calculate({worlds:deliveryWorlds.map(s=>({...s,packs:v}))}));});
test('reject derived overflow from tiny cost',()=>assert.throws(()=>calculate({costs:[{id:'tiny',weight:1,expense:Number.MIN_VALUE}]})));
test('reject negative supported hazard',()=>assert.throws(()=>calculate({worlds:deliveryWorlds.map(s=>({...s,hazardGain:.9}))})));
test('signed hazard downside supported',()=>{let r=calculate({worlds:deliveryWorlds.map(s=>({...s,hazardGain:-.001,harm:0}))});assert.ok(r.bayQ<0);assert.equal(r.bayCostPer10,null);});
test('higher repeat packs cannot create more risk people',()=>{let r=calculate({worlds:deliveryWorlds.map(s=>({...s,repeats:s.repeats*2}))});close(r.bayQ,saved.bayQ/2);});
test('higher whole expense halves output',()=>close(calculate({costs:costWorlds.map(c=>({...c,expense:c.expense*2}))}).bayQ,saved.bayQ/2));
test('one-year horizon reduces gain',()=>assert.ok(calculate({worlds:deliveryWorlds.map(s=>({...s,horizon:1}))}).bayQ<saved.bayQ));
test('full renderer field shapes',()=>{const fields=(rows,keys)=>{assert.ok(Array.isArray(rows)&&rows.length);for(const row of rows)for(const k of keys)assert.equal(typeof row[k],'string',k);};fields(report.summary,['label','value','detail']);fields(report.model.inputs,['key','label','confidence','best','range','basis']);fields(report.model.sensitivity,['case','headline','detail']);fields(report.evidence,['key','design','population','result','transfer']);fields(report.sources,['publisher','title','url','published','retrieved','sourceType']);fields(report.programSection.steps,['title','detail']);for(const key of['headline','body','whyItMayWork','whyWeAreCautious','recommendationBlocker'])assert.equal(typeof report.nutshell[key],'string');});
test('report result and mandatory caveats',()=>{assert.ok(report.model.equation.result.includes(String(saved.bayQ)));assert.ok(report.nutshell.body.includes('763,248'));assert.ok(report.nutshell.whyWeAreCautious.includes('65.7%'));assert.equal(report.donationUrl,undefined);assert.ok(report.nutshell.body.includes('not a filing'));});
test('stored sensitivity complete matrices',()=>{const ds=JSON.parse(fs.readFileSync(new URL('../data/bay/hope-pacifica-diagnostics.json',import.meta.url)));assert.equal(Object.keys(ds).length,9);for(const r of Object.values(ds))assert.ok(r.rows.length>=6);});
