import assert from 'node:assert/strict';
import fs from 'node:fs';
import {calculate,scenarios,anchors,discountedYears} from '../lib/marin-county-bicycle-coalition-model.mjs';
const r=calculate(),close=(a,b)=>assert.ok(Math.abs(a-b)<1e-10*Math.max(1,Math.abs(b)));
assert.deepEqual(r,JSON.parse(fs.readFileSync(new URL('../data/bay/marin-county-bicycle-coalition-results.json',import.meta.url))));
close(r.bayCostPer10,28647384.951895792);
const c=r.results.find(x=>x.id==='central');
close(c.baselineAnnualInjuryQ,.1*10+.5*2);
close(c.activityQ,60*.3*.5*.01*.5*.8);
let integral=0,n=100000;for(let i=0;i<n;i++)integral+=(3/n)*(1.03)**(-(4+(i+.5)*3/n));
close(discountedYears(3,4,.03),integral);
close(c.roadQ,2*.2*integral*.25*.5);
close(c.annualBudgetBayQ,(c.roadQ+c.activityQ-.1)*.5*.98);
close(r.weightedGiftBayQ,r.weightedBayQ*10000/anchors.wholeExpense);
assert.equal(discountedYears(3,4,0),3);assert.equal(discountedYears(0,4,.03),0);
assert.ok(discountedYears(3,5,.03)<discountedYears(3,4,.03));
assert.equal(r.results[0].annualBudgetBayQ,0);assert.equal(r.results[1].annualBudgetBayQ,0);assert.ok(r.results[2].annualBudgetBayQ<0);assert.equal(r.results[2].bayCostPer10,null);
assert.ok(r.favorableShare>1);assert.equal(r.probabilityBelow1M,0);
assert.equal(calculate({gift:0}).weightedGiftBayQ,0);
close(calculate({gift:5000}).weightedGiftBayQ,r.weightedGiftBayQ/2);
close(calculate({wholeExpense:anchors.wholeExpense*2}).bayCostPer10,r.bayCostPer10*2);
for(const x of [null,42,'bad',[]])assert.throws(()=>calculate(x));
for(const gift of [-1,10001,Infinity,NaN,'100'])assert.throws(()=>calculate({gift}));
for(const worlds of [[],null,[null],[[]],Array(101).fill(scenarios[0])])assert.throws(()=>calculate({worlds}));
for(const [k,v]of Object.entries({id:' ',weight:-1,fatalPerYear:Infinity,fatalQ:31,seriousQ:11,safetyReduction:2,exposureYears:11,delayYears:16,discount:-1,contribution:1.1,realization:-1,youthScale:4,activityYears:3,funding:2,bay:2,harmQ:-1}))assert.throws(()=>calculate({worlds:[{...scenarios[4],weight:1,[k]:v}]}));
assert.throws(()=>calculate({worlds:[{...scenarios[4],id:'a',weight:.5},{...scenarios[4],id:' a ',weight:.5}]}));
assert.throws(()=>calculate({worlds:[scenarios[4]]}));
const no=scenarios.filter(s=>s.id!=='favorable').map(s=>({...s,weight:s.weight/.9}));assert.equal(calculate({worlds:no}).bayCostPer10,null);
const adverse=calculate({worlds:[{...scenarios[4],weight:1,safetyReduction:-.2,activityUtility:0}]});assert.ok(adverse.weightedBayQ<0);assert.equal(adverse.bayCostPer10,null);
const report=JSON.parse(fs.readFileSync(new URL('../data/bay/marin-county-bicycle-coalition-report.json',import.meta.url)));
assert.equal(report.modelVersion,r.modelVersion);assert.equal(report.organization,'Marin County Bicycle Coalition');
for(const e of report.evidence)for(const k of ['key','design','population','result','transfer'])assert.ok(typeof e[k]==='string'&&e[k].length);
for(const e of report.model.sensitivity)for(const k of ['case','headline','detail'])assert.ok(typeof e[k]==='string'&&e[k].length);
for(const e of report.sources)for(const k of ['publisher','title','url','published','retrieved','sourceType'])assert.ok(typeof e[k]==='string'&&e[k].length);
assert.ok(!report.donationUrl);
console.log('MCBC passed full saved parity, independent numerical integral/pathway math, signed/null, finite/time bounds, malformed inputs, identity/mass, diagnostics and renderer fields.');
