import assert from 'node:assert/strict';
import fs from 'node:fs';
import {calculate,inputs,scenarios} from '../lib/melp-model.mjs';
import test from 'node:test';const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-10*Math.max(1,Math.abs(a),Math.abs(b)),`${a} != ${b}`);
const r=calculate(),central=r.rows.find(x=>x.name==='central');
test('full planning expense and inferred denominator',()=>{near(r.inferredPlanningClientEquivalents,960/.28);near(r.plannedCostPerClientEquivalent,49.370125);assert.notEqual(inputs.plannedWholeOrgExpenseUsd,inputs.historical2024ExpenseUsd);});
test('central independent arithmetic',()=>{const u=(10000/(169269/(960/.28)))*.75*.3*.8;near(central.additionalUniqueRecipients,u);const q=u*(.45*.4*.8*.03*.25+.3*.35*.8*.02*.25+.1*.4*.8*.02*.5+.15*.25*.85*.002*.05-.00015)*.95;near(central.bayQaly,q);});
test('weights prior locked',()=>{assert.deepEqual(scenarios.map(s=>s.weight),[.4,.15,.15,.15,.12,.03]);near(scenarios.reduce((a,s)=>a+s.weight,0),1);});
test('both null mechanisms',()=>{const a=r.rows.find(x=>x.name==='cash_neutral_null'),b=r.rows.find(x=>x.name==='clinical_null');assert.equal(a.additionalUniqueRecipients,0);assert.ok(b.additionalUniqueRecipients>0);assert.equal(a.bayQaly,0);assert.equal(b.bayQaly,0);});
test('signed harms retained including cautious net loss',()=>{for(const name of ['harm','cautious_positive']){const x=r.rows.find(s=>s.name===name);assert.ok(x.bayQaly<0);assert.equal(x.bayDonorCostPer10Qaly,null);}});
test('expected impact averaged not cost ratios',()=>{near(r.weighted.bayQaly,r.rows.reduce((a,s)=>a+s.weight*s.bayQaly,0));near(r.weighted.bayDonorCostPer10Qaly,100000/r.weighted.bayQaly);});
test('no favorable renormalization',()=>{near(r.noFavorable.bayQaly,r.rows.filter(x=>x.name!=='favorable').reduce((a,s)=>a+s.weight*s.bayQaly,0)/.97);});
test('zero gift',()=>{const z=calculate({...inputs,giftUsd:0});assert.equal(z.weighted.bayQaly,0);assert.equal(z.weighted.bayDonorCostPer10Qaly,null);});
test('fees charged to gross gift',()=>{const x=calculate({...inputs,paymentFeeUsd:100});near(x.weighted.bayQaly,r.weighted.bayQaly*.99);near(x.weighted.bayDonorCostPer10Qaly,r.weighted.bayDonorCostPer10Qaly/.99);});
test('unknown complete resources explicit',()=>{assert.equal(r.completeSocietalResourcesUsd,null);assert.equal(r.weighted.completeSocietalCostPer10Qaly,null);const t=calculate({...inputs,externalResourceUsdPerUnique:100});assert.ok(t.rows.find(x=>x.name==='central').resourceSensitivityBayCostPer10Qaly>central.bayDonorCostPer10Qaly);});
test('geographic signed nesting',()=>{for(const s of r.rows){assert.ok(s.sfShare<=s.bayShare);near(s.sfQaly,s.netQaly*s.sfShare);near(s.bayQaly,s.netQaly*s.bayShare);}});
test('exclusive category and finite duration',()=>{for(const s of scenarios){near(s.mix.reduce((a,d)=>a+d.share,0),1);for(const d of s.mix)assert.ok(d.years>=0&&d.years<=1);}});
test('bounded scale rejects100k',()=>assert.throws(()=>calculate({...inputs,giftUsd:100000}),RangeError));
test('invalid probability and duration fail',()=>{assert.throws(()=>calculate({...inputs,statedDistrictClientShare:0}));for(const bad of [NaN,Infinity,-.1,1.1]){const s=structuredClone(scenarios);s[4].cashAdditionality=bad;assert.throws(()=>calculate(inputs,s));}const s=structuredClone(scenarios);s[4].mix[0].years=Infinity;assert.throws(()=>calculate(inputs,s));});
test('bad weights and SF nesting fail',()=>{const a=structuredClone(scenarios);a[0].weight=.5;assert.throws(()=>calculate(inputs,a));const b=structuredClone(scenarios);b[0].sfShare=.99;assert.throws(()=>calculate(inputs,b));});
test('all positive utility removed retains independent harms',()=>{const x=calculate(inputs,scenarios.map(s=>({...s,mix:s.mix.map(d=>({...d,utility:0}))})));assert.ok(x.weighted.bayQaly<0);assert.equal(x.weighted.bayDonorCostPer10Qaly,null);});
test('accepted result parity',()=>{near(r.weighted.bayDonorCostPer10Qaly,3009665.171786541);near(r.weighted.bayQaly,0.033226287408123834);});
test('report result parity',()=>{const x=JSON.parse(fs.readFileSync(new URL('../data/bay/melp-report.json',import.meta.url),'utf8'));assert.equal(x.modelVersion,r.modelVersion);assert.ok(x.nutshell.body.includes('$3,009,665'));assert.ok(x.model.equation.result.includes('$1,725,534'));});
