import assert from 'node:assert/strict';
import fs from 'node:fs';
import {calculate,worlds,trajectory} from '../lib/micahs-hugs-model.mjs';
let checks=0;const test=(name,fn)=>{fn();checks++;};
test('exact full saved parity',()=>assert.deepEqual(calculate(),JSON.parse(fs.readFileSync(new URL('../data/bay/micahs-hugs-results.json',import.meta.url)))));
test('gross cost',()=>assert.equal(calculate().expense,61176+4900));
for(const x of [null,42,'x',[],true])test('malformed options',()=>assert.throws(()=>calculate(x)));
for(const x of [NaN,Infinity,0,-1,Number.MIN_VALUE])test('invalid expense or derived overflow',()=>assert.throws(()=>calculate({expense:x})));
for(const x of [null,[],[null],[{}],{},[...worlds,worlds[0]]])test('malformed worlds',()=>assert.throws(()=>calculate({scenarios:x})));
test('finite missing coefficient',()=>assert.throws(()=>calculate({scenarios:worlds.map((s,i)=>i?{...s}:{...s,horizon:undefined})})));
test('blank ids',()=>assert.throws(()=>calculate({scenarios:worlds.map((s,i)=>i?{...s}:{...s,id:' '})})));
test('gift cap',()=>assert.throws(()=>calculate({gift:10001})));
test('zero gift',()=>{const r=calculate({gift:0});assert.equal(r.bayQ,0);assert.equal(r.bayCostPer10,null)});
test('no doses',()=>assert.equal(calculate({doses:0}).bayQ,0));
test('signed harm and null',()=>{let r=calculate();assert.ok(r.rows.find(s=>s.id==='harm').bayQ<0);for(const id of ['funding_null','clinical_null'])assert.equal(r.rows.find(s=>s.id===id).bayQ,0)});
test('coverage dedup',()=>assert.equal(calculate().rows[4].uniqueRiskPeople,131.25));
test('linear bounded gift',()=>assert.equal(calculate({gift:5000}).bayQ,calculate().bayQ/2));
test('finite individual bound',()=>{for(const s of worlds)assert.ok(Math.abs(trajectory(s))<=s.utility*s.horizon)});
test('independent numerical survival integration',()=>{for(const s of worlds){let sum=0,dt=s.horizon/100000;for(let i=0;i<100000;i++){let t=(i+.5)*dt,withS=t<=1?Math.exp(-(s.baselineHazard-s.hazardGain)*t):Math.exp(-(s.baselineHazard-s.hazardGain))*Math.exp(-s.postHazard*(t-1)),withoutS=t<=1?Math.exp(-s.baselineHazard*t):Math.exp(-s.baselineHazard)*Math.exp(-s.postHazard*(t-1));sum+=(withS-withoutS)*s.utility/(1.03**t)*dt}assert.ok(Math.abs(sum-trajectory(s))<1e-9)}});
test('one person not repeated lives',()=>{const s={...worlds[4],weight:1,unitsPerCarrier:1000,dedup:1,stationShare:1,stationReach:1};let r=calculate({doses:1000,scenarios:[s]});assert.equal(r.rows[0].uniqueRiskPeople,1);assert.ok(r.rows[0].allQ<=10000/66076*s.funding*s.utility*s.horizon)});
test('all null average',()=>{let r=calculate({scenarios:worlds.map(s=>({...s,hazardGain:0,harm:0}))});assert.equal(r.bayQ,0);assert.equal(r.bayCostPer10,null);assert.equal(r.favorableShare,null)});
test('saved sensitivities exact',()=>{let saved=JSON.parse(fs.readFileSync(new URL('../data/bay/micahs-hugs-sensitivity.json',import.meta.url)));for(let x of saved){let r=x.result;assert.deepEqual(calculate({gift:r.gift,expense:r.expense,doses:r.doses,scenarios:r.rows.map(({id,weight,unitsPerCarrier,stationShare,stationReach,schoolReach,dedup,hazardGain,baselineHazard,postHazard,horizon,utility,funding,bay,harm})=>({id,weight,unitsPerCarrier,stationShare,stationReach,schoolReach,dedup,hazardGain,baselineHazard,postHazard,horizon,utility,funding,bay,harm}))}),r)}});
test('standalone trajectory guards',()=>{for(const s of [null,{},[],{...worlds[4],utility:NaN}])assert.throws(()=>trajectory(s))});
test('renderer canonical shape and numerical headline',()=>{const r=JSON.parse(fs.readFileSync(new URL('../data/bay/micahs-hugs-report.json',import.meta.url)));for(const x of r.evidence)for(const k of ['key','design','population','result','transfer'])assert.ok(typeof x[k]==='string'&&x[k]);assert.equal(r.modelVersion,calculate().modelVersion);assert.ok(r.model.equation.result.includes(String(calculate().bayQ)));assert.equal(r.donationUrl,'https://micahshugs.org/donate/');assert.ok(r.sources.every(s=>s.url.startsWith('https://')&&s.publisher&&s.title));});
test('renderer summary objects',()=>{const r=JSON.parse(fs.readFileSync(new URL('../data/bay/micahs-hugs-report.json',import.meta.url)));for(const x of r.summary)for(const k of ['label','value','detail'])assert.ok(typeof x[k]==='string'&&x[k]);});
console.log(JSON.stringify({checks,pass:true,price:calculate().bayCostPer10}));
