import fs from 'node:fs';import assert from 'node:assert/strict';import{calculate,inputsFor,BOUNDS,finiteYears,crcGain,symptomGain}from'../lib/oa-portfolio-model.mjs';
const m=JSON.parse(fs.readFileSync(new URL('../data/san-francisco/oa-portfolio-model-v1.json',import.meta.url)));let checks=0;const ok=v=>{assert.ok(v);checks++;},near=(x,y,t=1e-8)=>ok(Math.abs(x-y)<=t*Math.max(1,Math.abs(y)));
function independentCRC(p){let q=0;const n=50000,h=p.crc_horizon_years/n;for(let i=0;i<n;i++){const t=(i+.5)*h,a=Math.min(Math.max(0,t-p.crc_latency_years),p.crc_active_years),k=p.crc_catchup_hazard,z=p.crc_annual_fatal_hazard_reduction*Math.exp(-k*p.crc_latency_years)*(k? (1-Math.exp(-k*a))/k:a);q+=(Math.exp(-p.crc_baseline_total_mortality_hazard*t+z)-Math.exp(-p.crc_baseline_total_mortality_hazard*t))*Math.pow(1+p.discount,-t)*h;}return q*p.crc_treatment_linkage*p.crc_surviving_utility*Math.pow(1+p.discount,-p.crc_delay_years);}
for(const s of m.scenarios){const p=inputsFor(m,s),r=calculate(p);near(crcGain(p),independentCRC(p));near(r.us_q,r.eye_net_q+r.hernia_net_q+r.crc_net_q-p.independent_harm_q);near(r.sf_q,p.sf_share*r.us_q);near(r.bay_q,p.bay_share*r.us_q);near(r.gross_resource_usd,p.gift_usd+r.external_clinical_resource_usd+r.external_support_usd+r.patient_time_usd+r.crc_downstream_resource_usd);ok(r.additional_services<=p.max_additional_services);for(const g of['us','bay','sf'])for(const k of['donor','resource']){const price=r[k+'_'+g+'_per_10q'];if(r[g+'_q']>0)near(price,10*(k==='donor'?p.gift_usd:r.gross_resource_usd)/r[g+'_q']);else ok(price===null);}}
for(const[k,[lo,hi]]of Object.entries(BOUNDS)){const p={...m.central_inputs};delete p[k];assert.throws(()=>calculate(p));checks++;for(const v of[NaN,Infinity,-Infinity,lo-1,hi+1]){assert.throws(()=>calculate({...m.central_inputs,[k]:v}));checks++;}}
for(const extra of[{eye_allocation:.5},{sf_share:.9,bay_share:.1},{crc_baseline_total_mortality_hazard:0,crc_annual_fatal_hazard_reduction:.001}]){assert.throws(()=>calculate({...m.central_inputs,...extra}));checks++;}
let seed=892;const rand=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/4294967296);for(let i=0;i<1000;i++){const p={...m.central_inputs,crc_annual_fatal_hazard_reduction:(rand()-.5)*.02,crc_baseline_total_mortality_hazard:.02+rand()*.98,crc_catchup_hazard:rand()*10,crc_latency_years:rand()*10,crc_active_years:rand()*10,crc_horizon_years:rand()*30,discount:rand(),crc_treatment_linkage:rand(),crc_surviving_utility:rand(),eye_utility_gain:rand()*2-1,hernia_utility_gain:rand()*2-1};const r=calculate(p);ok(Number.isFinite(r.us_q));ok(Math.abs(r.crc_gross_q_per_person)<=p.crc_horizon_years);if(i<100)near(crcGain(p),independentCRC(p),2e-7);}
const zero=calculate({...m.central_inputs,funding_additionality:0,independent_harm_q:1});ok(zero.us_q===-1);ok(zero.donor_us_per_10q===null);ok(zero.gross_resource_usd>m.central_inputs.gift_usd);near(finiteYears(0,3),3);ok(crcGain({...m.central_inputs,crc_annual_fatal_hazard_reduction:1e-14})>0);for(const k of['eye','hernia'])near(symptomGain({...m.central_inputs,[k+'_horizon_years']:0},k),0);
const f=m.finance;ok(f.total_accrual_expense-f.donated_clinical_waived_charges-f.other_donated_support===f.cash_like_expense);ok(Object.values(f.specialty_services).reduce((a,b)=>a+b,0)===1529);console.log(JSON.stringify({status:'PASS',scenarios:m.scenarios.length,checks}));
