import assert from 'node:assert/strict';import fs from 'node:fs';import{calculate,scenarios}from'../lib/oakland-lgbtq-community-center-model.mjs';
const read=n=>JSON.parse(fs.readFileSync(new URL(n,import.meta.url)));let checks=0;const test=(n,f)=>{f();checks++;};
test('exact full snapshot',()=>assert.deepEqual(calculate(),read('../data/bay/oakland-lgbtq-community-center-results.json')));
for(const v of[null,[],true,42,'x'])test('options',()=>assert.throws(()=>calculate(v)));
for(const v of[0,-1,NaN,Infinity,Number.MIN_VALUE])test('expense',()=>assert.throws(()=>calculate({expense:v})));
for(const v of[null,[],{},[null],[{}]])test('worlds',()=>assert.throws(()=>calculate({worlds:v})));
test('duplicate ids',()=>assert.throws(()=>calculate({worlds:[{...scenarios[4],weight:.5},{...scenarios[4],id:' central ',weight:.5}]})));
test('blank id',()=>assert.throws(()=>calculate({worlds:scenarios.map((s,i)=>i?s:{...s,id:' '})})));
test('missing coefficient',()=>assert.throws(()=>calculate({worlds:scenarios.map((s,i)=>i?s:{...s,risk:undefined})})));
test('invalid weights',()=>assert.throws(()=>calculate({worlds:[{...scenarios[4],weight:.9}]})));
test('bounded gift',()=>{assert.throws(()=>calculate({gift:10001}));assert.equal(calculate({gift:0}).giftBayQ,0);assert.equal(calculate({gift:5000}).giftBayQ,calculate().giftBayQ/2)});
test('zero clinical cohort',()=>assert.equal(calculate({tested:0}).annualBayQ,0));
test('null',()=>{const r=calculate({worlds:scenarios.map(s=>({...s,hivUtility:0,artUtility:0,stiUtility:0,harm:0}))});assert.equal(r.annualBayQ,0);assert.equal(r.bayCostPer10,null)});
test('harm remains signed',()=>{const r=calculate({worlds:[{...scenarios[2],weight:1}]});assert.ok(r.annualBayQ<0);assert.equal(r.bayCostPer10,null)});
test('positive HIV excludes PrEP',()=>assert.equal(calculate({worlds:[{...scenarios[4],positive:1,weight:1}]}).rows[0].prepStarts,0));
test('no protected time no prevented infections',()=>assert.equal(calculate({worlds:[{...scenarios[4],prepYears:0,weight:1}]}).rows[0].prevented,0));
test('independent central arithmetic',()=>{const s=calculate().rows[4],n=1046*.8,p=n*.99*.2*.5*.015*.9*.4*.1*10,a=n*.01*.7*.5*.05*.5,t=n*.2*.8*.3*.5*.1*.02,q=(p+a+t-n*.00005)*.5*.4*.98;assert.ok(Math.abs(q-s.annualBayQ)<1e-12);assert.equal(s.people,n)});
test('weighted before inversion',()=>{const r=calculate(),q=r.rows.reduce((a,s)=>a+s.weight*s.annualBayQ,0);assert.equal(r.bayCostPer10,10*4957230/q)});
test('diagnostics full parity',()=>{for(const d of read('../data/bay/oakland-lgbtq-community-center-diagnostics.json'))assert.deepEqual(calculate({expense:d.result.expense,gift:d.result.gift,tested:d.result.tested,worlds:d.result.rows}),d.result)});
test('recursive finite outputs',()=>{const walk=x=>{if(typeof x==='number')assert.ok(Number.isFinite(x));if(x&&typeof x==='object')Object.values(x).forEach(walk)};walk(calculate())});
test('renderer',()=>{const r=read('../data/bay/oakland-lgbtq-community-center-report.json');assert.equal(r.modelVersion,calculate().modelVersion);assert.ok(r.model.equation.result.includes(String(calculate().giftBayQ)));for(const x of r.summary)for(const k of['label','value','detail'])assert.ok(typeof x[k]==='string'&&x[k]);for(const x of r.evidence)for(const k of['key','design','population','result','transfer'])assert.ok(typeof x[k]==='string'&&x[k]);for(const k of Object.keys(scenarios[4]).filter(k=>!['id','weight'].includes(k)))assert.ok(r.model.inputs.some(x=>x.key===k),k);assert.ok(!('donationUrl'in r));});
console.log(JSON.stringify({checks,pass:true,price:calculate().bayCostPer10}));
