import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{calculate,anchors,scenarios}from'../lib/pacific-hearing-connection-model.mjs';
const r=calculate(),near=(x,y)=>assert.ok(Math.abs(x-y)<1e-12);
test('exact first saved output',()=>assert.deepEqual(r,JSON.parse(fs.readFileSync('data/bay/pacific-hearing-connection-results.json'))));
test('whole expense unchanged',()=>{assert.equal(r.expense,184099);assert.equal(anchors.expense,r.expense)});
test('immutable first-run numeric anchors',()=>{assert.equal(r.bayQ,.1066415352609194);assert.equal(r.bayCostPer10,937720.9335493005)});
test('six worlds weights',()=>{assert.equal(r.rows.length,6);near(r.rows.reduce((a,s)=>a+s.weight,0),1)});
test('funding null',()=>assert.equal(r.rows[0].bayQ,0));
test('clinical null',()=>assert.equal(r.rows[1].bayQ,0));
test('signed harmful world',()=>assert.ok(r.rows[2].bayQ<0));
test('expectation before ratio',()=>near(r.bayCostPer10,100000/r.rows.reduce((a,s)=>a+s.weight*s.bayQ,0)));
test('central exact scalar',()=>near(r.rows[4].bayQ,10000/184099*75*.5*(.12*.5*.8*.5-.0005)*.95));
test('finite duration max2',()=>assert.ok(scenarios.every(s=>s.years<=2)));
test('zero gift',()=>{const z=calculate({gift:0});assert.equal(z.bayQ,0);assert.equal(z.bayCostPer10,null)});
test('gift cap',()=>assert.throws(()=>calculate({gift:100000}),RangeError));
test('half gift linear diagnostic',()=>near(calculate({gift:5000}).bayQ,r.bayQ/2));
test('malformed options',()=>{for(const o of[null,[],42,'x',true])assert.throws(()=>calculate(o),TypeError);assert.deepEqual(calculate(undefined),r)});
test('malformed worlds',()=>{for(const worlds of[[],null,{},[null],[[]]])assert.throws(()=>calculate({worlds}))});
test('duplicate ids',()=>assert.throws(()=>calculate({worlds:scenarios.map(s=>({...s,id:'same'}))}),TypeError));
test('bad finite coefficient',()=>assert.throws(()=>calculate({worlds:scenarios.map(s=>({...s,courses:Number.MAX_VALUE}))}),RangeError));
test('derived overflow',()=>assert.throws(()=>calculate({expense:Number.MIN_VALUE}),RangeError));
test('bad weights',()=>assert.throws(()=>calculate({worlds:scenarios.map(s=>({...s,weight:0}))}),RangeError));
test('undefined complete resource cost',()=>assert.equal(r.completeResourceCostPer10,null));
test('schema arrays and clinical evidence',()=>{const p=JSON.parse(fs.readFileSync('data/bay/pacific-hearing-connection-report.json'));for(const a of[p.summary,p.programSection.steps,p.model.inputs,p.model.sensitivity,p.evidence,p.reservations,p.excludedBenefits,p.sources])assert.ok(Array.isArray(a)&&a.length);assert.ok(p.model.sensitivity.every(s=>s.case&&s.headline&&s.detail));assert.ok(p.evidence.every(e=>['key','design','population','result','transfer'].every(k=>typeof e[k]==='string')))});
