import assert from 'node:assert/strict';import {readFileSync}from'node:fs';
import {central,scenarios,calculate,runScenarios}from'../lib/pvf-portfolio-model.mjs';
let checks=0;const ok=x=>{assert.ok(x);checks++;},near=(a,b)=>ok(Math.abs(a-b)<=1e-9*Math.max(1,Math.abs(b)));
const results=runScenarios();
for(const [name,r]of Object.entries(results)){let p={...central,...scenarios[name]};near(r.courses*p.course_cash,p.gift*p.first_eye_allocation);ok(r.added_courses<=r.courses);near(r.benefit,r.added_courses*p.trial_q*p.clinical_timing_transfer);ok(Math.abs(r.benefit)<=r.added_courses+1e-9);near(r.loss,r.added_courses*p.shared_harm_q+p.independent_harm_q+p.displaced_alternative_q);near(r.net_resources,p.gift+r.added_courses*(p.public_outside_per_course+p.private_outside_per_course-p.counterfactual_outside_per_course*Math.exp(-p.resource_discount*p.resource_wait_years))-p.other_real_savings);for(const g of['us','bay','sf'])for(const[k,c]of[['donor',p.gift],['gross',r.gross_resources],['net',r.net_resources]]){if(r.q[g]>0)near(r.prices[g][k]*r.q[g],c*10);else ok(r.prices[g][k]===null);}}
near(results.central.q.us,0.14);near(results.central.q.sf,0.056);near(results.central.net_resources,100369.43083064364);
near(results.replacement_only.q.us,0);near(results.no_timing_advantage.q.us,0);near(results.target_failure_displaces_alternative.q.us,-1);near(results.independent_harm_no_activity.q.us,-0.2);ok(results.shared_extra_harm.q.us<0);ok(results.negative_clinical_transfer.q.us<0);ok(results.net_saving_diagnostic.net_resources<0&&results.net_saving_diagnostic.prices.us.net<0);
const old=calculate({...central,first_eye_allocation:1,sf_share:1,bay_share:1});near(old.prices.sf.donor,714285.7142857143);near(old.prices.sf.gross,2500000);
for(const k of Object.keys(central)){let p={...central};delete p[k];assert.throws(()=>calculate(p));checks++;for(const v of[NaN,Infinity,-Infinity]){assert.throws(()=>calculate({...central,[k]:v}));checks++;}}
for(const p of[{gift:0},{course_cash:0},{trial_q:1.1},{sf_share:1},{funding_additionality:2},{resource_wait_years:11},{trial_q:-1,clinical_timing_transfer:-1},{first_eye_allocation:1e-310}]){assert.throws(()=>calculate({...central,...p}));checks++;}
let seed=271828;const rand=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;};for(let i=0;i<1000;i++){const p={...central,gift:1+1e8*rand(),first_eye_allocation:rand(),course_cash:1+1e6*rand(),trial_q:rand(),clinical_timing_transfer:2*rand()-1,funding_additionality:rand(),shared_harm_q:rand(),independent_harm_q:rand()*100,displaced_alternative_q:rand()*100,public_outside_per_course:rand()*1e6,private_outside_per_course:rand()*1e6,counterfactual_outside_per_course:rand()*1e6,resource_wait_years:10*rand(),resource_discount:0.2*rand(),other_real_savings:1e8*(2*rand()-1)};const r=calculate(p);ok(Number.isFinite(r.net_resources)&&Number.isFinite(r.q.us));near(r.q.us,r.added_courses*(p.trial_q*p.clinical_timing_transfer-p.shared_harm_q)-p.independent_harm_q-p.displaced_alternative_q);ok(Math.abs(r.benefit)<=r.added_courses+1e-8);}
const read=s=>JSON.parse(readFileSync(new URL('../data/san-francisco/pvf-portfolio-'+({'model.json':'model-v1.json','report-content.json':'report.json'}[s]||s),import.meta.url)));const m=read('model.json'),r=read('report-content.json');assert.deepEqual(read('results.json'),results);assert.deepEqual(m.results,results);assert.deepEqual(m.central,central);checks+=3;
const strings=(o,keys)=>{for(const k of keys){ok(typeof o[k]==='string'&&o[k].length>0);}};
strings(r,['organization','eyebrow','program','published','modelVersion']);strings(r.nutshell,['headline','body','whyItMayWork','whyWeAreCautious','recommendationBlocker']);strings(r.programSection,['body','boundary']);for(const s of r.programSection.steps)strings(s,['title','detail']);for(const s of r.summary)strings(s,['label','value','detail']);strings(r.model,['headline','body','giftHeading','fundingBoundary']);strings(r.model.equation,['label','expression','result']);for(const i of r.model.inputs)strings(i,['key','label','confidence','best','range','basis']);for(const i of r.evidence)strings(i,['key','design','population','result','transfer']);for(const i of r.sources)strings(i,['title','publisher','url','published','retrieved','sourceType']);for(const key of['reservations','excludedBenefits'])ok(Array.isArray(r[key])&&r[key].every(s=>typeof s==='string'&&s.length));
const money=v=>v===null?'No finite positive-health ratio':'$'+Math.round(v).toLocaleString('en-US'),num=v=>Number(v.toPrecision(8)).toString();
for(const[k,v]of Object.entries(results)){const row=r.model.sensitivity.find(s=>s.case===k);strings(row,['case','headline','detail']);for(const geo of['us','bay','sf']){ok(row.detail.includes(num(v.q[geo])));for(const type of['donor','gross','net'])ok(row.detail.includes(money(v.prices[geo][type])));}}
const f=m.finance;near(f.program+f.management+f.fundraising,f.functionalExpense);near(f.revenueNet+f.rentalExpenseNetted,f.grossRevenueArithmetic);near(f.functionalExpense+f.rentalExpenseNetted,f.grossExpenseArithmetic);near(f.assets-f.liabilities,f.unrestrictedNetAssets+f.restrictedNetAssets);near(Object.values(m.allocationLedger).reduce((a,b)=>a+b,0),1);
console.log(JSON.stringify({status:'PASS',scenarios:Object.keys(results).length,checks,central:results.central},null,2));
