import assert from 'node:assert/strict';import fs from 'node:fs';
import{calculate,scenarios}from'../lib/rainbow-community-center-model.mjs';
let checks=0;const test=(n,f)=>{f();checks++;};const read=n=>JSON.parse(fs.readFileSync(new URL(n,import.meta.url)));
test('full exact snapshot',()=>assert.deepEqual(calculate(),read('../data/bay/rainbow-community-center-results.json')));
for(const v of [null,1,'x',[],true])test('bad options',()=>assert.throws(()=>calculate(v)));
for(const v of [NaN,Infinity,0,Number.MIN_VALUE,-1])test('expense guards',()=>assert.throws(()=>calculate({expense:v})));
for(const v of [null,[],{},[null],[{}]])test('world guards',()=>assert.throws(()=>calculate({worlds:v})));
test('duplicate and blank ids',()=>{assert.throws(()=>calculate({worlds:[...scenarios,scenarios[0]]}));assert.throws(()=>calculate({worlds:scenarios.map((s,i)=>i?s:{...s,id:' '})}));});
test('missing coefficient',()=>assert.throws(()=>calculate({worlds:scenarios.map((s,i)=>i?s:{...s,duration:undefined})})));
test('weight normalization',()=>assert.throws(()=>calculate({worlds:[{...scenarios[4],weight:.9}]})));
test('all null',()=>{const r=calculate({worlds:scenarios.map(s=>({...s,utilityGain:0,harm:0}))});assert.equal(r.bayCostPer10,null);assert.equal(r.annualBayQ,0)});
test('negative clinical effect retained',()=>assert.ok(calculate({worlds:[{...scenarios[4],weight:1,utilityGain:-.01}]}).annualBayQ<0));
test('zero gift and cap',()=>{assert.equal(calculate({gift:0}).giftBayQ,0);assert.throws(()=>calculate({gift:10001}));});
test('no clinical delivery no clinical impact',()=>assert.equal(calculate({worlds:scenarios.map(s=>({...s,clinicians:0}))}).annualBayQ,0));
test('independent central equation',()=>{const r=calculate().rows[4];assert.equal(r.sessions,1600);assert.equal(r.starters,144);assert.ok(Math.abs(r.completed-100.8)<1e-12);const q=(100.8*.06*.5*.65*.5-144*.001)*.4*.98;assert.ok(Math.abs(q-r.annualBayQ)<1e-12)});
test('harm includes noncompletion',()=>{const r=calculate({worlds:[{...scenarios[4],weight:1,completion:0}]});assert.ok(r.annualBayQ<0)});
test('finite per-course effect',()=>{for(const r of calculate().rows)assert.ok(Math.abs(r.qPerComplete)<=.5*r.duration)});
test('half gift exact',()=>assert.equal(calculate({gift:5000}).giftBayQ,calculate().giftBayQ/2));
test('saved diagnostics exact',()=>{for(const x of read('../data/bay/rainbow-community-center-diagnostics.json'))assert.deepEqual(calculate({expense:x.result.expense,gift:x.result.gift,worlds:x.result.rows}),x.result)});
test('canonical renderer',()=>{const r=read('../data/bay/rainbow-community-center-report.json');assert.equal(r.modelVersion,calculate().modelVersion);assert.ok(r.model.equation.result.includes(String(calculate().giftBayQ)));for(const x of r.summary)for(const k of ['label','value','detail'])assert.ok(typeof x[k]==='string'&&x[k]);for(const x of r.evidence)for(const k of ['key','design','population','result','transfer'])assert.ok(typeof x[k]==='string'&&x[k]);assert.ok(!('donationUrl'in r));assert.ok(r.sources.every(x=>x.url.startsWith('https://')&&x.publisher&&x.title));});
console.log(JSON.stringify({checks,pass:true,price:calculate().bayCostPer10}));
