import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import{calculate,inputs,scenarios}from'../lib/season-of-sharing-model.mjs';
const r=calculate(),near=(a,b)=>assert.ok(Math.abs(a-b)<1e-10);
test('six signed worlds',()=>assert.equal(r.rows.length,6));
test('malformed top-level options rejected',()=>{for(const x of[42,'bad',[],null,true])assert.throws(()=>calculate(x),TypeError);assert.deepEqual(calculate(undefined),r)});
test('whole cash and resource expenses reconcile',()=>assert.equal(inputs.auditedResourceExpense-inputs.wholeExpense,330881));
test('weights sum one',()=>near(scenarios.reduce((a,s)=>a+s.weight,0),1));
test('funding null',()=>assert.equal(r.rows[0].bayQalys,0));
test('health null retains housing but no health',()=>{assert.ok(r.rows[1].avoidedHomelessness>0);assert.equal(r.rows[1].bayQalys,0)});
test('harm negative',()=>assert.ok(r.rows[2].bayQalys<0));
test('expectation before ratio',()=>near(r.bayCostPer10,100000/r.rows.reduce((a,s)=>a+s.weight*s.bayQalys,0)));
test('food retained in cost not output',()=>assert.ok(inputs.foodCash>0&&!('foodQalys'in r)));
test('exact saved result',()=>assert.deepEqual(r,JSON.parse(fs.readFileSync('data/bay/season-of-sharing-results.json'))));
test('half gift',()=>near(calculate({gift:5000}).weightedBayQalys,r.weightedBayQalys/2));
test('large gift rejected',()=>assert.throws(()=>calculate({gift:100000}),RangeError));
test('tiny cost rejects derived overflow',()=>assert.throws(()=>calculate({wholeExpense:Number.MIN_VALUE}),RangeError));
test('malformed worlds rejected',()=>{for(const worlds of [[],null,{},[null]])assert.throws(()=>calculate({worlds}))});
test('duplicateids rejected',()=>assert.throws(()=>calculate({worlds:scenarios.map(s=>({...s,id:'x'}))}),TypeError));
test('bad coefficient rejected',()=>assert.throws(()=>calculate({worlds:scenarios.map(s=>({...s,utility:NaN}))}),RangeError));
test('finite duration',()=>assert.ok(scenarios.every(s=>s.years<=1)));
test('exact Bay scalar central',()=>near(r.rows[4].bayQalys,r.rows[4].allQalys*.99));
test('renderer arrays and sensitivity shape',()=>{const p=JSON.parse(fs.readFileSync('data/bay/season-of-sharing-report.json'));for(const a of[p.summary,p.programSection.steps,p.model.inputs,p.model.sensitivity,p.evidence,p.reservations,p.excludedBenefits,p.sources])assert.ok(Array.isArray(a)&&a.length);assert.ok(p.model.sensitivity.every(s=>s.case&&s.headline&&s.detail));});
