import assert from 'node:assert/strict';
import fs from 'node:fs';
import {calculate,worlds,expense} from '../lib/sogorea-te-model.mjs';
let checks=0;const check=f=>{f();checks++;};
const r=calculate();
check(()=>assert.deepEqual(r,JSON.parse(fs.readFileSync(new URL('../data/bay/sogorea-te-results.json',import.meta.url)))));
check(()=>assert.equal(r.wholeExpense,2841731));
check(()=>assert.ok(Math.abs(r.rows[2].wholeQ-4*100*.05*.2*.003*.2*1*.2)<1e-15));
check(()=>assert.ok(r.rows[0].wholeQ<0));
check(()=>assert.equal(r.rows[1].wholeQ,0));
check(()=>assert.equal(calculate({gift:0}).giftQ,0));
check(()=>assert.equal(calculate({wholeExpense:expense*2}).perDollar,r.perDollar/2));
check(()=>assert.equal(calculate({hubs:0}).costPer10,null));
for(const options of [null,42,'bad',[],{wholeExpense:0},{wholeExpense:Number.MIN_VALUE},{gift:Infinity},{hubs:-1},{scenarios:[]},{scenarios:[null]},{scenarios:[{...worlds[0],id:' '}]},{scenarios:[{...worlds[0],id:' x '},{...worlds[1],id:'x'}]},{scenarios:worlds.map(w=>({...w,weight:1}))},{scenarios:worlds.map(w=>({...w,years:Infinity}))},{scenarios:worlds.map(w=>({...w,arr:2}))}])check(()=>assert.throws(()=>calculate(options)));
const report=JSON.parse(fs.readFileSync(new URL('../data/bay/sogorea-te-report.json',import.meta.url)));
check(()=>assert.ok(report.summary.every(x=>['label','value','detail'].every(k=>typeof x[k]==='string'))));
check(()=>assert.ok(report.model.sensitivity.every(x=>['case','headline','detail'].every(k=>typeof x[k]==='string'))));
check(()=>assert.ok(report.evidence.every(x=>['key','design','population','result','transfer'].every(k=>typeof x[k]==='string'))));
check(()=>assert.ok(report.sources.every(x=>['publisher','title','url','published','retrieved','sourceType'].every(k=>typeof x[k]==='string'))));
console.log(`${checks}/${checks} checks passed; exact full saved parity.`);
