import assert from 'node:assert/strict';import fs from 'node:fs';import {calculate,bounds,integral,annuity} from '../lib/via-heart-model.mjs';
const m=JSON.parse(fs.readFileSync(new URL('../data/bay/via-heart-model-v1.json',import.meta.url))),r=JSON.parse(fs.readFileSync(new URL('../data/bay/via-heart-results.json',import.meta.url))),report=JSON.parse(fs.readFileSync(new URL('../data/bay/via-heart-report.json',import.meta.url)));let checks=0;function ok(x){assert.ok(x);checks++;}
for(const [id,v]of Object.entries(m.scenarios)){const p={...m.central,...v},o=calculate(p);assert.deepEqual(o,r[id]);checks++;ok(report.model.sensitivity.some(s=>s.case===id));for(const region of ['total','us','bay','sf'])for(const c of ['donor','gross','net'])ok(o.q[region]>0?Math.abs(o.prices[region][c]-10*(c==='donor'?p.gift:o.costs[c])/o.q[region])<1e-6:o.prices[region][c]===null);for(const b of ['new','maintenance']){ok(o.branches[b].firstEvents<=o.branches[b].distinct+1e-12);ok(Math.abs(o.branches[b].q)<=o.branches[b].distinct*p.horizon+1e-9);}}
for(const k of Object.keys(bounds)){const p={...m.central};delete p[k];assert.throws(()=>calculate(p));checks++;for(const x of [NaN,Infinity,-Infinity]){assert.throws(()=>calculate({...m.central,[k]:x}));checks++;}}
assert.throws(()=>calculate({...m.central,new_active:5.01}));checks++;assert.throws(()=>calculate({...m.central,maintenance_active:1.01}));checks++;
for(let i=1;i<=150;i++){const p={...m.central,new_hazard:(i%31)/31,maintenance_hazard:(i%23)/23,horizon:(i%30),mortality:(i%17)/17,discount:(i%11)/11,new_increment:(i%10)/10-.3,maintenance_increment:(i%10)/10-.85,new_active:(i%51)/10,maintenance_active:(i%11)/10};calculate(p);for(const b of ['new','maintenance']){const T=Math.min(p[b+'_active'],p.horizon),n=20000,dt=T/n;let sum=0;for(let j=0;j<n;j++){const t=(j+.5)*dt;sum+=p[b+'_hazard']*Math.exp(-(p[b+'_hazard']+p.discount)*t)*annuity(p.mortality+p.discount,p.horizon-t)*dt;}ok(Math.abs(integral(p[b+'_hazard'],p[b+'_active'],p.horizon,p.mortality,p.discount)-sum)<1e-6);}}
for(const k of ['organization','eyebrow','program','published','modelVersion'])ok(typeof report[k]==='string');for(const k of ['summary','evidence','reservations','excludedBenefits','sources'])ok(Array.isArray(report[k]));for(const s of report.sources)for(const k of ['publisher','title','url','published','retrieved','sourceType'])ok(typeof s[k]==='string'&&s[k].length>0);ok(report.model.giftHeading.length>0);ok(report.model.inputs.length===Object.keys(m.central).length);
ok(r.target_failure_alternative_loss.q.total===-1);ok(r.no_local_health.prices.bay.donor===null);ok(r.signed_resource_savings.prices.total.net<0);
console.log(JSON.stringify({status:'PASS',scenarios:Object.keys(m.scenarios).length,checks,numericalCases:150}));
