import type {Metadata} from 'next';
import CharityResearchReport,{type CharityReportContent} from '@/components/CharityResearchReport';
import data from '@/data/san-francisco/pvf-cataract-cea-v1.json';
import {cataractAccessModel} from '@/lib/surgical-access-model.mjs';
export const metadata:Metadata={title:'Pacific Vision Foundation — cataract access | Market for Impact',description:'A conditional first-eye cataract model with explicit donor costs, a one-year randomized health anchor and uncertain additionality.'};
const money=(n:number|null)=>n===null?'No finite positive price':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2}).format(n);
const central=data.coreScenarios.find(s=>s.id==='central')!;
const r=cataractAccessModel(central.inputs);
const core=data.coreScenarios.map(s=>({...s,calculated:cataractAccessModel(s.inputs)}));
const separate=data.separateScenarios.map(s=>({...s,calculated:cataractAccessModel(s.inputs)}));
const content:CharityReportContent={
 organization:data.organization.name,program:'Earlier first-eye cataract surgery through the shared PVF/Lions pathway',eyebrow:'SAN FRANCISCO · CONDITIONAL RESEARCH',published:'8 September 2026',modelVersion:data.modelId,donationUrl:data.organization.donationUrl,
 nutshell:{headline:'Restoring sight is valuable. The key question is how much earlier a donation makes care happen.',
 body:<>Our provisional best estimate is <strong>{money(r.costPerTenQalys)} per better life—10 incremental QALYs</strong>. We model an eligible uninsured SF resident receiving earlier first-eye surgery, not the effectiveness of every Pacific Vision activity. The health anchor is randomized; local costs, timing and financing are judgments. <a href="/api/sf-surgical-access-models">Inspect the model and sources →</a></>,
 whyItMayWork:'A small cash contribution could unlock donated clinical capacity and shorten a meaningful period of impaired sight.',
 whyWeAreCautious:'A year of earlier surgery is not a lifetime of otherwise untreated blindness. The marginal cash requirement and local wait are unverified.',
 recommendationBlocker:'No priced additional SF cohort, accepted gift restriction or remaining funding amount has been verified.'},
 summary:[{label:'COST PER BETTER LIFE',value:money(r.costPerTenQalys),detail:'per 10 QALYs; conditional donor cash estimate'},{label:'POSITIVE CORE SCENARIOS',value:'$119K–$26.7M',detail:'Joint judgments, not a confidence interval; null and harm possible'},{label:'CENTRAL CASH BUDGET',value:'$1,000',detail:'Research allowance per assigned case, not a quote'},{label:'FUNDING ROOM',value:'Unknown',detail:'General giving is not a verified surgery offer'}],
 programSection:{body:'Pacific Vision Foundation supports eye care at 711 Van Ness. Eligible charity-care patients enter through the Lions clinic; CPMC clinicians and the surgery center are partners. The Patient Assistance Fund supports surgery costs. We treat this as one shared clinical pathway, not separate full health gains for PVF, Lions and CPMC. Its reported 570 charity cases are cumulative since 2020, not annual SF cataract operations.',
 steps:[{title:'Confirm the clinical and eligibility fit',detail:'An uninsured SF resident needs a physician referral, current income/residency eligibility and a clinically appropriate first-eye cataract diagnosis.'},{title:'Support the complete pathway',detail:'Coordinate assessment, surgery, access needs and postoperative follow-up; budget across assigned cases including failures.'},{title:'Compare with realistic alternative care',detail:'Estimate how much sooner surgery occurs and whether the gift expands care rather than replacing another payer.'}],
 boundary:'The underlying service is real; the exact additional donor-funded course is proposed. Current Lions intake excludes insurance, including government and partial coverage. The regional program is not SF-only. No second-eye or lifelong benefit is automatically credited.'},
 model:{headline:money(r.costPerTenQalys)+' per 10 QALYs',
 body:'The central $1,000 research budget assigns $250 to eligibility/navigation, $400 to facility/consumable support, $200 to medication/follow-up and $150 to transport/access contingency. All are unquoted allowances. The trial’s integrated one-year gain of 0.056 QALY is reduced by a judgmental 50% clinical/comparator transfer and 50% financing additionality. This gives 0.014 incremental QALY per assigned case.',
 equation:{label:'DONOR DOLLARS PER 10 QALYS',expression:'10 × $1,000 ÷ [0.5 × (0.056 × 0.5 − 0) − 0]',result:money(r.costPerTenQalys)},inputColumnLabel:'Central input',
 inputs:[{key:'cost',label:'Donor cash per assigned course',best:'$1,000',range:'$500–$2,000',confidence:'Research judgment',basis:'Complete cash allocation including unsuccessful referrals; partner underwriting assumed, not a provider quote.'},{key:'health',label:'External integrated one-year QALY gain',best:'0.056',range:'0.006–0.108 trial CI',confidence:'Randomized economic analysis',basis:'Expedited first-eye surgery versus approximately one-year wait; six-month EQ-5D observations extrapolated across the study year.'},{key:'transfer',label:'Clinical/comparator transfer',best:'50%',range:'50–100% in positive core cases',confidence:'Research judgment',basis:'Local age, severity, pathway and ordinary-care delay may differ; zero transfer is also possible.'},{key:'additionality',label:'Financing additionality',best:'50%',range:'25–75% in positive core cases',confidence:'Research judgment',basis:'Extra supported activity rather than replacement of existing PVF, Lions or partner financing; null modeled separately.'}],
 giftHeading:'One-year joint scenarios—not donation packages',
 sensitivity:core.map(s=>({case:s.id,headline:money(s.calculated.costPerTenQalys),detail:s.calculated.netQalys+' incremental QALY per assigned case; complete direct-resource diagnostic '+money(s.calculated.directResourcePrice)})),
 uncertaintyBoundary:'The trial effect is already assignment-based and integrated: no second completion, duration or falls multiplier. Trial complications are already included. Additional local shared harm and donor-specific disruption are separate diagnostic stresses.',
 fundingBoundary:'The central cash budget assumes $2,500 of partner clinical/facility/lens resources beyond donor cash. The $3,500 complete-resource diagnostic gives $2.5M/10 QALYs, not a fully net societal ICER. Neither partner commitment nor a marginal subsidy is verified. No valuation of waived charges or general leverage ratio is treated as economic cost.'},
 comparisonBridge:{headline:'Long-term denial could change the answer—but it is a different comparator',
 body:'A separate 13-year preference-based model produces much larger benefit than one year of earlier care. We show it to identify a decisive research question, not to select a flattering headline. The low-$250-cash case likewise assumes an unverified subsidy and does not enter the core range or ranking.',
 equation:{label:'SEPARATE OTHERWISE-UNTREATED LIFETIME CASE',expression:'10 × $1,000 ÷ (1.6212 × 0.5 × 0.5)',result:money(separate.find(s=>s.id==='otherwiseUntreatedLifetime')!.calculated.costPerTenQalys)},inputs:[],
 sensitivity:separate.map(s=>({case:s.id,headline:money(s.calculated.costPerTenQalys),detail:s.calculated.netQalys+' incremental QALY. '+s.reason})),
 boundary:'All separate cases are excluded from the ranking. At central health assumptions cash cost must be below $140 to beat $100K/10 QALYs; favorable health assumptions allow below $420. These are thresholds, not available offers. Nonpositive health results never become attractive negative prices.'},
 evidence:[{key:'First-eye trial',design:'Randomized trial economic evaluation, 2007',population:'306 women over 70 with bilateral cataracts; 288 economic participants after 18 missing six-month EQ-5D exclusions; most had relatively mild acuity impairment',result:'Expedited surgery versus routine waiting produced 0.056 integrated QALY over one year (95% CI 0.006–0.108).',transfer:'The local patient mix and untreated wait are unknown. The six-month utility value was assumed to apply one month after surgery and remain for a further 11 months. This is not linear six-month interpolation or complete 306-person intention-to-treat data.'},{key:'Second-eye counterweight',design:'Separate randomized economic evaluation',population:'Older women after first-eye surgery, with minimal remaining-eye dysfunction',result:'One-year QALY gain 0.015; confidence interval −0.039 to 0.068 includes no benefit.',transfer:'First-eye benefits must not be assigned to all surgery or added twice.'},{key:'Long-horizon model',design:'US visual-outcome/time-tradeoff model, 2013',population:'Modeled first-eye surgery over 13 years',result:'1.6212 modeled QALYs; not a randomized observation of lifetime improvement.',transfer:'A long-term untreated comparator is not interchangeable with an ordinary one-year delay.'}],
 reservations:['The proposed budget and funding additionality are low-confidence judgments.','No SF-resident first-eye queue or current waiting-time distribution is published in the reviewed material.','PVF and Lions share outcomes; financing constraints and partner capacity must be resolved before recommending a restricted gift.','General recipient EIN 94-2422439 is source-confirmed; that is not verification of current tax treatment or a specific gift restriction.'],
 excludedBenefits:['No additional falls, productivity, caregiver, mortality or monetary-return credit.','No automatic benefit after the one-year core horizon.','No bilateral total for a single eye, and no partner double-counting.','Patient time and future medical costs are not included in the direct-resource diagnostic.'],
 sources:data.sources.map(s=>({publisher:s.type,title:s.title,url:s.url,published:s.published??'Not stated',retrieved:s.retrieved,sourceType:s.type})),
};
export default function Page(){return <CharityResearchReport content={content}/>;}
