import type{Metadata}from'next';import CharityResearchReport,{type CharityReportContent}from'@/components/CharityResearchReport';
import model from '@/data/san-francisco/mnc-dental-cea-v1.json';import{dentalPreventionModel}from'@/lib/dental-prevention-model.mjs';
export const metadata:Metadata={title:'Mission Neighborhood Centers | Market for Impact',description:'A proposed child dental-prevention model separating cavity incidence from painful untreated disease.'};
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2});const scenarios=model.scenarios.map(s=>({...s,result:dentalPreventionModel(s)}));const central=scenarios[1];
const content:CharityReportContent={organization:model.organization,program:model.program,eyebrow:'CHARITY RESEARCH · SAN FRANCISCO · PROPOSED TRANCHE',published:'7 September 2026',modelVersion:model.version,
 nutshell:{headline:'Preventing tooth decay is useful. How much untreated pain would new funding actually prevent?',body:<><strong>Our central analyst scenario is $39.3M per better life (10 QALYs).</strong> This is a proposed dental-navigation and licensed-partner prevention course—not an existing verified MNC varnish program or an estimate of preschool’s total value. <a href="https://ai.rhyslindmark.com/donate/api/sf-mnc-model">Inspect the full model →</a></>,whyItMayWork:'A trusted early-childhood provider could connect otherwise-unreached families with completed preventive dental care.',whyWeAreCautious:'Existing toothbrushing and dental access may leave little incremental benefit. New cavities are not automatically prolonged painful disease.',recommendationBlocker:'A clinical partner, eligible uncovered children and a priced additional delivery plan remain unverified.'},
 summary:[{label:'CENTRAL SCENARIO',value:'$39.3M',detail:'per 10 incremental QALYs; explicit pain-duration judgment'},{label:'POSITIVE SCENARIOS',value:'$854K–$5.65B',detail:'Not confidence bounds; zero extra benefit possible'},{label:'COURSE BUDGET',value:'$250',detail:'Assumed two-year prevention/navigation cost'},{label:'FUNDING ROOM',value:'Unverified',detail:'Existing public and insurance funding must be reconciled'}],
 programSection:{body:'MNC’s Head Start services include toothbrushing and dental-home/referral support. We investigate a narrower proposed course for initially caries-free children otherwise missing prevention, delivered with a licensed partner. We do not infer that every child without a recorded dental visit is untreated or eligible.',steps:[{title:'Verify the real prevention gap',detail:'Check age, baseline dental status, current brushing, insurance and existing provider access.'},{title:'Complete clinical prevention',detail:'Budget four scheduled applications plus navigation and delivery overhead; referrals alone are not treatment.'},{title:'Measure untreated health burden',detail:'Follow person-level cavitated disease, prompt treatment and painful time, not just lesion counts.'}],boundary:'Head Start and local/state funding support mixed services. A private gift must add care rather than replace those commitments. This analysis does not advise individual dental treatment.'},
 model:{headline:'Central scenario: $39.3M per 10 QALYs.',body:'We assume $250 per course and a 40% baseline incident-caries risk. The trial odds ratio implies roughly 25 percentage points less incident caries before transfer and donor additionality discounts. We then separately model compatible untreated disease, pain probability and time-integrated pain loss.',equation:{label:'DOLLARS PER BETTER LIFE',expression:'10 × $250 ÷ (0.2497 × 50% × 50% × 0.5 cycles × 24% × 0.0085)',result:'≈ $39.3M per 10 QALYs'},inputs:model.judgments.map(j=>({key:j.key,label:j.label,confidence:'External anchor or explicitly subjective assumption',best:String(central[j.key as keyof typeof central]),range:scenarios.map(s=>String(s[j.key as keyof typeof s])).join(' / '),basis:j.basis})),inputColumnLabel:'Favorable / central / unfavorable inputs',giftHeading:'Illustrative $100,000: 400 courses and 0.0255 additional QALYs',sensitivity:scenarios.map(s=>({case:s.name,headline:money.format(s.result.costPerTenQalys!)+' per 10 QALYs',detail:s.result.additionalQalys.toPrecision(3)+' QALYs per $100,000; not available capacity'})),uncertaintyBoundary:model.nullBoundary,fundingBoundary:'The application-fee reference is historical Medicaid reimbursement, not current all-in SF cost. The assumed course budget needs clinical infrastructure and does not pay for all subsequent dental treatment.'},
 comparisonBridge:{headline:'Do not turn every prevented cavity into months of toothache.',body:'The incidence endpoint includes filled surfaces. Promptly treated disease may produce little continuing pain. Our provisional half-cycle assumption gives partial health credit; neither half a cycle nor its alternatives are locally measured.',equation:{label:'UNTREATED-DURATION SENSITIVITY',expression:'Price ≈ $19.63M ÷ equivalent six-month untreated cycles',result:'1 cycle: $19.63M · 0.5: $39.26M · 0.25: $78.51M'},inputs:[],sensitivity:[],boundary:'The 0.0085 QALY loss already covers a six-month cycle. Do not multiply by another half-year, count multiple lesions as multiple children, or apply pain probability to all new caries without a compatible disease-state/duration assumption.'},
 evidence:[{key:'local',design:'MNC program report',population:'Head Start and Early Head Start families',result:'Daily toothbrushing and dental navigation are established services.',transfer:'Varnish delivery, unmet eligible cohort and incremental costs are not verified.'},{key:'sf-rct',design:'SF randomized assigned-treatment trial',population:'376 initially caries-free young children; 280 with follow-up',result:'Control versus twice-yearly assigned varnish odds ratio3.77 for person-level cavitated or filled surfaces.',transfer:'Missing follow-up and accidental placebo applications limit interpretation. Use assignment effect, not actual-dose association; last follow-up was not uniformly24months.'},{key:'counter',design:'External supervised-brushing trial',population:'South African children; different ages and setting',result:'No significant additional caries benefit from varnish on top of supervised fluoridated brushing.',transfer:'A direct warning about the relevant add-on counterfactual, not proof of zero benefit at MNC.'}],
 reservations:['Pain duration and clinical-state compatibility dominate the health bridge.','Baseline risk and otherwise-unreached cohort are assumed.','Funding and clinical delivery are not an available quoted offer.','A narrow oral-health model does not measure preschool, family or educational value.'],excludedBenefits:model.excluded,sources:model.sources};
export default function MncReport(){return <CharityResearchReport content={content}/>;}
